// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void start_anim_Animation(lv_obj_t * TargetObject, int delay);
void start_anim2_Animation(lv_obj_t * TargetObject, int delay);
void rec_task_Animation(lv_obj_t * TargetObject, int delay);
void text_pulse_Animation(lv_obj_t * TargetObject, int delay);
void gif_play_Animation(lv_obj_t * TargetObject, int delay);
void blink_Animation(lv_obj_t * TargetObject, int delay);
void extensionstart1_Animation(lv_obj_t * TargetObject, int delay);
void extensionstart2_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Page_Battery
void ui_Page_Battery_screen_init(void);
void ui_event_Page_Battery(lv_event_t * e);
lv_obj_t * ui_Page_Battery;
lv_obj_t * ui_batteryimg;


// SCREEN: ui_Page_Startup
void ui_Page_Startup_screen_init(void);
void ui_event_Page_Startup(lv_event_t * e);
lv_obj_t * ui_Page_Startup;
lv_obj_t * ui_startuplogo;


// SCREEN: ui_Page_Loading
void ui_Page_Loading_screen_init(void);
void ui_event_Page_Loading(lv_event_t * e);
lv_obj_t * ui_Page_Loading;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_loadpert;


// SCREEN: ui_Page_Avatar
void ui_Page_Avatar_screen_init(void);
void ui_event_Page_Avatar(lv_event_t * e);
lv_obj_t * ui_Page_Avatar;
lv_obj_t * ui_virp;
lv_obj_t * ui_virsmile;
void ui_event_virbtn1(lv_event_t * e);
lv_obj_t * ui_virbtn1;
lv_obj_t * ui_virtext1;
void ui_event_virbtn2(lv_event_t * e);
lv_obj_t * ui_virbtn2;
lv_obj_t * ui_virtext2;


// SCREEN: ui_Page_Home
void ui_Page_Home_screen_init(void);
void ui_event_Page_Home(lv_event_t * e);
lv_obj_t * ui_Page_Home;
lv_obj_t * ui_mainlist;
lv_obj_t * ui_mainlp1;
void ui_event_mainbtn1(lv_event_t * e);
lv_obj_t * ui_mainbtn1;
lv_obj_t * ui_mainlp2;
void ui_event_mainbtn2(lv_event_t * e);
lv_obj_t * ui_mainbtn2;
lv_obj_t * ui_mainlp3;
void ui_event_mainbtn3(lv_event_t * e);
lv_obj_t * ui_mainbtn3;
lv_obj_t * ui_mainlp4;
void ui_event_mainbtn4(lv_event_t * e);
lv_obj_t * ui_mainbtn4;
lv_obj_t * ui_maincontent;
lv_obj_t * ui_Devicep;
lv_obj_t * ui_maintime;
lv_obj_t * ui_mainwifi;
lv_obj_t * ui_mainb;
lv_obj_t * ui_btpert;
lv_obj_t * ui_mainble;
lv_obj_t * ui_maintitle;
lv_obj_t * ui_mcontrolp;


// SCREEN: ui_Page_Connect
void ui_Page_Connect_screen_init(void);
lv_obj_t * ui_Page_Connect;
lv_obj_t * ui_conn_arcl;
lv_obj_t * ui_conn_arcr;
lv_obj_t * ui_conn_panel1;
lv_obj_t * ui_connp11;
lv_obj_t * ui_connp12;
lv_obj_t * ui_connp13;
lv_obj_t * ui_connp14;
lv_obj_t * ui_conn_panel2;
lv_obj_t * ui_connp21;
lv_obj_t * ui_connp22;
lv_obj_t * ui_connp23;
lv_obj_t * ui_connp24;
lv_obj_t * ui_conn_QR;
void ui_event_conncancel(lv_event_t * e);
lv_obj_t * ui_conncancel;
void ui_event_connp1(lv_event_t * e);
lv_obj_t * ui_connp1;
void ui_event_arrow1(lv_event_t * e);
lv_obj_t * ui_arrow1;
void ui_event_connp2(lv_event_t * e);
lv_obj_t * ui_connp2;
void ui_event_arrow2(lv_event_t * e);
lv_obj_t * ui_arrow2;


// SCREEN: ui_Page_Network
void ui_Page_Network_screen_init(void);
lv_obj_t * ui_Page_Network;
lv_obj_t * ui_wifip1;
lv_obj_t * ui_wifiicon;
lv_obj_t * ui_wifissid;
lv_obj_t * ui_wifibtnt;
lv_obj_t * ui_wifimqtt;
lv_obj_t * ui_wifip3;
lv_obj_t * ui_wifitext3;
lv_obj_t * ui_wifilogo;
lv_obj_t * ui_wifitext2;
void ui_event_wificancel(lv_event_t * e);
lv_obj_t * ui_wificancel;


// SCREEN: ui_Page_Notask
void ui_Page_Notask_screen_init(void);
lv_obj_t * ui_Page_Notask;
lv_obj_t * ui_notasktext;
void ui_event_curtask1b(lv_event_t * e);
lv_obj_t * ui_curtask1b;
lv_obj_t * ui_Label3;


// SCREEN: ui_Page_ModelOTA
void ui_Page_ModelOTA_screen_init(void);
lv_obj_t * ui_Page_ModelOTA;
lv_obj_t * ui_waittext;
void ui_event_waitb(lv_event_t * e);
lv_obj_t * ui_waitb;
lv_obj_t * ui_waitarc;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_otap;
lv_obj_t * ui_otatper;
lv_obj_t * ui_otatsym;


// SCREEN: ui_Page_Revtask
void ui_Page_Revtask_screen_init(void);
lv_obj_t * ui_Page_Revtask;
lv_obj_t * ui_revtext;
lv_obj_t * ui_Spinner3;


// SCREEN: ui_Page_ViewAva
void ui_Page_ViewAva_screen_init(void);
void ui_event_Page_ViewAva(lv_event_t * e);
lv_obj_t * ui_Page_ViewAva;


// SCREEN: ui_Page_ViewLive
void ui_Page_ViewLive_screen_init(void);
void ui_event_Page_ViewLive(lv_event_t * e);
lv_obj_t * ui_Page_ViewLive;
lv_obj_t * ui_viewlivp2;
lv_obj_t * ui_viewtext;
void ui_event_viewback(lv_event_t * e);
lv_obj_t * ui_viewback;


// SCREEN: ui_Page_Example
void ui_Page_Example_screen_init(void);
void ui_event_Page_Example(lv_event_t * e);
lv_obj_t * ui_Page_Example;
lv_obj_t * ui_menulist;
lv_obj_t * ui_custp1;
void ui_event_custbtn1(lv_event_t * e);
lv_obj_t * ui_custbtn1;
lv_obj_t * ui_custp2;
void ui_event_custbtn2(lv_event_t * e);
lv_obj_t * ui_custbtn2;
lv_obj_t * ui_custp3;
void ui_event_custbtn3(lv_event_t * e);
lv_obj_t * ui_custbtn3;
lv_obj_t * ui_menulp1;
void ui_event_menubtn1(lv_event_t * e);
lv_obj_t * ui_menubtn1;
lv_obj_t * ui_menulp2;
void ui_event_menubtn2(lv_event_t * e);
lv_obj_t * ui_menubtn2;
lv_obj_t * ui_menulp3;
void ui_event_menubtn3(lv_event_t * e);
lv_obj_t * ui_menubtn3;
lv_obj_t * ui_menulp4;
void ui_event_menubtn4(lv_event_t * e);
lv_obj_t * ui_menubtn4;
lv_obj_t * ui_Label1;
lv_obj_t * ui_mimgp;
lv_obj_t * ui_lcontrolp;


// SCREEN: ui_Page_Set
void ui_Page_Set_screen_init(void);
void ui_event_Page_Set(lv_event_t * e);
lv_obj_t * ui_Page_Set;
lv_obj_t * ui_Set_panel;
void ui_event_setback(lv_event_t * e);
lv_obj_t * ui_setback;
lv_obj_t * ui_Image1;
lv_obj_t * ui_setbackt;
void ui_event_setdown(lv_event_t * e);
lv_obj_t * ui_setdown;
lv_obj_t * ui_setdownt;
void ui_event_setapp(lv_event_t * e);
lv_obj_t * ui_setapp;
lv_obj_t * ui_setappt;
void ui_event_setwifi(lv_event_t * e);
lv_obj_t * ui_setwifi;
lv_obj_t * ui_setwifit;
void ui_event_setble(lv_event_t * e);
lv_obj_t * ui_setble;
lv_obj_t * ui_setblet;
lv_obj_t * ui_setblesw;
void ui_event_setvol(lv_event_t * e);
lv_obj_t * ui_setvol;
lv_obj_t * ui_setvolt;
void ui_event_setbri(lv_event_t * e);
lv_obj_t * ui_setbri;
lv_obj_t * ui_setbrit;
void ui_event_settime(lv_event_t * e);
lv_obj_t * ui_settime;
lv_obj_t * ui_settimt;
void ui_event_setrgb(lv_event_t * e);
lv_obj_t * ui_setrgb;
lv_obj_t * ui_setrgbt;
lv_obj_t * ui_setrgbsw;
void ui_event_setww(lv_event_t * e);
lv_obj_t * ui_setww;
lv_obj_t * ui_setwwt;
lv_obj_t * ui_setwwsw;
void ui_event_setdev(lv_event_t * e);
lv_obj_t * ui_setdev;
lv_obj_t * ui_setdevt;
void ui_event_setfac(lv_event_t * e);
lv_obj_t * ui_setfac;
lv_obj_t * ui_setfact;
lv_obj_t * ui_settextp;
lv_obj_t * ui_Set_title;
lv_obj_t * ui_scontrolp;


// SCREEN: ui_Page_Slider
void ui_Page_Slider_screen_init(void);
lv_obj_t * ui_Page_Slider;
lv_obj_t * ui_bvpb;
lv_obj_t * ui_bvbimg;
lv_obj_t * ui_bvbt;
lv_obj_t * ui_bvbv;
lv_obj_t * ui_bvs;
lv_obj_t * ui_bvtp;
lv_obj_t * ui_bvtitle;
void ui_event_bvback(lv_event_t * e);
lv_obj_t * ui_bvback;
lv_obj_t * ui_vp;
void ui_event_vslider(lv_event_t * e);
lv_obj_t * ui_vslider;
lv_obj_t * ui_bp;
void ui_event_bslider(lv_event_t * e);
lv_obj_t * ui_bslider;


// SCREEN: ui_Page_About
void ui_Page_About_screen_init(void);
lv_obj_t * ui_Page_About;
lv_obj_t * ui_AboutP;
void ui_event_aboutdevname(lv_event_t * e);
lv_obj_t * ui_aboutdevname;
lv_obj_t * ui_devnamet1;
lv_obj_t * ui_devnamet2;
void ui_event_aboutespversion(lv_event_t * e);
lv_obj_t * ui_aboutespversion;
lv_obj_t * ui_espversiont1;
lv_obj_t * ui_espversiont2;
void ui_event_aboutaiversion(lv_event_t * e);
lv_obj_t * ui_aboutaiversion;
lv_obj_t * ui_aiversion1;
lv_obj_t * ui_aiversion2;
void ui_event_aboutsn(lv_event_t * e);
lv_obj_t * ui_aboutsn;
lv_obj_t * ui_snt1;
lv_obj_t * ui_snt2;
void ui_event_abouteui(lv_event_t * e);
lv_obj_t * ui_abouteui;
lv_obj_t * ui_euit1;
lv_obj_t * ui_euit2;
void ui_event_aboutblemac(lv_event_t * e);
lv_obj_t * ui_aboutblemac;
lv_obj_t * ui_blet1;
lv_obj_t * ui_blet2;
void ui_event_aboutwifimac(lv_event_t * e);
lv_obj_t * ui_aboutwifimac;
lv_obj_t * ui_wifit1;
lv_obj_t * ui_wifit2;
void ui_event_Paboutb(lv_event_t * e);
lv_obj_t * ui_Paboutb;
lv_obj_t * ui_abtp;
lv_obj_t * ui_abtitle;


// SCREEN: ui_Page_Swipe
void ui_Page_Swipe_screen_init(void);
lv_obj_t * ui_Page_Swipe;
void ui_event_spsilder(lv_event_t * e);
lv_obj_t * ui_spsilder;
void ui_event_spback(lv_event_t * e);
lv_obj_t * ui_spback;
lv_obj_t * ui_sptext;
lv_obj_t * ui_swipep;
lv_obj_t * ui_sptitle;
lv_obj_t * ui_swipep2;
lv_obj_t * ui_sptext2;
lv_obj_t * ui_Spinner4;


// SCREEN: ui_Page_Extension
void ui_Page_Extension_screen_init(void);
lv_obj_t * ui_Page_Extension;
lv_obj_t * ui_extensionbubble1;
lv_obj_t * ui_extensionbubble1Value;
lv_obj_t * ui_extensionbubble1Unit;
lv_obj_t * ui_extensionbubble1Icon;
lv_obj_t * ui_extensionbubble1Icon2;
void ui_event_extensionbubble2(lv_event_t * e);
lv_obj_t * ui_extensionbubble2;
lv_obj_t * ui_extensionbubble2Value;
lv_obj_t * ui_extensionbubble2Unit;
lv_obj_t * ui_extensionbubble2Icon;
lv_obj_t * ui_extensionbubble2Icon2;
void ui_event_extensionbubble3(lv_event_t * e);
lv_obj_t * ui_extensionbubble3;
lv_obj_t * ui_extensionbubble3Value;
lv_obj_t * ui_extensionbubble3Unit;
lv_obj_t * ui_extensionbubble3Icon;
lv_obj_t * ui_extensionbubble3Icon2;
void ui_event_extensionbubble4(lv_event_t * e);
lv_obj_t * ui_extensionbubble4;
lv_obj_t * ui_extensionbubble4Value;
lv_obj_t * ui_extensionbubble4Unit;
lv_obj_t * ui_extensionbubble4Icon;
lv_obj_t * ui_extensionbubble4Icon2;
void ui_event_extensionpanel(lv_event_t * e);
lv_obj_t * ui_extensionpanel;
lv_obj_t * ui_extensionNone;
lv_obj_t * ui_extenNonetext;
lv_obj_t * ui_extenNonetext2;
void ui_event_extenNoneback(lv_event_t * e);
lv_obj_t * ui_extenNoneback;


// SCREEN: ui_Page_OTA
void ui_Page_OTA_screen_init(void);
lv_obj_t * ui_Page_OTA;
lv_obj_t * ui_otapanel;
lv_obj_t * ui_otatext;
lv_obj_t * ui_otastatus;
lv_obj_t * ui_otaspinner;
lv_obj_t * ui_otaicon;
lv_obj_t * ui_otaarc;
void ui_event_otaback(lv_event_t * e);
lv_obj_t * ui_otaback;


// SCREEN: ui_Page_Sleep
void ui_Page_Sleep_screen_init(void);
lv_obj_t * ui_Page_Sleep;
void ui_event_sleeptimeroller(lv_event_t * e);
lv_obj_t * ui_sleeptimeroller;
void ui_event_slpback(lv_event_t * e);
lv_obj_t * ui_slpback;
void ui_event_sleepswitchp(lv_event_t * e);
lv_obj_t * ui_sleepswitchp;
lv_obj_t * ui_sleepswitcht;
void ui_event_sleepswitch(lv_event_t * e);
lv_obj_t * ui_sleepswitch;


// SCREEN: ui_Page_Push2talk
void ui_Page_Push2talk_screen_init(void);
void ui_event_Page_Push2talk(lv_event_t * e);
lv_obj_t * ui_Page_Push2talk;
lv_obj_t * ui_push2talkpanel2;
void ui_event_push2talkarc(lv_event_t * e);
lv_obj_t * ui_push2talkarc;
lv_obj_t * ui_push2talkp2t1;
lv_obj_t * ui_push2talkp2t2;
lv_obj_t * ui_push2talkknob;
lv_obj_t * ui_push2talkpanel3;
void ui_event_p2tobj(lv_event_t * e);
lv_obj_t * ui_p2tobj;
lv_obj_t * ui_p2tobj1;
lv_obj_t * ui_p2tobj2;
void ui_event_p2tcomparison(lv_event_t * e);
lv_obj_t * ui_p2tcomparison;
lv_obj_t * ui_p2tcomparison1;
lv_obj_t * ui_p2tcomparison2;
void ui_event_p2tbehavior(lv_event_t * e);
lv_obj_t * ui_p2tbehavior;
lv_obj_t * ui_p2tbehavior1;
lv_obj_t * ui_p2tbehavior2;
void ui_event_p2tfeat(lv_event_t * e);
lv_obj_t * ui_p2tfeat;
lv_obj_t * ui_p2tfeat1;
lv_obj_t * ui_p2tfeat2;
void ui_event_p2tnotify(lv_event_t * e);
lv_obj_t * ui_p2tnotify;
lv_obj_t * ui_p2tnotify1;
lv_obj_t * ui_p2tnotify2;
void ui_event_p2ttime(lv_event_t * e);
lv_obj_t * ui_p2ttime;
lv_obj_t * ui_p2ttime1;
lv_obj_t * ui_p2ttime2;
void ui_event_p2tfreq(lv_event_t * e);
lv_obj_t * ui_p2tfreq;
lv_obj_t * ui_p2tfreq1;
lv_obj_t * ui_p2tfreq2;
void ui_event_p2tcancel(lv_event_t * e);
lv_obj_t * ui_p2tcancel;
void ui_event_p2tcheck(lv_event_t * e);
lv_obj_t * ui_p2tcheck;
lv_obj_t * ui_p2texit;


// SCREEN: ui_Page_Guideavatar
void ui_Page_Guideavatar_screen_init(void);
void ui_event_Page_Guideavatar(lv_event_t * e);
lv_obj_t * ui_Page_Guideavatar;
void ui_event_guide1p1(lv_event_t * e);
lv_obj_t * ui_guide1p1;
lv_obj_t * ui_guide1img1;
lv_obj_t * ui_guide1t1;
void ui_event_guide1p2(lv_event_t * e);
lv_obj_t * ui_guide1p2;
lv_obj_t * ui_guide1img2;
lv_obj_t * ui_guide1t2;
void ui_event_guide1p3(lv_event_t * e);
lv_obj_t * ui_guide1p3;
void ui_event_guide1btn1(lv_event_t * e);
lv_obj_t * ui_guide1btn1;
lv_obj_t * ui_guide1btn1t;
void ui_event_guide1btn2(lv_event_t * e);
lv_obj_t * ui_guide1btn2;
lv_obj_t * ui_guide1btn2t;
void ui_event_guide1btn3(lv_event_t * e);
lv_obj_t * ui_guide1btn3;


// SCREEN: ui_Page_Guidelive
void ui_Page_Guidelive_screen_init(void);
void ui_event_Page_Guidelive(lv_event_t * e);
lv_obj_t * ui_Page_Guidelive;
void ui_event_guide2p1(lv_event_t * e);
lv_obj_t * ui_guide2p1;
lv_obj_t * ui_guide2t1;
void ui_event_guide2p2(lv_event_t * e);
lv_obj_t * ui_guide2p2;
lv_obj_t * ui_guide2img2;
lv_obj_t * ui_guide2t2;


// SCREEN: ui_Page_Flag
void ui_Page_Flag_screen_init(void);
void ui_event_Page_Flag(lv_event_t * e);
lv_obj_t * ui_Page_Flag;
lv_obj_t * ui_guideflagp;
void ui_event_guidebtn1(lv_event_t * e);
lv_obj_t * ui_guidebtn1;
lv_obj_t * ui_guidebtn1t;
void ui_event_guidebtn2(lv_event_t * e);
lv_obj_t * ui_guidebtn2;
lv_obj_t * ui_guidebtn2t;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1328823148[1] = {&ui_img_1195720223};
const lv_img_dsc_t * ui_imgset_590839094[1] = {&ui_img_1722191473};
const lv_img_dsc_t * ui_imgset_800621560[1] = {&ui_img_30219097};
const lv_img_dsc_t * ui_imgset_1225629734[1] = {&ui_img_631814683};
const lv_img_dsc_t * ui_imgset_1798734462[1] = {&ui_img_578579305};
const lv_img_dsc_t * ui_imgset_speaking[2] = {&ui_img_speaking1_png, &ui_img_speaking2_png};
const lv_img_dsc_t * ui_imgset_wifi_[4] = {&ui_img_wifi_0_png, &ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void start_anim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 200);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 2500);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void start_anim2_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void rec_task_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 400);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 500);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, -215, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 500);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_2, 0, 215);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 600);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t * PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 500);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_3, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 600);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_3, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 0);
    lv_anim_set_early_apply(&PropertyAnimation_3, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_3, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_3);

}
void text_pulse_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 250);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 250);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 250);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 500);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 0);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, -180, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void gif_play_Animation(lv_obj_t * TargetObject, int delay)
{

}
void blink_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 2000);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 500);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void extensionstart1_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 400);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -100, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 100);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 600);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void extensionstart2_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 400);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 315, 80);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 100);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 600);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Page_Battery(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        slbattery_cb(e);
    }
}
void ui_event_Page_Startup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        startload_cb(e);
    }
}
void ui_event_Page_Loading(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        loadscrload_cb(e);
    }
}
void ui_event_Page_Avatar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        virclick_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        virscrload_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        virscrunload_cb(e);
    }
}
void ui_event_virbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        virb1c_cb(e);
    }
}
void ui_event_virbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        virb2c_cb(e);
    }
}
void ui_event_Page_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        maingestureup_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        maingesturedown_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        mainclick_cb(e);
    }
}
void ui_event_mainbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        main1c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        main1f_cb(e);
    }
}
void ui_event_mainbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        main2c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        main2f_cb(e);
    }
}
void ui_event_mainbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        main3c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        main3f_cb(e);
    }
}
void ui_event_mainbtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        main4c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        main4f_cb(e);
    }
}
void ui_event_conncancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backset_cb(e);
    }
}
void ui_event_connp1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        arr1c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        arr1f_cb(e);
    }
}
void ui_event_arrow1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        arr1c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        arr1f_cb(e);
    }
}
void ui_event_connp2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        arr2c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        arr2f_cb(e);
    }
}
void ui_event_arrow2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        arr2c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        arr2f_cb(e);
    }
}
void ui_event_wificancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backset_cb(e);
    }
}
void ui_event_curtask1b(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backmenu_cb(e);
    }
}
void ui_event_waitb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backmenu_cb(e);
    }
}
void ui_event_Page_ViewAva(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        viewac_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        viewaf_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        viewasl_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        viewasul_cb(e);
    }
}
void ui_event_Page_ViewLive(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        viewlc_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        viewlf_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        viewlsl_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        viewlsul_cb(e);
    }
}
void ui_event_viewback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        vieback_cb(e);
    }
}
void ui_event_Page_Example(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        lgesright_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        lgesleft_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        lclick_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        lunlds_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        lunlded_cb(e);
    }
}
void ui_event_custbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        custb1c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        custb1f_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        custb1df_cb(e);
    }
}
void ui_event_custbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        custb2c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        custb2f_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        custb2df_cb(e);
    }
}
void ui_event_custbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        custb3c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        custb3f_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        custb3df_cb(e);
    }
}
void ui_event_menubtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backmenu_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        loctask1f_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        loctask1df_cb(e);
    }
}
void ui_event_menubtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        loctask2c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        loctask2f_cb(e);
    }
}
void ui_event_menubtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        loctask3c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        loctask3f_cb(e);
    }
}
void ui_event_menubtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        loctask4c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        loctask4f_cb(e);
    }
}
void ui_event_Page_Set(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        sgesup_cb(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        sgesdown_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        sclick_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        setsl_cb(e);
    }
}
void ui_event_setback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        setbackf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setbackdf_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        backmenu_cb(e);
    }
}
void ui_event_setdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setdownc_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setdownf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setdowndf_cb(e);
    }
}
void ui_event_setapp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        setappf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setappdf_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        setappc_cb(e);
    }
}
void ui_event_setwifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setwific_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setwifif_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setwifidf_cb(e);
    }
}
void ui_event_setble(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setblec_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setblef_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setbledf_cb(e);
    }
}
void ui_event_setvol(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setvolc_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setvolf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setvoldf_cb(e);
    }
}
void ui_event_setbri(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setbric_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setbrif_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setbridf_cb(e);
    }
}
void ui_event_settime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        settimec_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        settimef_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        settimedf_cb(e);
    }
}
void ui_event_setrgb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setrgbc_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setrgbf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setrgbdf_cb(e);
    }
}
void ui_event_setww(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setwwc_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setwwf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setwwdf_cb(e);
    }
}
void ui_event_setdev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        setdevf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setdevdf_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        setdevc_cb(e);
    }
}
void ui_event_setfac(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setfac_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        setfacf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        setfacdf_cb(e);
    }
}
void ui_event_bvback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backset_cb(e);
    }
}
void ui_event_vslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        volvc_cb(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        volre_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        volfs_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        voldf_cb(e);
    }
}
void ui_event_bslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        brivc_cb(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        brire_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        brifs_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        bridf_cb(e);
    }
}
void ui_event_aboutdevname(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_aboutespversion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        absvf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        absvdf_cb(e);
    }
}
void ui_event_aboutaiversion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        absvf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        absvdf_cb(e);
    }
}
void ui_event_aboutsn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        absnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        absndf_cb(e);
    }
}
void ui_event_abouteui(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abeuif_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abeuidf_cb(e);
    }
}
void ui_event_aboutblemac(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abblef_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abbledf_cb(e);
    }
}
void ui_event_aboutwifimac(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abblef_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abbledf_cb(e);
    }
}
void ui_event_Paboutb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backset_cb(e);
    }
}
void ui_event_spsilder(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slidervc_cb(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        sliderr_cb(e);
    }
}
void ui_event_spback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backset_cb(e);
    }
}
void ui_event_extensionbubble2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        bubble2f_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        bubble2c_cb(e);
    }
}
void ui_event_extensionbubble3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        bubble3f_cb(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        bubble3c_cb(e);
    }
}
void ui_event_extensionbubble4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        bubble4c_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        bubble4f_cb(e);
    }
}
void ui_event_extensionpanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        extensionpanel_cb(e);
    }
}
void ui_event_extenNoneback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backmenu_cb(e);
    }
}
void ui_event_otaback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        otaback_cb(e);
    }
}
void ui_event_sleeptimeroller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        sleeptimeset_cb(e);
    }
}
void ui_event_slpback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backset_cb(e);
    }
}
void ui_event_sleepswitchp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setsleepsw_cb(e);
    }
}
void ui_event_sleepswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        sleepswitch_cb(e);
    }
}
void ui_event_Page_Push2talk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        p2tclick_cb(e);
    }
}
void ui_event_push2talkarc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        p2tvaluechange_cb(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        p2tfocus_cb(e);
    }
}
void ui_event_p2tobj(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_p2tcomparison(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_p2tbehavior(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_p2tfeat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_p2tnotify(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_p2ttime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_p2tfreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        abdnf_cb(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        abdndf_cb(e);
    }
}
void ui_event_p2tcancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        push2talkcancel_cb(e);
    }
}
void ui_event_p2tcheck(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        push2talkcheck_cb(e);
    }
}
void ui_event_Page_Guideavatar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        pageguideavaf_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        pageguideavascrload_cb(e);
    }
}
void ui_event_guide1p1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guideavaclick_cb(e);
    }
}
void ui_event_guide1p2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guide2avaclick_cb(e);
    }
}
void ui_event_guide1p3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guide2avaclick_cb(e);
    }
}
void ui_event_guide1btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        backmenu_cb(e);
    }
}
void ui_event_guide1btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guide1btn2c_cb(e);
    }
}
void ui_event_guide1btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guide1btn3c_cb(e);
    }
}
void ui_event_Page_Guidelive(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        pageguidelivef_cb(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        pageguidelivescrload_cb(e);
    }
}
void ui_event_guide2p1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guideliveclick_cb(e);
    }
}
void ui_event_guide2p2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guide2liveclick_cb(e);
    }
}
void ui_event_Page_Flag(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        flagloaded_cb(e);
    }
}
void ui_event_guidebtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guidebtn1click_cb(e);
    }
}
void ui_event_guidebtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        guidebtn2click_cb(e);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        start_anim_Animation(ui_startuplogo, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Page_Battery_screen_init();
    ui_Page_Startup_screen_init();
    ui_Page_Loading_screen_init();
    ui_Page_Avatar_screen_init();
    ui_Page_Home_screen_init();
    ui_Page_Connect_screen_init();
    ui_Page_Network_screen_init();
    ui_Page_Notask_screen_init();
    ui_Page_ModelOTA_screen_init();
    ui_Page_Revtask_screen_init();
    ui_Page_ViewAva_screen_init();
    ui_Page_ViewLive_screen_init();
    ui_Page_Example_screen_init();
    ui_Page_Set_screen_init();
    ui_Page_Slider_screen_init();
    ui_Page_About_screen_init();
    ui_Page_Swipe_screen_init();
    ui_Page_Extension_screen_init();
    ui_Page_OTA_screen_init();
    ui_Page_Sleep_screen_init();
    ui_Page_Push2talk_screen_init();
    ui_Page_Guideavatar_screen_init();
    ui_Page_Guidelive_screen_init();
    ui_Page_Flag_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_Page_Battery);
}
