// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#ifndef _SENSECAP_WATCHER_UI_H
#define _SENSECAP_WATCHER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void start_anim_Animation(lv_obj_t * TargetObject, int delay);
void start_anim2_Animation(lv_obj_t * TargetObject, int delay);
void rec_task_Animation(lv_obj_t * TargetObject, int delay);
void text_pulse_Animation(lv_obj_t * TargetObject, int delay);
void gif_play_Animation(lv_obj_t * TargetObject, int delay);
void blink_Animation(lv_obj_t * TargetObject, int delay);
void extensionstart1_Animation(lv_obj_t * TargetObject, int delay);
void extensionstart2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Page_Battery
void ui_Page_Battery_screen_init(void);
void ui_event_Page_Battery(lv_event_t * e);
extern lv_obj_t * ui_Page_Battery;
extern lv_obj_t * ui_batteryimg;
// SCREEN: ui_Page_Startup
void ui_Page_Startup_screen_init(void);
void ui_event_Page_Startup(lv_event_t * e);
extern lv_obj_t * ui_Page_Startup;
extern lv_obj_t * ui_startuplogo;
// SCREEN: ui_Page_Loading
void ui_Page_Loading_screen_init(void);
void ui_event_Page_Loading(lv_event_t * e);
extern lv_obj_t * ui_Page_Loading;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_loadpert;
// SCREEN: ui_Page_Avatar
void ui_Page_Avatar_screen_init(void);
void ui_event_Page_Avatar(lv_event_t * e);
extern lv_obj_t * ui_Page_Avatar;
extern lv_obj_t * ui_virp;
extern lv_obj_t * ui_virsmile;
void ui_event_virbtn1(lv_event_t * e);
extern lv_obj_t * ui_virbtn1;
extern lv_obj_t * ui_virtext1;
void ui_event_virbtn2(lv_event_t * e);
extern lv_obj_t * ui_virbtn2;
extern lv_obj_t * ui_virtext2;
// SCREEN: ui_Page_Home
void ui_Page_Home_screen_init(void);
void ui_event_Page_Home(lv_event_t * e);
extern lv_obj_t * ui_Page_Home;
extern lv_obj_t * ui_mainlist;
extern lv_obj_t * ui_mainlp1;
void ui_event_mainbtn1(lv_event_t * e);
extern lv_obj_t * ui_mainbtn1;
extern lv_obj_t * ui_mainlp2;
void ui_event_mainbtn2(lv_event_t * e);
extern lv_obj_t * ui_mainbtn2;
extern lv_obj_t * ui_mainlp3;
void ui_event_mainbtn3(lv_event_t * e);
extern lv_obj_t * ui_mainbtn3;
extern lv_obj_t * ui_mainlp4;
void ui_event_mainbtn4(lv_event_t * e);
extern lv_obj_t * ui_mainbtn4;
extern lv_obj_t * ui_maincontent;
extern lv_obj_t * ui_Devicep;
extern lv_obj_t * ui_maintime;
extern lv_obj_t * ui_mainwifi;
extern lv_obj_t * ui_mainb;
extern lv_obj_t * ui_btpert;
extern lv_obj_t * ui_mainble;
extern lv_obj_t * ui_maintitle;
extern lv_obj_t * ui_mcontrolp;
// SCREEN: ui_Page_Connect
void ui_Page_Connect_screen_init(void);
extern lv_obj_t * ui_Page_Connect;
extern lv_obj_t * ui_conn_arcl;
extern lv_obj_t * ui_conn_arcr;
extern lv_obj_t * ui_conn_panel1;
extern lv_obj_t * ui_connp11;
extern lv_obj_t * ui_connp12;
extern lv_obj_t * ui_connp13;
extern lv_obj_t * ui_connp14;
extern lv_obj_t * ui_conn_panel2;
extern lv_obj_t * ui_connp21;
extern lv_obj_t * ui_connp22;
extern lv_obj_t * ui_connp23;
extern lv_obj_t * ui_connp24;
extern lv_obj_t * ui_conn_QR;
void ui_event_conncancel(lv_event_t * e);
extern lv_obj_t * ui_conncancel;
void ui_event_connp1(lv_event_t * e);
extern lv_obj_t * ui_connp1;
void ui_event_arrow1(lv_event_t * e);
extern lv_obj_t * ui_arrow1;
void ui_event_connp2(lv_event_t * e);
extern lv_obj_t * ui_connp2;
void ui_event_arrow2(lv_event_t * e);
extern lv_obj_t * ui_arrow2;
// SCREEN: ui_Page_Network
void ui_Page_Network_screen_init(void);
extern lv_obj_t * ui_Page_Network;
extern lv_obj_t * ui_wifip1;
extern lv_obj_t * ui_wifiicon;
extern lv_obj_t * ui_wifissid;
extern lv_obj_t * ui_wifibtnt;
extern lv_obj_t * ui_wifimqtt;
extern lv_obj_t * ui_wifip3;
extern lv_obj_t * ui_wifitext3;
extern lv_obj_t * ui_wifilogo;
extern lv_obj_t * ui_wifitext2;
void ui_event_wificancel(lv_event_t * e);
extern lv_obj_t * ui_wificancel;
// SCREEN: ui_Page_Notask
void ui_Page_Notask_screen_init(void);
extern lv_obj_t * ui_Page_Notask;
extern lv_obj_t * ui_notasktext;
void ui_event_curtask1b(lv_event_t * e);
extern lv_obj_t * ui_curtask1b;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Page_ModelOTA
void ui_Page_ModelOTA_screen_init(void);
extern lv_obj_t * ui_Page_ModelOTA;
extern lv_obj_t * ui_waittext;
void ui_event_waitb(lv_event_t * e);
extern lv_obj_t * ui_waitb;
extern lv_obj_t * ui_waitarc;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_otap;
extern lv_obj_t * ui_otatper;
extern lv_obj_t * ui_otatsym;
// SCREEN: ui_Page_Revtask
void ui_Page_Revtask_screen_init(void);
extern lv_obj_t * ui_Page_Revtask;
extern lv_obj_t * ui_revtext;
extern lv_obj_t * ui_Spinner3;
// SCREEN: ui_Page_ViewAva
void ui_Page_ViewAva_screen_init(void);
void ui_event_Page_ViewAva(lv_event_t * e);
extern lv_obj_t * ui_Page_ViewAva;
// SCREEN: ui_Page_ViewLive
void ui_Page_ViewLive_screen_init(void);
void ui_event_Page_ViewLive(lv_event_t * e);
extern lv_obj_t * ui_Page_ViewLive;
extern lv_obj_t * ui_viewlivp2;
extern lv_obj_t * ui_viewtext;
void ui_event_viewback(lv_event_t * e);
extern lv_obj_t * ui_viewback;
// SCREEN: ui_Page_Example
void ui_Page_Example_screen_init(void);
void ui_event_Page_Example(lv_event_t * e);
extern lv_obj_t * ui_Page_Example;
extern lv_obj_t * ui_menulist;
extern lv_obj_t * ui_custp1;
void ui_event_custbtn1(lv_event_t * e);
extern lv_obj_t * ui_custbtn1;
extern lv_obj_t * ui_custp2;
void ui_event_custbtn2(lv_event_t * e);
extern lv_obj_t * ui_custbtn2;
extern lv_obj_t * ui_custp3;
void ui_event_custbtn3(lv_event_t * e);
extern lv_obj_t * ui_custbtn3;
extern lv_obj_t * ui_menulp1;
void ui_event_menubtn1(lv_event_t * e);
extern lv_obj_t * ui_menubtn1;
extern lv_obj_t * ui_menulp2;
void ui_event_menubtn2(lv_event_t * e);
extern lv_obj_t * ui_menubtn2;
extern lv_obj_t * ui_menulp3;
void ui_event_menubtn3(lv_event_t * e);
extern lv_obj_t * ui_menubtn3;
extern lv_obj_t * ui_menulp4;
void ui_event_menubtn4(lv_event_t * e);
extern lv_obj_t * ui_menubtn4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_mimgp;
extern lv_obj_t * ui_lcontrolp;
// SCREEN: ui_Page_Set
void ui_Page_Set_screen_init(void);
void ui_event_Page_Set(lv_event_t * e);
extern lv_obj_t * ui_Page_Set;
extern lv_obj_t * ui_Set_panel;
void ui_event_setback(lv_event_t * e);
extern lv_obj_t * ui_setback;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_setbackt;
void ui_event_setdown(lv_event_t * e);
extern lv_obj_t * ui_setdown;
extern lv_obj_t * ui_setdownt;
void ui_event_setapp(lv_event_t * e);
extern lv_obj_t * ui_setapp;
extern lv_obj_t * ui_setappt;
void ui_event_setwifi(lv_event_t * e);
extern lv_obj_t * ui_setwifi;
extern lv_obj_t * ui_setwifit;
void ui_event_setble(lv_event_t * e);
extern lv_obj_t * ui_setble;
extern lv_obj_t * ui_setblet;
extern lv_obj_t * ui_setblesw;
void ui_event_setvol(lv_event_t * e);
extern lv_obj_t * ui_setvol;
extern lv_obj_t * ui_setvolt;
void ui_event_setbri(lv_event_t * e);
extern lv_obj_t * ui_setbri;
extern lv_obj_t * ui_setbrit;
void ui_event_settime(lv_event_t * e);
extern lv_obj_t * ui_settime;
extern lv_obj_t * ui_settimt;
void ui_event_setrgb(lv_event_t * e);
extern lv_obj_t * ui_setrgb;
extern lv_obj_t * ui_setrgbt;
extern lv_obj_t * ui_setrgbsw;
void ui_event_setww(lv_event_t * e);
extern lv_obj_t * ui_setww;
extern lv_obj_t * ui_setwwt;
extern lv_obj_t * ui_setwwsw;
void ui_event_setdev(lv_event_t * e);
extern lv_obj_t * ui_setdev;
extern lv_obj_t * ui_setdevt;
void ui_event_setfac(lv_event_t * e);
extern lv_obj_t * ui_setfac;
extern lv_obj_t * ui_setfact;
extern lv_obj_t * ui_settextp;
extern lv_obj_t * ui_Set_title;
extern lv_obj_t * ui_scontrolp;
// SCREEN: ui_Page_Slider
void ui_Page_Slider_screen_init(void);
extern lv_obj_t * ui_Page_Slider;
extern lv_obj_t * ui_bvpb;
extern lv_obj_t * ui_bvbimg;
extern lv_obj_t * ui_bvbt;
extern lv_obj_t * ui_bvbv;
extern lv_obj_t * ui_bvs;
extern lv_obj_t * ui_bvtp;
extern lv_obj_t * ui_bvtitle;
void ui_event_bvback(lv_event_t * e);
extern lv_obj_t * ui_bvback;
extern lv_obj_t * ui_vp;
void ui_event_vslider(lv_event_t * e);
extern lv_obj_t * ui_vslider;
extern lv_obj_t * ui_bp;
void ui_event_bslider(lv_event_t * e);
extern lv_obj_t * ui_bslider;
// SCREEN: ui_Page_About
void ui_Page_About_screen_init(void);
extern lv_obj_t * ui_Page_About;
extern lv_obj_t * ui_AboutP;
void ui_event_aboutdevname(lv_event_t * e);
extern lv_obj_t * ui_aboutdevname;
extern lv_obj_t * ui_devnamet1;
extern lv_obj_t * ui_devnamet2;
void ui_event_aboutespversion(lv_event_t * e);
extern lv_obj_t * ui_aboutespversion;
extern lv_obj_t * ui_espversiont1;
extern lv_obj_t * ui_espversiont2;
void ui_event_aboutaiversion(lv_event_t * e);
extern lv_obj_t * ui_aboutaiversion;
extern lv_obj_t * ui_aiversion1;
extern lv_obj_t * ui_aiversion2;
void ui_event_aboutsn(lv_event_t * e);
extern lv_obj_t * ui_aboutsn;
extern lv_obj_t * ui_snt1;
extern lv_obj_t * ui_snt2;
void ui_event_abouteui(lv_event_t * e);
extern lv_obj_t * ui_abouteui;
extern lv_obj_t * ui_euit1;
extern lv_obj_t * ui_euit2;
void ui_event_aboutblemac(lv_event_t * e);
extern lv_obj_t * ui_aboutblemac;
extern lv_obj_t * ui_blet1;
extern lv_obj_t * ui_blet2;
void ui_event_aboutwifimac(lv_event_t * e);
extern lv_obj_t * ui_aboutwifimac;
extern lv_obj_t * ui_wifit1;
extern lv_obj_t * ui_wifit2;
void ui_event_Paboutb(lv_event_t * e);
extern lv_obj_t * ui_Paboutb;
extern lv_obj_t * ui_abtp;
extern lv_obj_t * ui_abtitle;
// SCREEN: ui_Page_Swipe
void ui_Page_Swipe_screen_init(void);
extern lv_obj_t * ui_Page_Swipe;
void ui_event_spsilder(lv_event_t * e);
extern lv_obj_t * ui_spsilder;
void ui_event_spback(lv_event_t * e);
extern lv_obj_t * ui_spback;
extern lv_obj_t * ui_sptext;
extern lv_obj_t * ui_swipep;
extern lv_obj_t * ui_sptitle;
extern lv_obj_t * ui_swipep2;
extern lv_obj_t * ui_sptext2;
extern lv_obj_t * ui_Spinner4;
// SCREEN: ui_Page_Extension
void ui_Page_Extension_screen_init(void);
extern lv_obj_t * ui_Page_Extension;
extern lv_obj_t * ui_extensionbubble1;
extern lv_obj_t * ui_extensionbubble1Value;
extern lv_obj_t * ui_extensionbubble1Unit;
extern lv_obj_t * ui_extensionbubble1Icon;
extern lv_obj_t * ui_extensionbubble1Icon2;
void ui_event_extensionbubble2(lv_event_t * e);
extern lv_obj_t * ui_extensionbubble2;
extern lv_obj_t * ui_extensionbubble2Value;
extern lv_obj_t * ui_extensionbubble2Unit;
extern lv_obj_t * ui_extensionbubble2Icon;
extern lv_obj_t * ui_extensionbubble2Icon2;
void ui_event_extensionbubble3(lv_event_t * e);
extern lv_obj_t * ui_extensionbubble3;
extern lv_obj_t * ui_extensionbubble3Value;
extern lv_obj_t * ui_extensionbubble3Unit;
extern lv_obj_t * ui_extensionbubble3Icon;
extern lv_obj_t * ui_extensionbubble3Icon2;
void ui_event_extensionbubble4(lv_event_t * e);
extern lv_obj_t * ui_extensionbubble4;
extern lv_obj_t * ui_extensionbubble4Value;
extern lv_obj_t * ui_extensionbubble4Unit;
extern lv_obj_t * ui_extensionbubble4Icon;
extern lv_obj_t * ui_extensionbubble4Icon2;
void ui_event_extensionpanel(lv_event_t * e);
extern lv_obj_t * ui_extensionpanel;
extern lv_obj_t * ui_extensionNone;
extern lv_obj_t * ui_extenNonetext;
extern lv_obj_t * ui_extenNonetext2;
void ui_event_extenNoneback(lv_event_t * e);
extern lv_obj_t * ui_extenNoneback;
// SCREEN: ui_Page_OTA
void ui_Page_OTA_screen_init(void);
extern lv_obj_t * ui_Page_OTA;
extern lv_obj_t * ui_otapanel;
extern lv_obj_t * ui_otatext;
extern lv_obj_t * ui_otastatus;
extern lv_obj_t * ui_otaspinner;
extern lv_obj_t * ui_otaicon;
extern lv_obj_t * ui_otaarc;
void ui_event_otaback(lv_event_t * e);
extern lv_obj_t * ui_otaback;
// SCREEN: ui_Page_Sleep
void ui_Page_Sleep_screen_init(void);
extern lv_obj_t * ui_Page_Sleep;
void ui_event_sleeptimeroller(lv_event_t * e);
extern lv_obj_t * ui_sleeptimeroller;
void ui_event_slpback(lv_event_t * e);
extern lv_obj_t * ui_slpback;
void ui_event_sleepswitchp(lv_event_t * e);
extern lv_obj_t * ui_sleepswitchp;
extern lv_obj_t * ui_sleepswitcht;
void ui_event_sleepswitch(lv_event_t * e);
extern lv_obj_t * ui_sleepswitch;
// SCREEN: ui_Page_Push2talk
void ui_Page_Push2talk_screen_init(void);
void ui_event_Page_Push2talk(lv_event_t * e);
extern lv_obj_t * ui_Page_Push2talk;
extern lv_obj_t * ui_push2talkpanel2;
void ui_event_push2talkarc(lv_event_t * e);
extern lv_obj_t * ui_push2talkarc;
extern lv_obj_t * ui_push2talkp2t1;
extern lv_obj_t * ui_push2talkp2t2;
extern lv_obj_t * ui_push2talkknob;
extern lv_obj_t * ui_push2talkpanel3;
void ui_event_p2tobj(lv_event_t * e);
extern lv_obj_t * ui_p2tobj;
extern lv_obj_t * ui_p2tobj1;
extern lv_obj_t * ui_p2tobj2;
void ui_event_p2tcomparison(lv_event_t * e);
extern lv_obj_t * ui_p2tcomparison;
extern lv_obj_t * ui_p2tcomparison1;
extern lv_obj_t * ui_p2tcomparison2;
void ui_event_p2tbehavior(lv_event_t * e);
extern lv_obj_t * ui_p2tbehavior;
extern lv_obj_t * ui_p2tbehavior1;
extern lv_obj_t * ui_p2tbehavior2;
void ui_event_p2tfeat(lv_event_t * e);
extern lv_obj_t * ui_p2tfeat;
extern lv_obj_t * ui_p2tfeat1;
extern lv_obj_t * ui_p2tfeat2;
void ui_event_p2tnotify(lv_event_t * e);
extern lv_obj_t * ui_p2tnotify;
extern lv_obj_t * ui_p2tnotify1;
extern lv_obj_t * ui_p2tnotify2;
void ui_event_p2ttime(lv_event_t * e);
extern lv_obj_t * ui_p2ttime;
extern lv_obj_t * ui_p2ttime1;
extern lv_obj_t * ui_p2ttime2;
void ui_event_p2tfreq(lv_event_t * e);
extern lv_obj_t * ui_p2tfreq;
extern lv_obj_t * ui_p2tfreq1;
extern lv_obj_t * ui_p2tfreq2;
void ui_event_p2tcancel(lv_event_t * e);
extern lv_obj_t * ui_p2tcancel;
void ui_event_p2tcheck(lv_event_t * e);
extern lv_obj_t * ui_p2tcheck;
extern lv_obj_t * ui_p2texit;
// SCREEN: ui_Page_Guideavatar
void ui_Page_Guideavatar_screen_init(void);
void ui_event_Page_Guideavatar(lv_event_t * e);
extern lv_obj_t * ui_Page_Guideavatar;
void ui_event_guide1p1(lv_event_t * e);
extern lv_obj_t * ui_guide1p1;
extern lv_obj_t * ui_guide1img1;
extern lv_obj_t * ui_guide1t1;
void ui_event_guide1p2(lv_event_t * e);
extern lv_obj_t * ui_guide1p2;
extern lv_obj_t * ui_guide1img2;
extern lv_obj_t * ui_guide1t2;
void ui_event_guide1p3(lv_event_t * e);
extern lv_obj_t * ui_guide1p3;
void ui_event_guide1btn1(lv_event_t * e);
extern lv_obj_t * ui_guide1btn1;
extern lv_obj_t * ui_guide1btn1t;
void ui_event_guide1btn2(lv_event_t * e);
extern lv_obj_t * ui_guide1btn2;
extern lv_obj_t * ui_guide1btn2t;
void ui_event_guide1btn3(lv_event_t * e);
extern lv_obj_t * ui_guide1btn3;
// SCREEN: ui_Page_Guidelive
void ui_Page_Guidelive_screen_init(void);
void ui_event_Page_Guidelive(lv_event_t * e);
extern lv_obj_t * ui_Page_Guidelive;
void ui_event_guide2p1(lv_event_t * e);
extern lv_obj_t * ui_guide2p1;
extern lv_obj_t * ui_guide2t1;
void ui_event_guide2p2(lv_event_t * e);
extern lv_obj_t * ui_guide2p2;
extern lv_obj_t * ui_guide2img2;
extern lv_obj_t * ui_guide2t2;
// SCREEN: ui_Page_Flag
void ui_Page_Flag_screen_init(void);
void ui_event_Page_Flag(lv_event_t * e);
extern lv_obj_t * ui_Page_Flag;
extern lv_obj_t * ui_guideflagp;
void ui_event_guidebtn1(lv_event_t * e);
extern lv_obj_t * ui_guidebtn1;
extern lv_obj_t * ui_guidebtn1t;
void ui_event_guidebtn2(lv_event_t * e);
extern lv_obj_t * ui_guidebtn2;
extern lv_obj_t * ui_guidebtn2t;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_battery_warn_png);    // assets/battery_warn.png
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_start_smile_png);    // assets/start_smile.png
LV_IMG_DECLARE(ui_img_page_main_png);    // assets/page_main.png
LV_IMG_DECLARE(ui_img_task_template_png);    // assets/Task Template.png
LV_IMG_DECLARE(ui_img_1415499115);    // assets/Task Template-.png
LV_IMG_DECLARE(ui_img_currenttask_png);    // assets/currenttask.png
LV_IMG_DECLARE(ui_img_1158392298);    // assets/currenttask-.png
LV_IMG_DECLARE(ui_img_extension_png);    // assets/extension.png
LV_IMG_DECLARE(ui_img_1722191473);    // assets/extension-2.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_setting_f_png);    // assets/setting_f.png
LV_IMG_DECLARE(ui_img_no_wifi_png);    // assets/no_wifi.png
LV_IMG_DECLARE(ui_img_battery_frame_png);    // assets/battery frame.png
LV_IMG_DECLARE(ui_img_ble_png);    // assets/ble.png
LV_IMG_DECLARE(ui_img_button_cancel_png);    // assets/button_cancel.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // assets/wifi_3.png
LV_IMG_DECLARE(ui_img_setback_png);    // assets/setback.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/Back.png
LV_IMG_DECLARE(ui_img_1195720223);    // assets/Back-2.png
LV_IMG_DECLARE(ui_img_human_png);    // assets/human.png
LV_IMG_DECLARE(ui_img_631814683);    // assets/human-2.png
LV_IMG_DECLARE(ui_img_578579305);    // assets/pet-2.png
LV_IMG_DECLARE(ui_img_pet_png);    // assets/pet.png
LV_IMG_DECLARE(ui_img_gesture_png);    // assets/gesture.png
LV_IMG_DECLARE(ui_img_30219097);    // assets/gesture-2.png
LV_IMG_DECLARE(ui_img_human_d_png);    // assets/human_d.png
LV_IMG_DECLARE(ui_img_volicon_png);    // assets/volicon.png
LV_IMG_DECLARE(ui_img_swipe_png);    // assets/swipe.png
LV_IMG_DECLARE(ui_img_1222852621);    // assets/background1@1x.png
LV_IMG_DECLARE(ui_img_226867343);    // assets/co2_f@1x.png
LV_IMG_DECLARE(ui_img_1955521171);    // assets/humidity@1x.png
LV_IMG_DECLARE(ui_img_529164268);    // assets/co2@1x.png
LV_IMG_DECLARE(ui_img_1761657674);    // assets/temp@1x.png
LV_IMG_DECLARE(ui_img_wifiok_png);    // assets/wifiok.png
LV_IMG_DECLARE(ui_img_pushtotalk_scroll_png);    // assets/pushToTalk_Scroll.png
LV_IMG_DECLARE(ui_img_guideimg_png);    // assets/guideimg.png
LV_IMG_DECLARE(ui_img_scroll_down_png);    // assets/scroll_down.png
LV_IMG_DECLARE(ui_img_fakelivecam_png);    // assets/fakelivecam.png
LV_IMG_DECLARE(ui_img_scroll_up_png);    // assets/scroll_up.png
LV_IMG_DECLARE(ui_img_backtomenu_png);    // assets/backtomenu.png
LV_IMG_DECLARE(ui_img_battery_charging_png);    // assets/battery charging.png
LV_IMG_DECLARE(ui_img_brighticon_png);    // assets/brighticon.png
LV_IMG_DECLARE(ui_img_dog_d_png);    // assets/dog_d.png
LV_IMG_DECLARE(ui_img_error_png);    // assets/error.png
LV_IMG_DECLARE(ui_img_gesture_d_png);    // assets/gesture_d.png
LV_IMG_DECLARE(ui_img_gradient_png);    // assets/gradient.png
LV_IMG_DECLARE(ui_img_1336611536);    // assets/humidity_f@1x.png
LV_IMG_DECLARE(ui_img_left_png);    // assets/left.png
LV_IMG_DECLARE(ui_img_onboardclick_png);    // assets/onboardClick.png
LV_IMG_DECLARE(ui_img_pushtotalk_error_png);    // assets/pushToTalk_Error.png
LV_IMG_DECLARE(ui_img_speaking1_png);    // assets/speaking1.png
LV_IMG_DECLARE(ui_img_speaking2_png);    // assets/speaking2.png
LV_IMG_DECLARE(ui_img_2057255035);    // assets/temp_f@1x.png
LV_IMG_DECLARE(ui_img_wifi_0_png);    // assets/wifi_0.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets/wifi_1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // assets/wifi_2.png
LV_IMG_DECLARE(ui_img_wifi_abnormal_png);    // assets/wifi_abnormal.png



LV_FONT_DECLARE(ui_font_fbold24);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_fontbold26);
LV_FONT_DECLARE(ui_font_font_bold);
LV_FONT_DECLARE(ui_font_semibold16);
LV_FONT_DECLARE(ui_font_semibold16extend);
LV_FONT_DECLARE(ui_font_semibold28);
LV_FONT_DECLARE(ui_font_semibold34extend);
LV_FONT_DECLARE(ui_font_semibold42);
LV_FONT_DECLARE(ui_font_semibold64);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
