// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Connect_screen_init(void)
{
    ui_Page_Connect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_arcl = lv_arc_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_arcl, 410);
    lv_obj_set_height(ui_conn_arcl, 410);
    lv_obj_set_align(ui_conn_arcl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_arcl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_conn_arcl, 100);
    lv_arc_set_bg_angles(ui_conn_arcl, 95, 265);
    lv_obj_set_style_arc_color(ui_conn_arcl, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcl, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcl, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_conn_arcl, lv_color_hex(0xA9DE2C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcl, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcl, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_conn_arcl, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_arcl, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_conn_arcl, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_conn_arcl, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_conn_arcr = lv_arc_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_arcr, 410);
    lv_obj_set_height(ui_conn_arcr, 410);
    lv_obj_set_align(ui_conn_arcr, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_arcr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_conn_arcr, 100);
    lv_arc_set_bg_angles(ui_conn_arcr, 95, 265);
    lv_arc_set_rotation(ui_conn_arcr, 180);
    lv_obj_set_style_arc_color(ui_conn_arcr, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcr, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcr, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_conn_arcr, lv_color_hex(0xA9DE2C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_conn_arcr, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_conn_arcr, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_conn_arcr, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_arcr, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_conn_panel1 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel1, 212);
    lv_obj_set_height(ui_conn_panel1, 131);
    lv_obj_set_x(ui_conn_panel1, 0);
    lv_obj_set_y(ui_conn_panel1, -101);
    lv_obj_set_align(ui_conn_panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp11 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp11, -30);
    lv_obj_set_y(ui_connp11, 0);
    lv_obj_set_align(ui_connp11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp11, "Mate");
    lv_obj_set_style_text_color(ui_connp11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp11, &ui_font_fbold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp12 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp12, 108);
    lv_obj_set_y(ui_connp12, 0);
    lv_obj_set_align(ui_connp12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_connp12, "(   / 2)");
    lv_obj_set_style_text_color(ui_connp12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp13 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp13, 0);
    lv_obj_set_y(ui_connp13, -39);
    lv_obj_set_align(ui_connp13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp13, "Download\nSenseCraft");
    lv_obj_set_style_text_color(ui_connp13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp13, &ui_font_fbold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp14 = lv_label_create(ui_conn_panel1);
    lv_obj_set_width(ui_connp14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp14, 35);
    lv_obj_set_y(ui_connp14, 0);
    lv_obj_set_align(ui_connp14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp14, "1");
    lv_obj_set_style_text_color(ui_connp14, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp14, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_panel2 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_panel2, 189);
    lv_obj_set_height(ui_conn_panel2, 82);
    lv_obj_set_x(ui_conn_panel2, -6);
    lv_obj_set_y(ui_conn_panel2, -101);
    lv_obj_set_align(ui_conn_panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_conn_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conn_panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conn_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conn_panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conn_panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp21 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp21, -17);
    lv_obj_set_y(ui_connp21, 0);
    lv_obj_set_align(ui_connp21, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_connp21, "Bluetooth");
    lv_obj_set_style_text_color(ui_connp21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp21, &ui_font_fbold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp22 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp22, 111);
    lv_obj_set_y(ui_connp22, 0);
    lv_obj_set_align(ui_connp22, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_connp22, "(    / 2)");
    lv_obj_set_style_text_color(ui_connp22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp22, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp23 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp23, 0);
    lv_obj_set_y(ui_connp23, -30);
    lv_obj_set_align(ui_connp23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp23, "Connect");
    lv_obj_set_style_text_color(ui_connp23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp23, &ui_font_fbold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp24 = lv_label_create(ui_conn_panel2);
    lv_obj_set_width(ui_connp24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connp24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connp24, 50);
    lv_obj_set_y(ui_connp24, 0);
    lv_obj_set_align(ui_connp24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connp24, "2");
    lv_obj_set_style_text_color(ui_connp24, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connp24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connp24, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conn_QR = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_conn_QR, 160);
    lv_obj_set_height(ui_conn_QR, 160);
    lv_obj_set_align(ui_conn_QR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_conn_QR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_conncancel = lv_btn_create(ui_Page_Connect);
    lv_obj_set_width(ui_conncancel, 60);
    lv_obj_set_height(ui_conncancel, 60);
    lv_obj_set_x(ui_conncancel, 0);
    lv_obj_set_y(ui_conncancel, 125);
    lv_obj_set_align(ui_conncancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conncancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_conncancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_conncancel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_conncancel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conncancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_conncancel, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_conncancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_conncancel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connp1 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_connp1, 90);
    lv_obj_set_height(ui_connp1, 125);
    lv_obj_set_x(ui_connp1, 130);
    lv_obj_set_y(ui_connp1, 0);
    lv_obj_set_align(ui_connp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_connp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_connp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arrow1 = lv_img_create(ui_connp1);
    lv_img_set_src(ui_arrow1, &ui_img_arrow_png);
    lv_obj_set_width(ui_arrow1, 50);
    lv_obj_set_height(ui_arrow1, 50);
    lv_obj_set_align(ui_arrow1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arrow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_connp2 = lv_obj_create(ui_Page_Connect);
    lv_obj_set_width(ui_connp2, 90);
    lv_obj_set_height(ui_connp2, 125);
    lv_obj_set_x(ui_connp2, -130);
    lv_obj_set_y(ui_connp2, 0);
    lv_obj_set_align(ui_connp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_connp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_connp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arrow2 = lv_img_create(ui_connp2);
    lv_img_set_src(ui_arrow2, &ui_img_arrow_png);
    lv_obj_set_width(ui_arrow2, 50);
    lv_obj_set_height(ui_arrow2, 50);
    lv_obj_set_x(ui_arrow2, 1);
    lv_obj_set_y(ui_arrow2, 2);
    lv_obj_set_align(ui_arrow2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arrow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_arrow2, 1800);

    lv_obj_add_event_cb(ui_conncancel, ui_event_conncancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arrow1, ui_event_arrow1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connp1, ui_event_connp1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arrow2, ui_event_arrow2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connp2, ui_event_connp2, LV_EVENT_ALL, NULL);

}
