// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Extension_screen_init(void)
{
    ui_Page_Extension = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Extension, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Extension, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Extension, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble1 = lv_obj_create(ui_Page_Extension);
    lv_obj_set_width(ui_extensionbubble1, 215);
    lv_obj_set_height(ui_extensionbubble1, 215);
    lv_obj_set_x(ui_extensionbubble1, 67);
    lv_obj_set_y(ui_extensionbubble1, 0);
    lv_obj_set_align(ui_extensionbubble1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_extensionbubble1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_extensionbubble1, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_extensionbubble1, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_extensionbubble1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_extensionbubble1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_extensionbubble1, &ui_img_1222852621, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_extensionbubble1, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_extensionbubble1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble1Value = lv_label_create(ui_extensionbubble1);
    lv_obj_set_width(ui_extensionbubble1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble1Value, "--");
    lv_obj_set_style_text_color(ui_extensionbubble1Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble1Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble1Value, &ui_font_semibold64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble1Unit = lv_label_create(ui_extensionbubble1);
    lv_obj_set_width(ui_extensionbubble1Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble1Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble1Unit, 0);
    lv_obj_set_y(ui_extensionbubble1Unit, 68);
    lv_obj_set_align(ui_extensionbubble1Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble1Unit, "°C");
    lv_obj_set_style_text_color(ui_extensionbubble1Unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble1Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble1Unit, &ui_font_semibold34extend, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble1Icon = lv_img_create(ui_extensionbubble1);
    lv_img_set_src(ui_extensionbubble1Icon, &ui_img_226867343);
    lv_obj_set_width(ui_extensionbubble1Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble1Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble1Icon, 0);
    lv_obj_set_y(ui_extensionbubble1Icon, -72);
    lv_obj_set_align(ui_extensionbubble1Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble1Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble1Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_extensionbubble1Icon2 = lv_img_create(ui_extensionbubble1);
    lv_img_set_src(ui_extensionbubble1Icon2, &ui_img_setback_png);
    lv_obj_set_width(ui_extensionbubble1Icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble1Icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble1Icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble1Icon2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble1Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_extensionbubble1Icon2, 500);

    ui_extensionbubble2 = lv_obj_create(ui_Page_Extension);
    lv_obj_set_width(ui_extensionbubble2, 106);
    lv_obj_set_height(ui_extensionbubble2, 106);
    lv_obj_set_x(ui_extensionbubble2, -79);
    lv_obj_set_y(ui_extensionbubble2, -117);
    lv_obj_set_align(ui_extensionbubble2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_extensionbubble2, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_extensionbubble2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_extensionbubble2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_extensionbubble2, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_extensionbubble2, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble2Value = lv_label_create(ui_extensionbubble2);
    lv_obj_set_width(ui_extensionbubble2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble2Value, "--");
    lv_obj_set_style_text_color(ui_extensionbubble2Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble2Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble2Value, &ui_font_semibold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble2Unit = lv_label_create(ui_extensionbubble2);
    lv_obj_set_width(ui_extensionbubble2Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble2Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble2Unit, 0);
    lv_obj_set_y(ui_extensionbubble2Unit, 31);
    lv_obj_set_align(ui_extensionbubble2Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble2Unit, "%");
    lv_obj_set_style_text_color(ui_extensionbubble2Unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble2Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble2Unit, &ui_font_semibold16extend, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble2Icon = lv_img_create(ui_extensionbubble2);
    lv_img_set_src(ui_extensionbubble2Icon, &ui_img_1955521171);
    lv_obj_set_width(ui_extensionbubble2Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble2Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble2Icon, 0);
    lv_obj_set_y(ui_extensionbubble2Icon, -32);
    lv_obj_set_align(ui_extensionbubble2Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble2Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble2Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_extensionbubble2Icon2 = lv_img_create(ui_extensionbubble2);
    lv_img_set_src(ui_extensionbubble2Icon2, &ui_img_setback_png);
    lv_obj_set_width(ui_extensionbubble2Icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble2Icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble2Icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble2Icon2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble2Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_extensionbubble3 = lv_obj_create(ui_Page_Extension);
    lv_obj_set_width(ui_extensionbubble3, 106);
    lv_obj_set_height(ui_extensionbubble3, 106);
    lv_obj_set_x(ui_extensionbubble3, -132);
    lv_obj_set_y(ui_extensionbubble3, 0);
    lv_obj_set_align(ui_extensionbubble3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_extensionbubble3, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_extensionbubble3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_extensionbubble3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_extensionbubble3, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_extensionbubble3, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble3Value = lv_label_create(ui_extensionbubble3);
    lv_obj_set_width(ui_extensionbubble3Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble3Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble3Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble3Value, "--");
    lv_obj_set_style_text_color(ui_extensionbubble3Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble3Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble3Value, &ui_font_semibold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble3Unit = lv_label_create(ui_extensionbubble3);
    lv_obj_set_width(ui_extensionbubble3Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble3Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble3Unit, 0);
    lv_obj_set_y(ui_extensionbubble3Unit, 31);
    lv_obj_set_align(ui_extensionbubble3Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble3Unit, "ppm");
    lv_obj_set_style_text_color(ui_extensionbubble3Unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble3Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble3Unit, &ui_font_semibold16extend, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble3Icon = lv_img_create(ui_extensionbubble3);
    lv_img_set_src(ui_extensionbubble3Icon, &ui_img_529164268);
    lv_obj_set_width(ui_extensionbubble3Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble3Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble3Icon, 0);
    lv_obj_set_y(ui_extensionbubble3Icon, -32);
    lv_obj_set_align(ui_extensionbubble3Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble3Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble3Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_extensionbubble3Icon2 = lv_img_create(ui_extensionbubble3);
    lv_img_set_src(ui_extensionbubble3Icon2, &ui_img_setback_png);
    lv_obj_set_width(ui_extensionbubble3Icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble3Icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble3Icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble3Icon2,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble3Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_extensionbubble4 = lv_obj_create(ui_Page_Extension);
    lv_obj_set_width(ui_extensionbubble4, 106);
    lv_obj_set_height(ui_extensionbubble4, 106);
    lv_obj_set_x(ui_extensionbubble4, -79);
    lv_obj_set_y(ui_extensionbubble4, 117);
    lv_obj_set_align(ui_extensionbubble4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_extensionbubble4, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_extensionbubble4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_extensionbubble4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_extensionbubble4, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_extensionbubble4, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble4Value = lv_label_create(ui_extensionbubble4);
    lv_obj_set_width(ui_extensionbubble4Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble4Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble4Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble4Value, "--");
    lv_obj_set_style_text_color(ui_extensionbubble4Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble4Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble4Value, &ui_font_semibold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble4Unit = lv_label_create(ui_extensionbubble4);
    lv_obj_set_width(ui_extensionbubble4Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble4Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble4Unit, 0);
    lv_obj_set_y(ui_extensionbubble4Unit, 33);
    lv_obj_set_align(ui_extensionbubble4Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extensionbubble4Unit, "°C");
    lv_obj_set_style_text_color(ui_extensionbubble4Unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extensionbubble4Unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extensionbubble4Unit, &ui_font_semibold16extend, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionbubble4Icon = lv_img_create(ui_extensionbubble4);
    lv_img_set_src(ui_extensionbubble4Icon, &ui_img_1761657674);
    lv_obj_set_width(ui_extensionbubble4Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble4Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extensionbubble4Icon, 0);
    lv_obj_set_y(ui_extensionbubble4Icon, -32);
    lv_obj_set_align(ui_extensionbubble4Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble4Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble4Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_extensionbubble4Icon2 = lv_img_create(ui_extensionbubble4);
    lv_img_set_src(ui_extensionbubble4Icon2, &ui_img_setback_png);
    lv_obj_set_width(ui_extensionbubble4Icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extensionbubble4Icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_extensionbubble4Icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionbubble4Icon2,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_extensionbubble4Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_extensionpanel = lv_obj_create(ui_Page_Extension);
    lv_obj_set_width(ui_extensionpanel, 412);
    lv_obj_set_height(ui_extensionpanel, 412);
    lv_obj_set_align(ui_extensionpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_extensionpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_extensionpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_extensionpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_extensionpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_extensionpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extensionNone = lv_obj_create(ui_Page_Extension);
    lv_obj_set_width(ui_extensionNone, 412);
    lv_obj_set_height(ui_extensionNone, 412);
    lv_obj_set_align(ui_extensionNone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_extensionNone, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_extensionNone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_extensionNone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_extensionNone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_extensionNone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_extensionNone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extenNonetext = lv_label_create(ui_extensionNone);
    lv_obj_set_width(ui_extenNonetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_extenNonetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_extenNonetext, 0);
    lv_obj_set_y(ui_extenNonetext, -80);
    lv_obj_set_align(ui_extenNonetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extenNonetext, "None");
    lv_obj_set_style_text_color(ui_extenNonetext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extenNonetext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extenNonetext, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extenNonetext2 = lv_label_create(ui_extensionNone);
    lv_obj_set_width(ui_extenNonetext2, 280);
    lv_obj_set_height(ui_extenNonetext2, 66);
    lv_obj_set_align(ui_extenNonetext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_extenNonetext2, "You can use Grove scd4x and sht4x here for displaying the entension value");
    lv_obj_set_style_text_color(ui_extenNonetext2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_extenNonetext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_extenNonetext2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_extenNonetext2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_extenNoneback = lv_btn_create(ui_extensionNone);
    lv_obj_set_width(ui_extenNoneback, 90);
    lv_obj_set_height(ui_extenNoneback, 90);
    lv_obj_set_x(ui_extenNoneback, 0);
    lv_obj_set_y(ui_extenNoneback, 120);
    lv_obj_set_align(ui_extenNoneback, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_extenNoneback, 59, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_extenNoneback, lv_color_hex(0x202124), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_extenNoneback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_extenNoneback, &ui_img_setback_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_extenNoneback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_extenNoneback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_extensionbubble2, ui_event_extensionbubble2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_extensionbubble3, ui_event_extensionbubble3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_extensionbubble4, ui_event_extensionbubble4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_extensionpanel, ui_event_extensionpanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_extenNoneback, ui_event_extenNoneback, LV_EVENT_ALL, NULL);

}
