// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Example_screen_init(void)
{
    ui_Page_Example = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Example, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Example, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Example, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menulist = lv_obj_create(ui_Page_Example);
    lv_obj_set_width(ui_menulist, 400);
    lv_obj_set_height(ui_menulist, 165);
    lv_obj_set_x(ui_menulist, 0);
    lv_obj_set_y(ui_menulist, 6);
    lv_obj_set_align(ui_menulist, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_menulist, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menulist, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_menulist, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_menulist, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_menulist, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_menulist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_menulist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_menulist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_custp1 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_custp1, 90);
    lv_obj_set_height(ui_custp1, 90);
    lv_obj_set_align(ui_custp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_custp1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_custp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_custp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_custp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_custbtn1 = lv_btn_create(ui_custp1);
    lv_obj_set_width(ui_custbtn1, 80);
    lv_obj_set_height(ui_custbtn1, 80);
    lv_obj_set_align(ui_custbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_custbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_custbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_custbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_custbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_custbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_custbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_custp2 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_custp2, 90);
    lv_obj_set_height(ui_custp2, 90);
    lv_obj_set_align(ui_custp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_custp2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_custp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_custp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_custp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_custbtn2 = lv_btn_create(ui_custp2);
    lv_obj_set_width(ui_custbtn2, 80);
    lv_obj_set_height(ui_custbtn2, 80);
    lv_obj_set_align(ui_custbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_custbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_custbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_custbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_custbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_custbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_custbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_custp3 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_custp3, 90);
    lv_obj_set_height(ui_custp3, 90);
    lv_obj_set_align(ui_custp3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_custp3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_custp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_custp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_custp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_custbtn3 = lv_btn_create(ui_custp3);
    lv_obj_set_width(ui_custbtn3, 80);
    lv_obj_set_height(ui_custbtn3, 80);
    lv_obj_set_align(ui_custbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_custbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_custbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custbtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_custbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_custbtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_custbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_custbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menulp1 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp1, 90);
    lv_obj_set_height(ui_menulp1, 90);
    lv_obj_set_align(ui_menulp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn1 = lv_btn_create(ui_menulp1);
    lv_obj_set_width(ui_menubtn1, 80);
    lv_obj_set_height(ui_menubtn1, 80);
    lv_obj_set_align(ui_menubtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn1, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menubtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_menubtn1, &ui_img_1195720223, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_menubtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menubtn1, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menulp2 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp2, 90);
    lv_obj_set_height(ui_menulp2, 90);
    lv_obj_set_align(ui_menulp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn2 = lv_btn_create(ui_menulp2);
    lv_obj_set_width(ui_menubtn2, 80);
    lv_obj_set_height(ui_menubtn2, 80);
    lv_obj_set_align(ui_menubtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn2, &ui_img_human_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn2, &ui_img_631814683, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menubtn2, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menulp3 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp3, 90);
    lv_obj_set_height(ui_menulp3, 90);
    lv_obj_set_align(ui_menulp3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn3 = lv_btn_create(ui_menulp3);
    lv_obj_set_width(ui_menubtn3, 80);
    lv_obj_set_height(ui_menubtn3, 80);
    lv_obj_set_align(ui_menubtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn3, &ui_img_578579305, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menubtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_menubtn3, &ui_img_pet_png, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_menubtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menubtn3, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_menulp4 = lv_obj_create(ui_menulist);
    lv_obj_set_width(ui_menulp4, 90);
    lv_obj_set_height(ui_menulp4, 90);
    lv_obj_set_align(ui_menulp4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menulp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menulp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menulp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menulp4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menulp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menubtn4 = lv_btn_create(ui_menulp4);
    lv_obj_set_width(ui_menubtn4, 80);
    lv_obj_set_height(ui_menubtn4, 80);
    lv_obj_set_align(ui_menubtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menubtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menubtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menubtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn4, &ui_img_gesture_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menubtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menubtn4, &ui_img_30219097, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_menubtn4, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label1 = lv_label_create(ui_Page_Example);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 2);
    lv_obj_set_y(ui_Label1, -132);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Human\nDetection");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mimgp = lv_obj_create(ui_Page_Example);
    lv_obj_set_width(ui_mimgp, 412);
    lv_obj_set_height(ui_mimgp, 412);
    lv_obj_set_align(ui_mimgp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mimgp, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_mimgp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mimgp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mimgp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_human_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mimgp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mimgp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lcontrolp = lv_obj_create(ui_Page_Example);
    lv_obj_set_width(ui_lcontrolp, 412);
    lv_obj_set_height(ui_lcontrolp, 412);
    lv_obj_set_align(ui_lcontrolp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lcontrolp, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_lcontrolp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lcontrolp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lcontrolp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lcontrolp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lcontrolp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_custbtn1, ui_event_custbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custbtn2, ui_event_custbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custbtn3, ui_event_custbtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menubtn1, ui_event_menubtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menubtn2, ui_event_menubtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menubtn3, ui_event_menubtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menubtn4, ui_event_menubtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_Example, ui_event_Page_Example, LV_EVENT_ALL, NULL);

}
