// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Startup_screen_init(void)
{
    ui_Page_Startup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Startup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Startup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startuplogo = lv_img_create(ui_Page_Startup);
    lv_img_set_src(ui_startuplogo, &ui_img_logo_png);
    lv_obj_set_width(ui_startuplogo, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_startuplogo, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_align(ui_startuplogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startuplogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_startuplogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Page_Startup, ui_event_Page_Startup, LV_EVENT_ALL, NULL);

}
