// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Avatar_screen_init(void)
{
    ui_Page_Avatar = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Avatar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Avatar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Avatar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_virp = lv_obj_create(ui_Page_Avatar);
    lv_obj_set_width(ui_virp, 416);
    lv_obj_set_height(ui_virp, 516);
    lv_obj_set_x(ui_virp, 0);
    lv_obj_set_y(ui_virp, -50);
    lv_obj_set_align(ui_virp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_virp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_virp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_virp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_virp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_virp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_virp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_virsmile = lv_img_create(ui_virp);
    lv_img_set_src(ui_virsmile, &ui_img_start_smile_png);
    lv_obj_set_width(ui_virsmile, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_virsmile, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_virsmile, 0);
    lv_obj_set_y(ui_virsmile, -50);
    lv_obj_set_align(ui_virsmile, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_virsmile, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_virsmile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_virbtn1 = lv_btn_create(ui_virp);
    lv_obj_set_width(ui_virbtn1, 300);
    lv_obj_set_height(ui_virbtn1, 60);
    lv_obj_set_x(ui_virbtn1, 0);
    lv_obj_set_y(ui_virbtn1, 60);
    lv_obj_set_align(ui_virbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_virbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_virbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_virbtn1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_virbtn1, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_virbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_virbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_virbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_virbtn1, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_virbtn1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_virbtn1, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_virbtn1, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_virtext1 = lv_label_create(ui_virbtn1);
    lv_obj_set_width(ui_virtext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_virtext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_virtext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_virtext1, "Connect to App");
    lv_obj_set_style_text_color(ui_virtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_virtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_virtext1, &ui_font_fontbold26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_virbtn2 = lv_btn_create(ui_virp);
    lv_obj_set_width(ui_virbtn2, 150);
    lv_obj_set_height(ui_virbtn2, 60);
    lv_obj_set_x(ui_virbtn2, 0);
    lv_obj_set_y(ui_virbtn2, 150);
    lv_obj_set_align(ui_virbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_virbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_virbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_virbtn2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_virbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_virbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_virbtn2, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_virbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_virbtn2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_virbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_virbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_virbtn2, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_virbtn2, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_virbtn2, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_virbtn2, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_virtext2 = lv_label_create(ui_virbtn2);
    lv_obj_set_width(ui_virtext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_virtext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_virtext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_virtext2, "Skip");
    lv_obj_set_style_text_color(ui_virtext2, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_virtext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_virtext2, &ui_font_fontbold26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_virbtn1, ui_event_virbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_virbtn2, ui_event_virbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_Avatar, ui_event_Page_Avatar, LV_EVENT_ALL, NULL);

}
