// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Flag_screen_init(void)
{
    ui_Page_Flag = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Flag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Flag, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Flag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_guideflagp = lv_obj_create(ui_Page_Flag);
    lv_obj_set_width(ui_guideflagp, 416);
    lv_obj_set_height(ui_guideflagp, 416);
    lv_obj_set_align(ui_guideflagp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_guideflagp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_guideflagp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_guideflagp, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_guideflagp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_guideflagp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_guidebtn1 = lv_btn_create(ui_guideflagp);
    lv_obj_set_width(ui_guidebtn1, 270);
    lv_obj_set_height(ui_guidebtn1, 80);
    lv_obj_set_x(ui_guidebtn1, 0);
    lv_obj_set_y(ui_guidebtn1, -58);
    lv_obj_set_align(ui_guidebtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_guidebtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_guidebtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_guidebtn1, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_guidebtn1, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_guidebtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_guidebtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_guidebtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_guidebtn1, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_guidebtn1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_guidebtn1, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_guidebtn1, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_guidebtn1t = lv_label_create(ui_guidebtn1);
    lv_obj_set_width(ui_guidebtn1t, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_guidebtn1t, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_guidebtn1t, LV_ALIGN_CENTER);
    lv_label_set_text(ui_guidebtn1t, "First Time?");
    lv_obj_set_style_text_color(ui_guidebtn1t, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_guidebtn1t, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_guidebtn1t, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_guidebtn2 = lv_btn_create(ui_guideflagp);
    lv_obj_set_width(ui_guidebtn2, 270);
    lv_obj_set_height(ui_guidebtn2, 80);
    lv_obj_set_x(ui_guidebtn2, 0);
    lv_obj_set_y(ui_guidebtn2, 50);
    lv_obj_set_align(ui_guidebtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_guidebtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_guidebtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_guidebtn2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_guidebtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_guidebtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_guidebtn2, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_guidebtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_guidebtn2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_guidebtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_guidebtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_guidebtn2, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_guidebtn2, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_guidebtn2, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_guidebtn2, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_guidebtn2t = lv_label_create(ui_guidebtn2);
    lv_obj_set_width(ui_guidebtn2t, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_guidebtn2t, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_guidebtn2t, LV_ALIGN_CENTER);
    lv_label_set_text(ui_guidebtn2t, "Skip");
    lv_obj_set_style_text_color(ui_guidebtn2t, lv_color_hex(0x91BF25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_guidebtn2t, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_guidebtn2t, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_guidebtn1, ui_event_guidebtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_guidebtn2, ui_event_guidebtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_Flag, ui_event_Page_Flag, LV_EVENT_ALL, NULL);

}
