// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_OTA_screen_init(void)
{
    ui_Page_OTA = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_OTA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_OTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_OTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otapanel = lv_obj_create(ui_Page_OTA);
    lv_obj_set_width(ui_otapanel, 412);
    lv_obj_set_height(ui_otapanel, 412);
    lv_obj_set_align(ui_otapanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_otapanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_otapanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_otapanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_otapanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_otapanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otatext = lv_label_create(ui_otapanel);
    lv_obj_set_width(ui_otatext, 335);
    lv_obj_set_height(ui_otatext, 61);
    lv_obj_set_x(ui_otatext, 0);
    lv_obj_set_y(ui_otatext, 41);
    lv_obj_set_align(ui_otatext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_otatext, "This might take several minutes...");
    lv_obj_set_style_text_color(ui_otatext, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_otatext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_otatext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_otatext, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otastatus = lv_label_create(ui_otapanel);
    lv_obj_set_width(ui_otastatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_otastatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_otastatus, 0);
    lv_obj_set_y(ui_otastatus, -42);
    lv_obj_set_align(ui_otastatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_otastatus, "Updating\nFirmware");
    lv_obj_set_style_text_color(ui_otastatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_otastatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_otastatus, &ui_font_semibold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otaspinner = lv_spinner_create(ui_otapanel, 1000, 90);
    lv_obj_set_width(ui_otaspinner, 40);
    lv_obj_set_height(ui_otaspinner, 40);
    lv_obj_set_x(ui_otaspinner, 0);
    lv_obj_set_y(ui_otaspinner, -109);
    lv_obj_set_align(ui_otaspinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_otaspinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_otaspinner, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_otaspinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_otaspinner, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_otaspinner, lv_color_hex(0x91BF25), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_otaspinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_otaspinner, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_otaicon = lv_img_create(ui_otapanel);
    lv_img_set_src(ui_otaicon, &ui_img_wifiok_png);
    lv_obj_set_width(ui_otaicon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_otaicon, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_otaicon, 0);
    lv_obj_set_y(ui_otaicon, -120);
    lv_obj_set_align(ui_otaicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_otaicon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_otaicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_otaarc = lv_arc_create(ui_otapanel);
    lv_obj_set_width(ui_otaarc, 412);
    lv_obj_set_height(ui_otaarc, 412);
    lv_obj_set_align(ui_otaarc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_otaarc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_otaarc, 1);
    lv_arc_set_bg_angles(ui_otaarc, 0, 360);
    lv_arc_set_rotation(ui_otaarc, 270);
    lv_obj_set_style_arc_color(ui_otaarc, lv_color_hex(0x1D2608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_otaarc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_otaarc, lv_color_hex(0xA1D42A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_otaarc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_otaarc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_otaarc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_otaback = lv_btn_create(ui_Page_OTA);
    lv_obj_set_width(ui_otaback, 60);
    lv_obj_set_height(ui_otaback, 60);
    lv_obj_set_x(ui_otaback, 0);
    lv_obj_set_y(ui_otaback, 120);
    lv_obj_set_align(ui_otaback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_otaback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_otaback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_otaback, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_otaback, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_otaback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_otaback, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_otaback, ui_event_otaback, LV_EVENT_ALL, NULL);

}
