// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Home_screen_init(void)
{
    ui_Page_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Page_Home, &ui_img_page_main_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainlist = lv_obj_create(ui_Page_Home);
    lv_obj_set_width(ui_mainlist, 130);
    lv_obj_set_height(ui_mainlist, 399);
    lv_obj_set_x(ui_mainlist, 140);
    lv_obj_set_y(ui_mainlist, 0);
    lv_obj_set_align(ui_mainlist, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mainlist, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_mainlist, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_add_flag(ui_mainlist, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_mainlist, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_mainlist, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_mainlist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainlp1 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp1, 90);
    lv_obj_set_height(ui_mainlp1, 90);
    lv_obj_set_align(ui_mainlp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainlp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn1 = lv_btn_create(ui_mainlp1);
    lv_obj_set_width(ui_mainbtn1, 80);
    lv_obj_set_height(ui_mainbtn1, 80);
    lv_obj_set_align(ui_mainbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn1, &ui_img_task_template_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mainbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_mainbtn1, &ui_img_1415499115, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_mainbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn1, &ui_img_1415499115, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_mainbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_mainbtn1, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_mainlp2 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp2, 90);
    lv_obj_set_height(ui_mainlp2, 90);
    lv_obj_set_align(ui_mainlp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainlp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn2 = lv_btn_create(ui_mainlp2);
    lv_obj_set_width(ui_mainbtn2, 80);
    lv_obj_set_height(ui_mainbtn2, 80);
    lv_obj_set_align(ui_mainbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn2, &ui_img_currenttask_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mainbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn2, &ui_img_1158392298, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn2, &ui_img_1158392298, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_mainbtn2, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_mainlp3 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp3, 90);
    lv_obj_set_height(ui_mainlp3, 90);
    lv_obj_set_align(ui_mainlp3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_mainlp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn3 = lv_btn_create(ui_mainlp3);
    lv_obj_set_width(ui_mainbtn3, 80);
    lv_obj_set_height(ui_mainbtn3, 80);
    lv_obj_set_align(ui_mainbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn3, &ui_img_extension_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mainbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn3, &ui_img_1722191473, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_mainbtn3, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_mainlp4 = lv_obj_create(ui_mainlist);
    lv_obj_set_width(ui_mainlp4, 90);
    lv_obj_set_height(ui_mainlp4, 90);
    lv_obj_set_x(ui_mainlp4, 15);
    lv_obj_set_y(ui_mainlp4, 110);
    lv_obj_set_align(ui_mainlp4, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_mainlp4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainlp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainlp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainlp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainlp4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainbtn4 = lv_btn_create(ui_mainlp4);
    lv_obj_set_width(ui_mainbtn4, 80);
    lv_obj_set_height(ui_mainbtn4, 80);
    lv_obj_set_align(ui_mainbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mainbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainbtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_mainbtn4, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mainbtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_mainbtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainbtn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(ui_mainbtn4, &ui_img_setting_f_png, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_mainbtn4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_mainbtn4, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_maincontent = lv_obj_create(ui_Page_Home);
    lv_obj_set_width(ui_maincontent, 263);
    lv_obj_set_height(ui_maincontent, 240);
    lv_obj_set_x(ui_maincontent, 10);
    lv_obj_set_y(ui_maincontent, 0);
    lv_obj_set_align(ui_maincontent, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_maincontent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_maincontent, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_maincontent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_maincontent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_maincontent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_maincontent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_maincontent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Devicep = lv_obj_create(ui_maincontent);
    lv_obj_set_width(ui_Devicep, 256);
    lv_obj_set_height(ui_Devicep, 50);
    lv_obj_set_x(ui_Devicep, -19);
    lv_obj_set_y(ui_Devicep, -1);
    lv_obj_set_align(ui_Devicep, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Devicep, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Devicep, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Devicep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Devicep, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Devicep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Devicep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Devicep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maintime = lv_label_create(ui_Devicep);
    lv_obj_set_width(ui_maintime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maintime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_maintime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maintime, "18:20");
    lv_obj_set_style_text_color(ui_maintime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maintime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maintime, &ui_font_semibold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainwifi = lv_img_create(ui_Devicep);
    lv_img_set_src(ui_mainwifi, &ui_img_no_wifi_png);
    lv_obj_set_width(ui_mainwifi, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_mainwifi, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_align(ui_mainwifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainwifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_mainwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_mainwifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainb = lv_img_create(ui_Devicep);
    lv_img_set_src(ui_mainb, &ui_img_battery_frame_png);
    lv_obj_set_width(ui_mainb, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_mainb, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_align(ui_mainb, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_mainb, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_mainb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_mainb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btpert = lv_label_create(ui_mainb);
    lv_obj_set_width(ui_btpert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btpert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_btpert, 9);
    lv_obj_set_y(ui_btpert, -1);
    lv_obj_set_align(ui_btpert, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_btpert, "96");
    lv_obj_set_style_text_color(ui_btpert, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btpert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btpert, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainble = lv_img_create(ui_Devicep);
    lv_img_set_src(ui_mainble, &ui_img_ble_png);
    lv_obj_set_width(ui_mainble, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_mainble, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_align(ui_mainble, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_mainble, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_mainble, 200);
    lv_obj_set_style_img_recolor(ui_mainble, lv_color_hex(0x171515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_mainble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maintitle = lv_label_create(ui_Page_Home);
    lv_obj_set_width(ui_maintitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maintitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maintitle, 50);
    lv_obj_set_y(ui_maintitle, 0);
    lv_obj_set_align(ui_maintitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_maintitle, "Task\nTemplates");
    lv_obj_set_style_text_color(ui_maintitle, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maintitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maintitle, &ui_font_semibold42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mcontrolp = lv_obj_create(ui_Page_Home);
    lv_obj_set_width(ui_mcontrolp, 412);
    lv_obj_set_height(ui_mcontrolp, 412);
    lv_obj_set_x(ui_mcontrolp, 0);
    lv_obj_set_y(ui_mcontrolp, 1);
    lv_obj_set_align(ui_mcontrolp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mcontrolp, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_mcontrolp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mcontrolp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mcontrolp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mcontrolp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mcontrolp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mainbtn1, ui_event_mainbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainbtn2, ui_event_mainbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainbtn3, ui_event_mainbtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainbtn4, ui_event_mainbtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_Home, ui_event_Page_Home, LV_EVENT_ALL, NULL);

}
