// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Slider_screen_init(void)
{
    ui_Page_Slider = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Slider, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Slider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bvpb = lv_obj_create(ui_Page_Slider);
    lv_obj_set_width(ui_bvpb, 320);
    lv_obj_set_height(ui_bvpb, 67);
    lv_obj_set_x(ui_bvpb, 0);
    lv_obj_set_y(ui_bvpb, -100);
    lv_obj_set_align(ui_bvpb, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bvpb, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_bvpb, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bvpb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bvpb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bvpb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bvpb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bvpb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bvbimg = lv_img_create(ui_bvpb);
    lv_img_set_src(ui_bvbimg, &ui_img_volicon_png);
    lv_obj_set_width(ui_bvbimg, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_bvbimg, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_align(ui_bvbimg, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_bvbimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bvbimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bvbt = lv_label_create(ui_bvpb);
    lv_obj_set_width(ui_bvbt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bvbt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bvbt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bvbt, "Volume");
    lv_obj_set_style_text_color(ui_bvbt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bvbt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bvbt, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bvbv = lv_label_create(ui_bvpb);
    lv_obj_set_width(ui_bvbv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bvbv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bvbv, 91);
    lv_obj_set_y(ui_bvbv, 0);
    lv_obj_set_align(ui_bvbv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bvbv, "0");
    lv_obj_set_style_text_color(ui_bvbv, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bvbv, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bvbv, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bvs = lv_label_create(ui_bvpb);
    lv_obj_set_width(ui_bvs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bvs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bvs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bvs, "%");
    lv_obj_set_style_text_color(ui_bvs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bvs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bvs, &ui_font_fontbold26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bvtp = lv_obj_create(ui_Page_Slider);
    lv_obj_set_width(ui_bvtp, 288);
    lv_obj_set_height(ui_bvtp, 60);
    lv_obj_set_x(ui_bvtp, 0);
    lv_obj_set_y(ui_bvtp, -179);
    lv_obj_set_align(ui_bvtp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bvtp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bvtp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bvtp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bvtp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bvtp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bvtitle = lv_label_create(ui_bvtp);
    lv_obj_set_width(ui_bvtitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bvtitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bvtitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bvtitle, "Sound");
    lv_obj_set_style_text_color(ui_bvtitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bvtitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bvtitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bvback = lv_btn_create(ui_Page_Slider);
    lv_obj_set_width(ui_bvback, 75);
    lv_obj_set_height(ui_bvback, 75);
    lv_obj_set_x(ui_bvback, 0);
    lv_obj_set_y(ui_bvback, 120);
    lv_obj_set_align(ui_bvback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bvback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bvback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bvback, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bvback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bvback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_bvback, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_bvback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_bvback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bvback, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_bvback, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_bvback, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_vp = lv_obj_create(ui_Page_Slider);
    lv_obj_set_width(ui_vp, 380);
    lv_obj_set_height(ui_vp, 100);
    lv_obj_set_align(ui_vp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_vp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vp, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vp, lv_color_hex(0x202124), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_vp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_vp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_vp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_vp, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_vslider = lv_slider_create(ui_vp);
    lv_slider_set_value(ui_vslider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_vslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_vslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_vslider, 250);
    lv_obj_set_height(ui_vslider, 30);
    lv_obj_set_align(ui_vslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_vslider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_vslider, lv_color_hex(0x8FC31F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_vslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_vslider, lv_color_hex(0x8FC31F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_vslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_vslider, 4, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_bp = lv_obj_create(ui_Page_Slider);
    lv_obj_set_width(ui_bp, 380);
    lv_obj_set_height(ui_bp, 100);
    lv_obj_set_align(ui_bp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_bp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bp, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bp, lv_color_hex(0x202124), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bslider = lv_slider_create(ui_bp);
    lv_slider_set_value(ui_bslider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_bslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_bslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bslider, 250);
    lv_obj_set_height(ui_bslider, 30);
    lv_obj_set_align(ui_bslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_bslider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_bslider, lv_color_hex(0x1F6DC3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_bslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bslider, lv_color_hex(0x1F6DC3), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bslider, 4, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bvback, ui_event_bvback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vslider, ui_event_vslider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bslider, ui_event_bslider, LV_EVENT_ALL, NULL);

}
