// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_About_screen_init(void)
{
    ui_Page_About = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_About, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_About, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutP = lv_obj_create(ui_Page_About);
    lv_obj_set_width(ui_AboutP, 380);
    lv_obj_set_height(ui_AboutP, 356);
    lv_obj_set_x(ui_AboutP, 0);
    lv_obj_set_y(ui_AboutP, 24);
    lv_obj_set_align(ui_AboutP, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutP, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AboutP, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_AboutP, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scroll_dir(ui_AboutP, LV_DIR_VER);
    lv_obj_set_style_radius(ui_AboutP, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AboutP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AboutP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AboutP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AboutP, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AboutP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AboutP, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutP, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AboutP, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AboutP, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AboutP, 60, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AboutP, 100, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_aboutdevname = lv_obj_create(ui_AboutP);
    lv_obj_set_width(ui_aboutdevname, 300);
    lv_obj_set_height(ui_aboutdevname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutdevname, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aboutdevname, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_aboutdevname, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_aboutdevname, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aboutdevname, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aboutdevname, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aboutdevname, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aboutdevname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aboutdevname, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aboutdevname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aboutdevname, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_aboutdevname, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_aboutdevname, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_aboutdevname, 1, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_devnamet1 = lv_label_create(ui_aboutdevname);
    lv_obj_set_width(ui_devnamet1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devnamet1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_devnamet1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_devnamet1, "Device Name :");
    lv_obj_set_style_text_color(ui_devnamet1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_devnamet1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_devnamet1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devnamet2 = lv_label_create(ui_aboutdevname);
    lv_obj_set_width(ui_devnamet2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devnamet2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_devnamet2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_devnamet2, "SenseCAP Watcher");
    lv_obj_add_flag(ui_devnamet2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_devnamet2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_devnamet2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_devnamet2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutespversion = lv_obj_create(ui_AboutP);
    lv_obj_set_width(ui_aboutespversion, 300);
    lv_obj_set_height(ui_aboutespversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutespversion, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aboutespversion, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_aboutespversion, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_aboutespversion, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aboutespversion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aboutespversion, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aboutespversion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aboutespversion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aboutespversion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aboutespversion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aboutespversion, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_aboutespversion, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_aboutespversion, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_aboutespversion, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_espversiont1 = lv_label_create(ui_aboutespversion);
    lv_obj_set_width(ui_espversiont1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_espversiont1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_espversiont1, 1);
    lv_obj_set_y(ui_espversiont1, 0);
    lv_obj_set_align(ui_espversiont1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_espversiont1, "ESP32 Firmware :");
    lv_obj_set_style_text_color(ui_espversiont1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_espversiont1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_espversiont1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_espversiont2 = lv_label_create(ui_aboutespversion);
    lv_obj_set_width(ui_espversiont2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_espversiont2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_espversiont2, 1);
    lv_obj_set_y(ui_espversiont2, 0);
    lv_obj_set_align(ui_espversiont2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_espversiont2, "1.0");
    lv_obj_add_flag(ui_espversiont2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_espversiont2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_espversiont2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_espversiont2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutaiversion = lv_obj_create(ui_AboutP);
    lv_obj_set_width(ui_aboutaiversion, 300);
    lv_obj_set_height(ui_aboutaiversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutaiversion, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aboutaiversion, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_aboutaiversion, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_aboutaiversion, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aboutaiversion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aboutaiversion, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aboutaiversion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aboutaiversion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aboutaiversion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aboutaiversion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aboutaiversion, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_aboutaiversion, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_aboutaiversion, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_aboutaiversion, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_aiversion1 = lv_label_create(ui_aboutaiversion);
    lv_obj_set_width(ui_aiversion1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aiversion1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aiversion1, 1);
    lv_obj_set_y(ui_aiversion1, 0);
    lv_obj_set_align(ui_aiversion1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aiversion1, "AI Firmware :");
    lv_obj_set_style_text_color(ui_aiversion1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aiversion1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aiversion1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aiversion2 = lv_label_create(ui_aboutaiversion);
    lv_obj_set_width(ui_aiversion2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aiversion2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aiversion2, 1);
    lv_obj_set_y(ui_aiversion2, 0);
    lv_obj_set_align(ui_aiversion2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_aiversion2, "1.0");
    lv_obj_add_flag(ui_aiversion2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_aiversion2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aiversion2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aiversion2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutsn = lv_obj_create(ui_AboutP);
    lv_obj_set_width(ui_aboutsn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aboutsn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutsn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aboutsn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_aboutsn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_aboutsn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aboutsn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aboutsn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aboutsn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aboutsn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aboutsn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aboutsn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aboutsn, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_aboutsn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_aboutsn, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_aboutsn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_snt1 = lv_label_create(ui_aboutsn);
    lv_obj_set_width(ui_snt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_snt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_snt1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_snt1, "S/N :");
    lv_obj_set_style_text_color(ui_snt1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_snt1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_snt1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_snt2 = lv_label_create(ui_aboutsn);
    lv_obj_set_width(ui_snt2, 260);
    lv_obj_set_height(ui_snt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_snt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_snt2, "xxxxxxxxxxxxxxxxxxxx");
    lv_obj_add_flag(ui_snt2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_snt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_snt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_snt2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_snt2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_abouteui = lv_obj_create(ui_AboutP);
    lv_obj_set_width(ui_abouteui, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_abouteui, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_abouteui, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_abouteui, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_abouteui, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_abouteui, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_abouteui, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_abouteui, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_abouteui, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_abouteui, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_abouteui, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_abouteui, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_abouteui, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_abouteui, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_abouteui, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_abouteui, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_euit1 = lv_label_create(ui_abouteui);
    lv_obj_set_width(ui_euit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_euit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_euit1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_euit1, "EUI :");
    lv_obj_set_style_text_color(ui_euit1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_euit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_euit1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_euit2 = lv_label_create(ui_abouteui);
    lv_obj_set_width(ui_euit2, 260);
    lv_obj_set_height(ui_euit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_euit2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_euit2, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    lv_obj_add_flag(ui_euit2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_euit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_euit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_euit2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutblemac = lv_obj_create(ui_AboutP);
    lv_obj_set_width(ui_aboutblemac, 300);
    lv_obj_set_height(ui_aboutblemac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutblemac, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aboutblemac, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_aboutblemac, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_aboutblemac, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aboutblemac, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aboutblemac, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aboutblemac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aboutblemac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aboutblemac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aboutblemac, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aboutblemac, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_aboutblemac, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_aboutblemac, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_aboutblemac, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_blet1 = lv_label_create(ui_aboutblemac);
    lv_obj_set_width(ui_blet1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_blet1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_blet1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_blet1, "Bluetooth Mac:");
    lv_obj_set_style_text_color(ui_blet1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_blet1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_blet1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blet2 = lv_label_create(ui_aboutblemac);
    lv_obj_set_width(ui_blet2, 260);
    lv_obj_set_height(ui_blet2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_blet2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_blet2, "xxxxxxxxxxx");
    lv_obj_add_flag(ui_blet2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_blet2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_blet2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_blet2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aboutwifimac = lv_obj_create(ui_AboutP);
    lv_obj_set_width(ui_aboutwifimac, 300);
    lv_obj_set_height(ui_aboutwifimac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_aboutwifimac, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_aboutwifimac, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_aboutwifimac, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_aboutwifimac, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_aboutwifimac, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_aboutwifimac, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aboutwifimac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aboutwifimac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aboutwifimac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aboutwifimac, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_aboutwifimac, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_aboutwifimac, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_aboutwifimac, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_aboutwifimac, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_wifit1 = lv_label_create(ui_aboutwifimac);
    lv_obj_set_width(ui_wifit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifit1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifit1, "Wi-Fi Mac:");
    lv_obj_set_style_text_color(ui_wifit1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifit1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifit2 = lv_label_create(ui_aboutwifimac);
    lv_obj_set_width(ui_wifit2, 260);
    lv_obj_set_height(ui_wifit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifit2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifit2, "xx:xx:xx:xx:xx:xx:xx");
    lv_obj_add_flag(ui_wifit2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_wifit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifit2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Paboutb = lv_btn_create(ui_AboutP);
    lv_obj_set_width(ui_Paboutb, 60);
    lv_obj_set_height(ui_Paboutb, 60);
    lv_obj_set_x(ui_Paboutb, 0);
    lv_obj_set_y(ui_Paboutb, 120);
    lv_obj_set_align(ui_Paboutb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Paboutb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Paboutb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Paboutb, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Paboutb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Paboutb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Paboutb, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Paboutb, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Paboutb, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_abtp = lv_obj_create(ui_Page_About);
    lv_obj_set_width(ui_abtp, 288);
    lv_obj_set_height(ui_abtp, 60);
    lv_obj_set_x(ui_abtp, 0);
    lv_obj_set_y(ui_abtp, -179);
    lv_obj_set_align(ui_abtp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_abtp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_abtp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_abtp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_abtp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_abtp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_abtitle = lv_label_create(ui_abtp);
    lv_obj_set_width(ui_abtitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_abtitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_abtitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_abtitle, "About");
    lv_obj_set_style_text_color(ui_abtitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_abtitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_abtitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_aboutdevname, ui_event_aboutdevname, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aboutespversion, ui_event_aboutespversion, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aboutaiversion, ui_event_aboutaiversion, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aboutsn, ui_event_aboutsn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_abouteui, ui_event_abouteui, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aboutblemac, ui_event_aboutblemac, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aboutwifimac, ui_event_aboutwifimac, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Paboutb, ui_event_Paboutb, LV_EVENT_ALL, NULL);

}
