// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Sleep_screen_init(void)
{
    ui_Page_Sleep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Sleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Sleep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Sleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleeptimeroller = lv_roller_create(ui_Page_Sleep);
    lv_roller_set_options(ui_sleeptimeroller, "Never\n1 min\n5 min\n10 min\n15 min\n30 min\n24 hours",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_sleeptimeroller, 250);
    lv_obj_set_height(ui_sleeptimeroller, 153);
    lv_obj_set_x(ui_sleeptimeroller, 0);
    lv_obj_set_y(ui_sleeptimeroller, -55);
    lv_obj_set_align(ui_sleeptimeroller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_sleeptimeroller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleeptimeroller, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sleeptimeroller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleeptimeroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sleeptimeroller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sleeptimeroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sleeptimeroller, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_sleeptimeroller, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_sleeptimeroller, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_sleeptimeroller, 10, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_bg_color(ui_sleeptimeroller, lv_color_hex(0x8FC31F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleeptimeroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sleeptimeroller, lv_color_hex(0x8FC31F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_sleeptimeroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_sleeptimeroller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_sleeptimeroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_slpback = lv_btn_create(ui_Page_Sleep);
    lv_obj_set_width(ui_slpback, 60);
    lv_obj_set_height(ui_slpback, 60);
    lv_obj_set_x(ui_slpback, 0);
    lv_obj_set_y(ui_slpback, 142);
    lv_obj_set_align(ui_slpback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slpback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_slpback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_slpback, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slpback, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slpback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slpback, &ui_img_button_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_slpback, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_slpback, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_slpback, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_slpback, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_sleepswitchp = lv_obj_create(ui_Page_Sleep);
    lv_obj_set_width(ui_sleepswitchp, 347);
    lv_obj_set_height(ui_sleepswitchp, 50);
    lv_obj_set_x(ui_sleepswitchp, 0);
    lv_obj_set_y(ui_sleepswitchp, 66);
    lv_obj_set_align(ui_sleepswitchp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_sleepswitchp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_sleepswitchp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_sleepswitchp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sleepswitchp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sleepswitchp, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sleepswitchp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleepswitchp, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_sleepswitchp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_sleepswitchp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_sleepswitchp, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_sleepswitchp, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sleepswitchp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sleepswitchp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sleepswitchp, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_sleepswitchp, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_sleepswitchp, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_sleepswitchp, 6, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_sleepswitcht = lv_label_create(ui_sleepswitchp);
    lv_obj_set_width(ui_sleepswitcht, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sleepswitcht, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_sleepswitcht, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_sleepswitcht, "Light Up When Alert");
    lv_obj_set_style_text_color(ui_sleepswitcht, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sleepswitcht, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleepswitcht, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepswitch = lv_switch_create(ui_sleepswitchp);
    lv_obj_set_width(ui_sleepswitch, 66);
    lv_obj_set_height(ui_sleepswitch, 34);
    lv_obj_set_align(ui_sleepswitch, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_sleepswitch, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sleepswitch, 50, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_sleepswitch, lv_color_hex(0x2D89EF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_sleepswitch, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_sleepswitch, 4, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_sleepswitch, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_bg_color(ui_sleepswitch, lv_color_hex(0x8FC31F), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sleepswitch, 50, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_sleepswitch, lv_color_hex(0x8FC31F), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_sleepswitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_sleepswitch, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_sleepswitch, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_sleepswitch, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_sleepswitch, 0, LV_PART_KNOB | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_sleeptimeroller, ui_event_sleeptimeroller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slpback, ui_event_slpback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sleepswitch, ui_event_sleepswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sleepswitchp, ui_event_sleepswitchp, LV_EVENT_ALL, NULL);

}
