// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_ViewLive_screen_init(void)
{
    ui_Page_ViewLive = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_ViewLive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_ViewLive, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_ViewLive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewlivp2 = lv_obj_create(ui_Page_ViewLive);
    lv_obj_set_width(ui_viewlivp2, 412);
    lv_obj_set_height(ui_viewlivp2, 412);
    lv_obj_set_align(ui_viewlivp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_viewlivp2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_viewlivp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_viewlivp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewlivp2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_viewlivp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_viewlivp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewtext = lv_label_create(ui_viewlivp2);
    lv_obj_set_width(ui_viewtext, 360);
    lv_obj_set_height(ui_viewtext, 31);
    lv_obj_set_align(ui_viewtext, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_viewtext, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_viewtext, "A man is smoking here.                    ");
    lv_obj_set_style_text_color(ui_viewtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_viewtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_viewtext, &ui_font_fontbold26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewback = lv_btn_create(ui_viewlivp2);
    lv_obj_set_width(ui_viewback, 80);
    lv_obj_set_height(ui_viewback, 80);
    lv_obj_set_x(ui_viewback, 0);
    lv_obj_set_y(ui_viewback, 120);
    lv_obj_set_align(ui_viewback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_viewback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_viewback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_viewback, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_viewback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_viewback, &ui_img_setback_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_viewback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_viewback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_viewback, ui_event_viewback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_ViewLive, ui_event_Page_ViewLive, LV_EVENT_ALL, NULL);

}
