// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SenseCAP-Watcher

#include "../ui.h"

void ui_Page_Set_screen_init(void)
{
    ui_Page_Set = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page_Set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page_Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page_Set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Page_Set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Page_Set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set_panel = lv_obj_create(ui_Page_Set);
    lv_obj_set_width(ui_Set_panel, 412);
    lv_obj_set_height(ui_Set_panel, 412);
    lv_obj_set_align(ui_Set_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Set_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Set_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Set_panel, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Set_panel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Set_panel, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Set_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Set_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Set_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Set_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setback = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setback, 300);
    lv_obj_set_height(ui_setback, 50);
    lv_obj_set_align(ui_setback, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setback, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_setback, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_setback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setback, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setback, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setback, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setback, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setback, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_setback);
    lv_img_set_src(ui_Image1, &ui_img_setback_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image1, 50);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 200);

    ui_setbackt = lv_label_create(ui_setback);
    lv_obj_set_width(ui_setbackt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setbackt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setbackt, 60);
    lv_obj_set_y(ui_setbackt, 29);
    lv_obj_set_align(ui_setbackt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setbackt, "Back");
    lv_obj_set_style_text_color(ui_setbackt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setbackt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setbackt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setdown = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setdown, 412);
    lv_obj_set_height(ui_setdown, 50);
    lv_obj_set_align(ui_setdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setdown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setdown, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setdown, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setdown, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setdown, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setdownt = lv_label_create(ui_setdown);
    lv_obj_set_width(ui_setdownt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setdownt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setdownt, 50);
    lv_obj_set_y(ui_setdownt, 0);
    lv_obj_set_align(ui_setdownt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setdownt, "Shutdown");
    lv_obj_set_style_text_color(ui_setdownt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setdownt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setdownt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setapp = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setapp, 412);
    lv_obj_set_height(ui_setapp, 50);
    lv_obj_set_align(ui_setapp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setapp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setapp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setapp, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setapp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setapp, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setapp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setapp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setapp, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setapp, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setapp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setapp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setappt = lv_label_create(ui_setapp);
    lv_obj_set_width(ui_setappt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setappt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setappt, 50);
    lv_obj_set_y(ui_setappt, 0);
    lv_obj_set_align(ui_setappt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setappt, "Connect App");
    lv_obj_set_style_text_color(ui_setappt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setappt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setappt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setwifi = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setwifi, 412);
    lv_obj_set_height(ui_setwifi, 50);
    lv_obj_set_align(ui_setwifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setwifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setwifi, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setwifi, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setwifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setwifi, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setwifi, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setwifit = lv_label_create(ui_setwifi);
    lv_obj_set_width(ui_setwifit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setwifit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setwifit, 50);
    lv_obj_set_y(ui_setwifit, 0);
    lv_obj_set_align(ui_setwifit, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setwifit, "Wi-Fi");
    lv_obj_set_style_text_color(ui_setwifit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setwifit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setwifit, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setble = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setble, 412);
    lv_obj_set_height(ui_setble, 50);
    lv_obj_set_x(ui_setble, 3);
    lv_obj_set_y(ui_setble, 1);
    lv_obj_set_align(ui_setble, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setble, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setble, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setble, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setble, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setble, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setble, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setble, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setble, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setble, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setble, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setblet = lv_label_create(ui_setble);
    lv_obj_set_width(ui_setblet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setblet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setblet, 50);
    lv_obj_set_y(ui_setblet, 0);
    lv_obj_set_align(ui_setblet, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setblet, "Bluetooth");
    lv_obj_set_style_text_color(ui_setblet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setblet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setblet, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setblesw = lv_switch_create(ui_setble);
    lv_obj_set_width(ui_setblesw, 60);
    lv_obj_set_height(ui_setblesw, 25);
    lv_obj_set_x(ui_setblesw, 140);
    lv_obj_set_y(ui_setblesw, 0);
    lv_obj_set_align(ui_setblesw, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_setblesw, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setblesw, 50, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_setblesw, lv_color_hex(0x8FC31F), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setblesw, 50, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_setblesw, lv_color_hex(0x8FC31F), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setblesw, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_setblesw, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_setblesw, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_setblesw, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_setblesw, 5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_setvol = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setvol, 412);
    lv_obj_set_height(ui_setvol, 50);
    lv_obj_set_x(ui_setvol, 0);
    lv_obj_set_y(ui_setvol, 36);
    lv_obj_set_align(ui_setvol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setvol, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setvol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setvol, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setvol, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setvol, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setvol, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setvol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setvol, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setvol, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setvol, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setvol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setvolt = lv_label_create(ui_setvol);
    lv_obj_set_width(ui_setvolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setvolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setvolt, 50);
    lv_obj_set_y(ui_setvolt, 0);
    lv_obj_set_align(ui_setvolt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setvolt, "Sound");
    lv_obj_set_style_text_color(ui_setvolt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setvolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setvolt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setbri = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setbri, 412);
    lv_obj_set_height(ui_setbri, 50);
    lv_obj_set_x(ui_setbri, 0);
    lv_obj_set_y(ui_setbri, 36);
    lv_obj_set_align(ui_setbri, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setbri, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setbri, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setbri, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setbri, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setbri, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setbri, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setbri, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setbri, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setbri, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setbri, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setbri, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setbrit = lv_label_create(ui_setbri);
    lv_obj_set_width(ui_setbrit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setbrit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setbrit, 50);
    lv_obj_set_y(ui_setbrit, 0);
    lv_obj_set_align(ui_setbrit, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setbrit, "Brightness");
    lv_obj_set_style_text_color(ui_setbrit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setbrit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setbrit, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settime = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_settime, 412);
    lv_obj_set_height(ui_settime, 50);
    lv_obj_set_align(ui_settime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settime, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settime, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_settime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_settime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_settime, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_settime, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_settime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_settime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settimt = lv_label_create(ui_settime);
    lv_obj_set_width(ui_settimt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settimt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settimt, 50);
    lv_obj_set_y(ui_settimt, 0);
    lv_obj_set_align(ui_settimt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settimt, "Turn Screen Off");
    lv_obj_set_style_text_color(ui_settimt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settimt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settimt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setrgb = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setrgb, 412);
    lv_obj_set_height(ui_setrgb, 50);
    lv_obj_set_align(ui_setrgb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setrgb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setrgb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setrgb, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setrgb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setrgb, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setrgb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setrgb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setrgb, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setrgb, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setrgb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setrgb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setrgbt = lv_label_create(ui_setrgb);
    lv_obj_set_width(ui_setrgbt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setrgbt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setrgbt, 50);
    lv_obj_set_y(ui_setrgbt, 0);
    lv_obj_set_align(ui_setrgbt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setrgbt, "RGB Light");
    lv_obj_set_style_text_color(ui_setrgbt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setrgbt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setrgbt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setrgbsw = lv_switch_create(ui_setrgb);
    lv_obj_set_width(ui_setrgbsw, 60);
    lv_obj_set_height(ui_setrgbsw, 25);
    lv_obj_set_x(ui_setrgbsw, 140);
    lv_obj_set_y(ui_setrgbsw, 0);
    lv_obj_set_align(ui_setrgbsw, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_setrgbsw, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setrgbsw, 50, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_setrgbsw, lv_color_hex(0x8FC31F), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setrgbsw, 50, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_setrgbsw, lv_color_hex(0x8FC31F), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setrgbsw, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_setrgbsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_setrgbsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_setrgbsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_setrgbsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_setww = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setww, 412);
    lv_obj_set_height(ui_setww, 50);
    lv_obj_set_align(ui_setww, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setww, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setww, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setww, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setww, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setww, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setww, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setww, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setww, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setww, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setww, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setww, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setwwt = lv_label_create(ui_setww);
    lv_obj_set_width(ui_setwwt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setwwt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setwwt, 50);
    lv_obj_set_y(ui_setwwt, 0);
    lv_obj_set_align(ui_setwwt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setwwt, "Wake Word");
    lv_obj_set_style_text_color(ui_setwwt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setwwt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setwwt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setwwsw = lv_switch_create(ui_setww);
    lv_obj_set_width(ui_setwwsw, 60);
    lv_obj_set_height(ui_setwwsw, 25);
    lv_obj_set_x(ui_setwwsw, 140);
    lv_obj_set_y(ui_setwwsw, 0);
    lv_obj_set_align(ui_setwwsw, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_setwwsw, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setwwsw, 50, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_setwwsw, lv_color_hex(0x8FC31F), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setwwsw, 50, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_setwwsw, lv_color_hex(0x8FC31F), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_setwwsw, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_setwwsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_setwwsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_setwwsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_setwwsw, 0, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_setdev = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setdev, 412);
    lv_obj_set_height(ui_setdev, 50);
    lv_obj_set_align(ui_setdev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setdev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setdev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setdev, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setdev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setdev, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setdev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setdev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setdev, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setdev, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setdev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setdev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setdevt = lv_label_create(ui_setdev);
    lv_obj_set_width(ui_setdevt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setdevt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setdevt, 50);
    lv_obj_set_y(ui_setdevt, 0);
    lv_obj_set_align(ui_setdevt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setdevt, "About Device");
    lv_obj_set_style_text_color(ui_setdevt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setdevt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setdevt, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setfac = lv_obj_create(ui_Set_panel);
    lv_obj_set_width(ui_setfac, 412);
    lv_obj_set_height(ui_setfac, 50);
    lv_obj_set_align(ui_setfac, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setfac, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setfac, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setfac, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setfac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setfac, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_setfac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_setfac, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_setfac, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_setfac, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setfac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setfac, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setfact = lv_label_create(ui_setfac);
    lv_obj_set_width(ui_setfact, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setfact, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setfact, 50);
    lv_obj_set_y(ui_setfact, 0);
    lv_obj_set_align(ui_setfact, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_setfact, "Factory Reset");
    lv_obj_set_style_text_color(ui_setfact, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setfact, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setfact, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settextp = lv_obj_create(ui_Page_Set);
    lv_obj_set_width(ui_settextp, 288);
    lv_obj_set_height(ui_settextp, 60);
    lv_obj_set_x(ui_settextp, 0);
    lv_obj_set_y(ui_settextp, -179);
    lv_obj_set_align(ui_settextp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settextp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_settextp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settextp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settextp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_settextp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_settextp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set_title = lv_label_create(ui_settextp);
    lv_obj_set_width(ui_Set_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Set_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Set_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Set_title, "Setting");
    lv_obj_set_style_text_color(ui_Set_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Set_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Set_title, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scontrolp = lv_obj_create(ui_Page_Set);
    lv_obj_set_width(ui_scontrolp, 412);
    lv_obj_set_height(ui_scontrolp, 412);
    lv_obj_set_align(ui_scontrolp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scontrolp, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_scontrolp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scontrolp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scontrolp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scontrolp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scontrolp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_scontrolp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scontrolp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_setback, ui_event_setback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setdown, ui_event_setdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setapp, ui_event_setapp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setwifi, ui_event_setwifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setble, ui_event_setble, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setvol, ui_event_setvol, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setbri, ui_event_setbri, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settime, ui_event_settime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setrgb, ui_event_setrgb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setww, ui_event_setww, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setdev, ui_event_setdev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setfac, ui_event_setfac, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Page_Set, ui_event_Page_Set, LV_EVENT_ALL, NULL);

}
