// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ai
#include "esp_log.h"
#include "data_defs.h"
#include "event_loops.h"
#include "esp_wifi.h"
#include <dirent.h>
#include "esp_timer.h"

#include "ui/ui.h"
#include "view.h"
#include "pm.h"
#include "animation.h"
#include "event.h"

#include "app_device_info.h"
#include "app_ble.h"
#include "app_wifi.h"
#include "storage.h"
#include "app_png.h"
#include "app_rgb.h"
#include "sensecap-watcher.h"
#include "task_flow_engine/include/tf.h"

#define VOLBRI_CFG "volbri-cfg"
#define MAX_RETRIES 3

static const char *TAG = "ui_event";
static const char *CLICK_TAG = "Click_event";

wifi_ap_record_t wifi_record;
int g_guide_disable = 0;    // 0: usage guide enable,           1: usage guide disable
uint8_t g_taskdown = 1;     // 0: task running,                 1: task down
uint8_t g_guide_step = 0;   // usage guide step : 0~3
uint8_t g_swipeid = 0;      // 0: shutdown,                     1: factoryreset
uint8_t g_alarm_p = 0;      // 0: End Task panel display,       1: End_Task panel hidden 
uint8_t g_avarlive = 0;     // 0: current page is avatar,       1: current page is live
uint8_t g_tasktype = 0;     // 0: local task,                   1: remote task
uint8_t g_backpage = 0;
uint8_t g_avalivjump = 0;
uint8_t g_push2talk_timer = 1;// 0: Speaking countdown,         1: Scrolling countdown
extern uint8_t g_is_push2talk;

uint8_t screenoff_mode = 0;     // 0: normal; 1: sleep
uint8_t standby_mode = 0;    // 0: on;     1: off
int g_screenoff_time = 0;
int g_screenoff_switch = 1;
extern char *push2talk_item[TASK_CFG_ID_MAX];

uint8_t emoji_switch_scr = NULL;
extern uint8_t g_dev_binded;
extern uint8_t g_shutdown;
extern int g_screenoff_time;
extern int g_screenoff_switch;
extern uint8_t g_push2talk_status;
extern uint8_t g_taskflow_pause;
extern uint8_t g_push2talk_mode;

static lv_obj_t *qr;
static uint8_t loading_flag = 0;
static uint32_t emoji_user_data = NULL;
static struct view_data_setting_volbri volbri;
static struct view_data_setting_switch set_sw;
static struct view_data_emoticon_display emo_disp;

static lv_obj_t *avatar_image   = NULL;
static lv_obj_t *virtual_image  = NULL;
static lv_obj_t *flag_image     = NULL;
static lv_obj_t *standby_image  = NULL;
static lv_obj_t *push2talk_image = NULL;
static lv_obj_t *push2talk_speak_img = NULL;

static int current_img_index = 0;
static uint8_t vir_load_count = 0;
static uint32_t local_task_id = 4;
static lv_timer_t *g_timer;
static char *qrcode_content = NULL;

extern uint8_t emoticon_disp_id; // for lv_async switch and emoticon switch
extern lv_obj_t *ui_alarm_indicator;
extern lv_obj_t * ui_task_error;
extern uint8_t view_alarm_status;
extern lv_obj_t * ui_emoticonok;
extern lv_obj_t * pre_foucsed_obj;
extern uint8_t g_group_layer_;

extern lv_img_dsc_t *g_detect_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_speak_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_listen_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_analyze_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_standby_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_greet_img_dsc[MAX_IMAGES];
extern lv_img_dsc_t *g_detected_img_dsc[MAX_IMAGES];

extern int g_detect_image_count;
extern int g_speak_image_count;
extern int g_listen_image_count;
extern int g_analyze_image_count;
extern int g_standby_image_count;
extern int g_greet_image_count;
extern int g_detected_image_count;

extern GroupInfo group_page_main;
extern GroupInfo group_page_template;
extern GroupInfo group_page_notask;
extern GroupInfo group_page_extension;
extern GroupInfo group_page_set;
extern GroupInfo group_page_view;
extern GroupInfo group_page_brightness;
extern GroupInfo group_page_volume;
extern GroupInfo group_page_connectapp;
extern GroupInfo group_page_about;
extern GroupInfo group_page_guide;
extern GroupInfo group_page_sleep;
extern GroupInfo group_page_push2talk;

// view_alarm obj extern
extern lv_obj_t * ui_viewavap;
extern lv_obj_t * ui_viewpbtn1;
extern lv_obj_t * ui_viewpt1;
extern lv_obj_t * ui_viewpbtn2;
extern lv_obj_t * ui_viewpt2;
extern lv_obj_t * ui_viewpbtn3;

// view sleep
extern lv_obj_t * ui_Page_Standby;
// view emoji ota extern
extern lv_obj_t * ui_Page_Emoji;

// push2talk
lv_obj_t *push2talk_textarea;
static char *push2talk_text = NULL;
static uint32_t push2talk_text_index = 0;
static bool push2talk_timer_active = false;

// extension sensor
uint8_t bubble_position[4] = {3, 0, 1, 2};
static uint8_t extension_scroll_mode = 0;
static char sensor_data_1[6];
static char sensor_data_2[6];
static char sensor_data_3[6];
static char sensor_data_4[6];
typedef struct {
    int cur_idx;
    int pre_idx;
} ExtensionScroll;

ExtensionScroll extensionscroll;
static lv_timer_t * view_extension_timer;

// Bluetooth switch frequency filter
static lv_timer_t * view_ble_switch_timer;

static lv_timer_t * view_push2talk_expired_timer;
// Sleep mode scanner
#define ACTIVE_THRESHOLD (5000)
static lv_timer_t * view_sleep_timer;
static uint32_t inactive_time = 0;
static int get_inactive_time = 0;
static int inactive_threshold = 0;

// Push2talk timer
static lv_timer_t * view_push2talk_timer;
static uint8_t push2talk_timer_counter = 0;

static lv_timer_t * view_push2talk_msg_timer;
static uint8_t push2talk_panel_idx = 0;

static lv_timer_t * view_push2talk_animation_timer;

static void Page_ConnAPP_BLE();
static void Page_ConnAPP_Mate();
static void Task_end();
static void Page_shutdown();
static void Page_facreset();
static void view_info_obtain_early();
void sensor_date_update();

static lv_coord_t get_angle(const lv_obj_t * obj)
{
    lv_arc_t * arc = (lv_arc_t *)obj;
    uint16_t angle = arc->rotation;
    if(arc->type == LV_ARC_MODE_NORMAL) {
        angle += arc->indic_angle_end;
    }
    else if(arc->type == LV_ARC_MODE_REVERSE) {
        angle += arc->indic_angle_start;
    }
    else if(arc->type == LV_ARC_MODE_SYMMETRICAL) {
        int16_t bg_end = arc->bg_angle_end;
        if(arc->bg_angle_end < arc->bg_angle_start) bg_end = arc->bg_angle_end + 360;
        int16_t indic_end = arc->indic_angle_end;
        if(arc->indic_angle_end < arc->indic_angle_start) indic_end = arc->indic_angle_end + 360;

        int32_t angle_midpoint = (int32_t)(arc->bg_angle_start + bg_end) / 2;
        if(arc->indic_angle_start < angle_midpoint) angle += arc->indic_angle_start;
        else if(indic_end > angle_midpoint) angle += arc->indic_angle_end;
        else angle += angle_midpoint;
    }

    return angle;
}

static void async_emoji_switch_scr(void *arg)
{
    lv_img_dsc_t *current_img = (lv_img_dsc_t *)arg;
    if(emoji_switch_scr == SCREEN_VIRTUAL)
    {
        lv_img_set_src(virtual_image, current_img);
    }
    if(emoji_switch_scr == SCREEN_AVATAR)
    {
        lv_img_set_src(avatar_image, current_img);
    }
    if(emoji_switch_scr == SCREEN_GUIDE)
    {
        lv_img_set_src(flag_image, current_img);
    }
    if(emoji_switch_scr == SCREEN_STANDBY)
    {
        lv_img_set_src(standby_image, current_img);
    }
    if(emoji_switch_scr == SCREEN_PUSH2TALK)
    {
        lv_obj_add_flag(push2talk_speak_img, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(push2talk_image, LV_OBJ_FLAG_HIDDEN);
        lv_img_set_src(push2talk_image, current_img);
    }
    if(emoji_switch_scr == SCREEN_PUSH2TALK_SPEAK)
    {
        lv_obj_add_flag(push2talk_image, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(push2talk_speak_img, LV_OBJ_FLAG_HIDDEN);
        lv_img_set_src(push2talk_speak_img, current_img);
    }
}

static uint32_t emoji_period[] = {200, 1000, 2000, 500};
static uint8_t  emoji_count = 0;
static uint32_t eomji_interval = 500;

static void emoji_timer_callback(lv_timer_t *timer)
{
    if(emoji_count == 4)
    {
        emoji_count = 0;
    }
    eomji_interval = emoji_period[emoji_count];
    uint32_t * user_data = (uint32_t *)timer->user_data;
    const lv_img_dsc_t *current_img = NULL;

    if(*user_data == EMOJI_GREETING)
    {
        current_img_index = (current_img_index + 1) % g_greet_image_count;
        current_img = g_greet_img_dsc[current_img_index];
    }
    else if(*user_data == EMOJI_DETECTING)
    {
        current_img_index = (current_img_index + 1) % g_detect_image_count;
        current_img = g_detect_img_dsc[current_img_index];
    }
    else if(*user_data == EMOJI_DETECTED)
    {
        current_img_index = (current_img_index + 1) % g_detected_image_count;
        current_img = g_detected_img_dsc[current_img_index];
    }
    else if(*user_data == EMOJI_SPEAKING)
    {
        current_img_index = (current_img_index + 1) % g_speak_image_count;
        current_img = g_speak_img_dsc[current_img_index];
    }
    else if(*user_data == EMOJI_LISTENING)
    {
        current_img_index = (current_img_index + 1) % g_listen_image_count;
        current_img = g_listen_img_dsc[current_img_index];
    }
    else if(*user_data == EMOJI_ANALYZING)
    {
        current_img_index = (current_img_index + 1) % g_analyze_image_count;
        current_img = g_analyze_img_dsc[current_img_index];
    }
    else if(*user_data == EMOJI_STANDBY)
    {
        current_img_index = (current_img_index + 1) % g_standby_image_count;
        current_img = g_standby_img_dsc[current_img_index];
    }
    // ESP_LOGI(TAG, "current image index is %d", current_img_index + 1);
    if(current_img != NULL)
    {
        lv_async_call(async_emoji_switch_scr, (void *)current_img);
    }

    // lv_timer_set_period(g_timer, eomji_interval);

    if(*user_data == EMOJI_GREETING)
    {
        vir_load_count ++;
        // if delay 2s and the device is not wifi-configed
        if(vir_load_count > 8)
        {
            lv_event_send(ui_Page_Avatar, LV_EVENT_CLICKED, NULL);
        }
    }
    emoji_count ++;
}

void emoji_timer_stop()
{
    if((lv_scr_act() != ui_Page_ViewAva) && (lv_scr_act() != ui_Page_Guideavatar) && (lv_scr_act() != ui_Page_Standby) && (lv_scr_act() != ui_Page_Push2talk))
    {
        emoji_timer(EMOJI_STOP);
    }
}

void emoji_timer(uint8_t emoji_type)
{
    if (g_timer != NULL)
    {
        lv_timer_del(g_timer);
        g_timer = NULL;
    }
    emoji_user_data = emoji_type;
    if(emoji_user_data != EMOJI_STOP){
        current_img_index = -1;
        g_timer = lv_timer_create(emoji_timer_callback, 500, &emoji_user_data);
        emoji_timer_callback(g_timer);
    }
}

void slbattery_cb(lv_event_t *e) { }

static void set_obj_style_defocused(lv_obj_t *obj, lv_obj_t *obj_text)
{
    lv_obj_set_width(obj, 412);
    lv_obj_set_height(obj, 50);
    lv_obj_set_style_radius(obj, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(obj, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(obj_text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void set_obj_style_focused(lv_obj_t *obj, lv_obj_t *obj_text)
{
    lv_obj_set_width(obj, 380);
    lv_obj_set_height(obj, 90);
    lv_obj_set_style_radius(obj, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(obj, lv_color_hex(0xA9DE2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(obj, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(obj, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(obj_text, &ui_font_font_bold, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void startload_cb(lv_event_t *e)
{
    _ui_screen_change(&ui_Page_Loading, LV_SCR_LOAD_ANIM_NONE, 0, 3000, &ui_Page_Loading_screen_init);
}

void loadscrload_cb(lv_event_t *e)
{
    if (loading_flag == 0)
    {
        _ui_opacity_set(ui_Left1, 0);
        _ui_opacity_set(ui_Left2, 0);
        _ui_opacity_set(ui_Left3, 0);
        _ui_opacity_set(ui_Left4, 0);
        _ui_opacity_set(ui_Left5, 0);
        _ui_opacity_set(ui_Left5, 0);
        _ui_opacity_set(ui_Left6, 0);
        _ui_opacity_set(ui_Left7, 0);
        _ui_opacity_set(ui_Left8, 0);
        _ui_opacity_set(ui_Right1, 0);
        _ui_opacity_set(ui_Right8, 0);
        _ui_opacity_set(ui_Right2, 0);
        _ui_opacity_set(ui_Right3, 0);
        _ui_opacity_set(ui_Right4, 0);
        _ui_opacity_set(ui_Right5, 0);
        _ui_opacity_set(ui_Right6, 0);
        _ui_opacity_set(ui_Right7, 0);

        lv_obj_clear_flag(ui_Left1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left4, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left5, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left6, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left7, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Left8, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right4, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right5, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right6, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right7, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_Right8, LV_OBJ_FLAG_HIDDEN);

        sidelines_Animation(ui_Left1, 0);
        secondline_Animation(ui_Left2, 1000);
        loading_flag++;
    }else if(loading_flag == 1)
    {
        shorttoptobottom_Animation(ui_Left3, 0);
        shorttoptobottom_Animation(ui_Left4, 1000);
        shortbottomtotop_Animation(ui_Left8, 1500);
        shortbottomtotop_Animation(ui_Left7, 2500);
        loading_flag ++;
    }else if(loading_flag == 2)
    {
        secondline_Animation(ui_Left5, 0);
        sidelines_Animation(ui_Left6, 500);
        loading_flag ++;
    }else if(loading_flag == 3)
    {
        sidelines_Animation(ui_Right1, 0);
        secondline_Animation(ui_Right2, 1000);
        loading_flag ++;
    }else if(loading_flag == 4)
    {
        shorttoptobottom_Animation(ui_Right3, 0);
        shorttoptobottom_Animation(ui_Right4, 1000);
        shortbottomtotop_Animation(ui_Right8, 1500);
        shortbottomtotop_Animation(ui_Right7, 2500);
        loading_flag ++;
    }else if(loading_flag == 5)
    {
        secondline_Animation(ui_Right5, 0);
        sidelines_Animation(ui_Right6, 300);
        loading_flag ++;
    }
}

void virclick_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "virtc_cb");
    if(vir_load_count < 8)return;
    emoji_timer_stop();
    if(!g_dev_binded)   // if the device is not wifi-configed, then appear panel
    {
        lv_group_remove_all_objs(g_main);
        lv_obj_clear_flag(ui_virp, LV_OBJ_FLAG_HIDDEN);
        lv_group_add_obj(g_main, ui_virbtn1);
        lv_group_add_obj(g_main, ui_virbtn2);
        vir_load_count = 0;
    }else{              // else the device is wifi-configed, jump to Home page
        if(lv_scr_act() == ui_Page_Avatar)lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
    }
}

void virscrload_cb(lv_event_t *e)
{
    lv_obj_add_flag(ui_virp, LV_OBJ_FLAG_HIDDEN);
    lv_group_add_obj(g_main, ui_Page_Avatar);

    emoji_switch_scr = SCREEN_VIRTUAL;
    emoji_timer(EMOJI_GREETING);

    viewInfoInit();
    view_info_obtain_early();
    view_sleep_timer_start();
    
    if(avatar_image == NULL)avatar_image = lv_img_create(ui_Page_ViewAva);
    if(virtual_image == NULL)virtual_image = lv_img_create(ui_Page_Avatar);
    if(flag_image == NULL)flag_image = lv_img_create(ui_Page_Flag);
    if(standby_image == NULL)standby_image = lv_img_create(ui_Page_Standby);
    if(push2talk_image == NULL)push2talk_image = lv_img_create(ui_Page_Push2talk);
    if(push2talk_speak_img == NULL)push2talk_speak_img = lv_img_create(ui_Page_Push2talk);
    lv_obj_set_align(avatar_image, LV_ALIGN_CENTER);
    lv_obj_set_align(virtual_image, LV_ALIGN_CENTER);
    lv_obj_set_align(flag_image, LV_ALIGN_CENTER);
    lv_obj_set_align(standby_image, LV_ALIGN_CENTER);
    lv_obj_set_align(push2talk_image, LV_ALIGN_CENTER);
    lv_obj_set_x(push2talk_speak_img, 0);
    lv_obj_set_y(push2talk_speak_img, -48);
    lv_obj_set_align(push2talk_speak_img, LV_ALIGN_CENTER);
    lv_obj_move_background(flag_image);
    lv_obj_move_background(virtual_image);
    lv_obj_move_background(standby_image);
    lv_obj_move_background(push2talk_image);
    lv_obj_move_background(push2talk_speak_img);
}

void virscrunload_cb(lv_event_t * e)
{

}

void virb1c_cb(lv_event_t *e)
{
    lv_pm_open_page(g_main, &group_page_connectapp, PM_ADD_OBJS_TO_GROUP, &ui_Page_Connect, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Connect_screen_init);
    Page_ConnAPP_Mate();
}

void virb2c_cb(lv_event_t *e)
{
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
}

void main1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main1c_cb");
    lv_pm_open_page(g_main, &group_page_template, PM_ADD_OBJS_TO_GROUP, &ui_Page_Example, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Example_screen_init);
    lv_group_focus_obj(ui_menubtn2);
}

void main1f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 0);
    lv_label_set_text(ui_maintitle, "Task\nTemplates");
}

void main2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main2c_cb");
    if(g_taskdown == 1)
    {
        lv_pm_open_page(g_main, &group_page_notask, PM_ADD_OBJS_TO_GROUP, &ui_Page_Notask, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Notask_screen_init);
    }
    if(g_taskdown == 0)
    {
        if(g_avarlive == 0)
        {
            if(lv_scr_act() != ui_Page_ViewAva)lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
        }else if(g_avarlive == 1)
        {
            if(lv_scr_act() != ui_Page_ViewLive)lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewLive, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewLive_screen_init);
        }
    }
}

void main2f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 0);
    lv_label_set_text(ui_maintitle, "Current\nTasks");
}

void main3c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main3c_cb");
    lv_group_remove_all_objs(g_main);   
    bool is_hidden = true;
    is_hidden = lv_obj_has_flag(ui_extensionNone, LV_OBJ_FLAG_HIDDEN);
    if(!is_hidden)
    {
        _ui_screen_change(&ui_Page_Extension, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Extension_screen_init);
        lv_group_add_obj(g_main, ui_extenNoneback);
    }else{
        lv_pm_open_page(g_main, &group_page_extension, PM_ADD_OBJS_TO_GROUP, &ui_Page_Extension, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Extension_screen_init);
    }
}

void main3f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 20);
    lv_label_set_text(ui_maintitle, "Extension");
}

void main4c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "main4c_cb");
    lv_pm_open_page(g_main, &group_page_set, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Set_screen_init);
}

void main4f_cb(lv_event_t *e)
{
    lv_obj_set_y(ui_maintitle, 20);
    lv_label_set_text(ui_maintitle, "Setting");
}

void backset_cb(lv_event_t * e)
{
    // ESP_LOGI(CLICK_TAG, "backset_cb");
    lv_group_set_wrap(g_main, true);
    lv_pm_open_page(g_main, &group_page_set, PM_ADD_OBJS_TO_GROUP, &ui_Page_Set, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Set_screen_init);
}

void backmenu_cb(lv_event_t * e)
{
    // ESP_LOGI(CLICK_TAG, "backmenu_cb");
    if(lv_scr_act() == ui_Page_ModelOTA)
    {
        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, NULL, pdMS_TO_TICKS(10000));
    }else
    {
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
        lv_group_set_wrap(g_main, true);

        if(g_tasktype == 0)
        {
            if(local_task_id == 0 || local_task_id == 1 || local_task_id == 2)
            {
                g_taskdown = 0;
                esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), pdMS_TO_TICKS(10000));
            }
        }

        if(g_tasktype == 1)
        {
            esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_RESUME, NULL, NULL, pdMS_TO_TICKS(10000));
        }
    }
}

void arr1c_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "arr1c_cb");
    lv_group_focus_obj(ui_connp2);
    Page_ConnAPP_BLE();
}

void arr1f_cb(lv_event_t *e) 
{
    // ESP_LOGI(CLICK_TAG, "arr1f_cb");
    Page_ConnAPP_Mate();
}

void arr2c_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "arr2c_cb");
    lv_group_focus_obj(ui_connp1);
    Page_ConnAPP_Mate();
}

void arr2f_cb(lv_event_t *e) 
{ 
    // ESP_LOGI(CLICK_TAG, "arr2f_cb");
    Page_ConnAPP_BLE();
}

void ntaskb1c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "ntaskb1c_cb");
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_ModelOTA, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ModelOTA_screen_init);
}

void waitbc_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "waitbc_cb");
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, NULL, pdMS_TO_TICKS(10000));
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
}

void revbc_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "revbc_cb");
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, NULL, pdMS_TO_TICKS(10000));
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
}

void viewac_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "viewac_cb");
    if(g_guide_disable)
    {
        if(g_taskdown == 0)
        {
            lv_obj_clear_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN); /// Flags
            lv_obj_move_foreground(ui_viewavap);
            lv_group_remove_all_objs(g_main);
            lv_group_add_obj(g_main, ui_viewpbtn1);
            lv_group_add_obj(g_main, ui_viewpbtn2);
            lv_group_add_obj(g_main, ui_viewpbtn3);
            g_alarm_p = 1;
            g_avarlive = 0;
        }
    }
}

void viewaf_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "viewaf_cb");
    if(g_alarm_p == 0)
    {
        lv_obj_add_flag(ui_alarm_indicator, LV_OBJ_FLAG_HIDDEN);
        if(lv_scr_act() != ui_Page_ViewAva)_ui_screen_change(&ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
        g_avarlive = 0;
    }
}

void viewasl_cb(lv_event_t *e)
{
    g_avarlive = 0;
    lv_group_focus_obj(ui_Page_ViewAva);
    if(lv_scr_act() == ui_Page_ViewAva || lv_scr_act() == ui_Page_ViewLive)lv_group_set_wrap(g_main, false);
    if (emoticon_disp_id == 1)
    {
        emoji_switch_scr = SCREEN_AVATAR;   // set the emoji display page to VIEWAVATAR
        emoji_timer(EMOJI_DETECTED); // Load timer for the "detected" animation when emoticon_disp_id is 1
    }
    else
    {
        emoji_switch_scr = SCREEN_AVATAR;   // set the emoji display page to VIEWAVATAR
        emoji_timer(EMOJI_DETECTING); // Load timer for the "detecting" animation when emoticon_disp_id is 0
    }
}

void viewasul_cb(lv_event_t *e)
{
    emoji_timer_stop();
}

void viewlc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "viewlc_cb");
    if(g_guide_disable)
    {
        if(g_taskdown == 0)
        {
            lv_obj_clear_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN); /// Flags
            lv_obj_move_foreground(ui_viewavap);
            lv_group_remove_all_objs(g_main);
            lv_group_add_obj(g_main, ui_viewpbtn1);
            lv_group_add_obj(g_main, ui_viewpbtn2);
            lv_group_add_obj(g_main, ui_viewpbtn3);
            g_alarm_p = 1;
            g_avarlive = 1;
        }
    }
}

void viewlf_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "viewlf_cb");
    if(lv_scr_act() != ui_Page_ViewLive)_ui_screen_change(&ui_Page_ViewLive, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewLive_screen_init);
    g_avarlive = 1;
}

void viewlsl_cb(lv_event_t *e)
{
    g_avarlive = 1;
    lv_group_focus_obj(ui_Page_ViewLive);
    if(lv_scr_act() == ui_Page_ViewAva || lv_scr_act() == ui_Page_ViewLive)lv_group_set_wrap(g_main, false);
    if(view_alarm_status == 1)
    {
        lv_obj_clear_flag(ui_alarm_indicator, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_viewlivp2, LV_OBJ_FLAG_HIDDEN);
    }
}

void viewlsul_cb(lv_event_t *e) 
{
}

void waitT_cb(lv_event_t *e)
{
    // Your code here
}

void loctask1f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "");
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_backtomenu_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loctask1df_cb(lv_event_t *e)
{
    lv_obj_clear_flag(ui_mimgp, LV_OBJ_FLAG_HIDDEN);
}

void loctask2c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "loctask2c_cb");
    local_task_id = 2;
    g_tasktype = 0;

    if(!g_guide_disable)
    {
        _ui_screen_change(&ui_Page_Flag, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Flag_screen_init);
        lv_group_remove_all_objs(g_main);
        lv_group_add_obj(g_main, ui_guidebtn1);
        lv_group_add_obj(g_main, ui_guidebtn2);
        emoji_switch_scr = SCREEN_GUIDE;
        emoji_timer(EMOJI_DETECTING);
    }
    
    if(g_guide_disable){
        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), pdMS_TO_TICKS(10000));
        g_taskdown = 0;
        lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
    }
}

void loctask2f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "Human\nDetection");
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_human_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loctask3c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "loctask3c_cb");
    local_task_id = 1;
    g_tasktype = 0;

    if(!g_guide_disable)
    {
        _ui_screen_change(&ui_Page_Flag, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Flag_screen_init);
        lv_group_remove_all_objs(g_main);
        lv_group_add_obj(g_main, ui_guidebtn1);
        lv_group_add_obj(g_main, ui_guidebtn2);
        emoji_switch_scr = SCREEN_GUIDE;
        emoji_timer(EMOJI_DETECTING);
    }

    if(g_guide_disable){
        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), pdMS_TO_TICKS(10000));
        g_taskdown = 0;
        lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
    }  
}

void loctask3f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "Pet\nDetection");
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_dog_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void loctask4c_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "loctask4c_cb");
    local_task_id = 0;
    g_tasktype = 0;

    if(!g_guide_disable)
    {
        _ui_screen_change(&ui_Page_Flag, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Flag_screen_init);
        lv_group_remove_all_objs(g_main);
        lv_group_add_obj(g_main, ui_guidebtn1);
        lv_group_add_obj(g_main, ui_guidebtn2);
        emoji_switch_scr = SCREEN_GUIDE;
        emoji_timer(EMOJI_DETECTING);
    }

    if(g_guide_disable){
        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), pdMS_TO_TICKS(10000));
        g_taskdown = 0;
        lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
    } 
}

void loctask4f_cb(lv_event_t *e)
{
    lv_label_set_text(ui_Label1, "Gesture\nDetection");
    lv_obj_set_style_bg_img_src(ui_mimgp, &ui_img_gesture_d_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void sgesup_cb(lv_event_t *e)
{
    lv_group_focus_next(g_main);
}

void sgesdown_cb(lv_event_t *e)
{
    lv_group_focus_prev(g_main);
}

void sclick_cb(lv_event_t *e)
{
    lv_obj_t *focused_obj = lv_group_get_focused(g_main);
    lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void setsl_cb(lv_event_t * e)
{
    // esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_INFO_OBTAIN, NULL, 0, pdMS_TO_TICKS(10000));
}

void maingestureup_cb(lv_event_t *e)
{
    lv_group_focus_next(g_main);
}

void maingesturedown_cb(lv_event_t *e)
{
    lv_group_focus_prev(g_main);
}

void vieback_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "vieback_cb");
    lv_obj_add_flag(ui_viewlivp2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_alarm_indicator, LV_OBJ_FLAG_HIDDEN);

    g_taskdown = 0;
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_ALARM_OFF, &g_taskdown, sizeof(uint8_t), pdMS_TO_TICKS(10000));
}

void livgc_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "livgc_cb");
}

void lgesleft_cb(lv_event_t *e)
{
    lv_group_focus_next(g_main);
}

void lgesright_cb(lv_event_t *e)
{
    lv_group_focus_prev(g_main);
}

void mainclick_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "mainclick_cb");
    lv_obj_t *focused_obj = lv_group_get_focused(g_main);
    lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void lclick_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "lclick_cb");
    lv_obj_t *focused_obj = lv_group_get_focused(g_main);
    lv_event_send(focused_obj, LV_EVENT_CLICKED, NULL);
}

void lunlds_cb(lv_event_t *e) { }

void lunlded_cb(lv_event_t *e) { }

void custb1c_cb(lv_event_t *e) { }

void custb1f_cb(lv_event_t *e) { }

void custb1df_cb(lv_event_t *e) { }

void custb2c_cb(lv_event_t *e) { }

void custb2f_cb(lv_event_t *e) { }

void custb2df_cb(lv_event_t *e) { }

void custb3c_cb(lv_event_t *e) { }

void custb3f_cb(lv_event_t *e) { }

void custb3df_cb(lv_event_t *e) { }

void setbackf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setback, ui_setbackt);
    lv_obj_set_width(ui_setback, 300);
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN);
}

void setbackdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setback, ui_setbackt);
    lv_obj_set_width(ui_setback, 300);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN);
}

void setdevf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setdev, ui_setdevt);
}

void setdevdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setdev, ui_setdevt);
}

void setwifif_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setwifi, ui_setwifit);
}

void setwifidf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setwifi, ui_setwifit);
}

void setrgbf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setrgb, ui_setrgbt);
    lv_obj_clear_flag(ui_setrgbsw, LV_OBJ_FLAG_HIDDEN);
}

void setrgbdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setrgb, ui_setrgbt);
    lv_obj_add_flag(ui_setrgbsw, LV_OBJ_FLAG_HIDDEN);
}

void setdownf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setdown, ui_setdownt);
}

void setdowndf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setdown, ui_setdownt);
}

void setblef_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setble, ui_setblet);
    lv_obj_clear_flag(ui_setblesw, LV_OBJ_FLAG_HIDDEN);
}

void setbledf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setble, ui_setblet);
    lv_obj_add_flag(ui_setblesw, LV_OBJ_FLAG_HIDDEN);
}

void setvolc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setvolc_cb");
    lv_label_set_text(ui_bvtitle, "Sound");
    lv_label_set_text(ui_bvbt, "Volume");
    lv_img_set_src(ui_bvbimg, &ui_img_volicon_png);
    lv_obj_add_flag(ui_bp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_vp, LV_OBJ_FLAG_HIDDEN);

    lv_pm_open_page(g_main, &group_page_volume, PM_ADD_OBJS_TO_GROUP, &ui_Page_Slider, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Slider_screen_init);
    lv_event_send(ui_vslider, LV_EVENT_VALUE_CHANGED, NULL);
}

void setvolf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setvol, ui_setvolt);
}

void setvoldf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setvol, ui_setvolt);
}

void setbric_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setbric_cb");
    lv_label_set_text(ui_bvtitle, "Display");
    lv_label_set_text(ui_bvbt, "Brightness");
    lv_img_set_src(ui_bvbimg, &ui_img_brighticon_png);
    lv_obj_clear_flag(ui_bp, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_vp, LV_OBJ_FLAG_HIDDEN);

    lv_pm_open_page(g_main, &group_page_brightness, PM_ADD_OBJS_TO_GROUP, &ui_Page_Slider, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Slider_screen_init);
    lv_event_send(ui_bslider, LV_EVENT_VALUE_CHANGED, NULL);
}

void setbrif_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setbri, ui_setbrit);
}

void setbridf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setbri, ui_setbrit);
}

void setwwf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setww, ui_setwwt);
    lv_obj_clear_flag(ui_setwwsw, LV_OBJ_FLAG_HIDDEN);
}

void setwwdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setww, ui_setwwt);
    lv_obj_add_flag(ui_setwwsw, LV_OBJ_FLAG_HIDDEN);
}

void settimec_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "settimec_cb");
    lv_pm_open_page(g_main, &group_page_sleep, PM_ADD_OBJS_TO_GROUP, &ui_Page_Sleep, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Sleep_screen_init);
    lv_roller_set_selected(ui_sleeptimeroller, g_screenoff_time, LV_ANIM_OFF);
}

void settimef_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_settime, ui_settimt);
}

void settimedf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_settime, ui_settimt);
}

void setfacf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setfac, ui_setfact);
}

void setfacdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setfac, ui_setfact);
}

void abdnf_cb(lv_event_t *e) { }

void abdndf_cb(lv_event_t *e) { }

void absvf_cb(lv_event_t *e) { }

void absvdf_cb(lv_event_t *e) { }

void absnf_cb(lv_event_t *e) { }

void absndf_cb(lv_event_t *e) { }

void abeuif_cb(lv_event_t *e) { }

void abeuidf_cb(lv_event_t *e) { }

void abblef_cb(lv_event_t *e) { }

void abbledf_cb(lv_event_t *e) { }

void setdevc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setdevc_cb");
    lv_pm_open_page(g_main, &group_page_about, PM_ADD_OBJS_TO_GROUP, &ui_Page_About, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_About_screen_init);
    lv_group_focus_obj(ui_aboutdevname);
    lv_group_set_wrap(g_main, false);
}

void setwific_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setwific_cb");
    current_wifi_get(&wifi_record);

    static char ssid_string[34];
    if (strlen((const char *)wifi_record.ssid) < 1) {
        strncpy(ssid_string, "None", sizeof(ssid_string) - 1);
    } else {
        strncpy(ssid_string, (const char *)wifi_record.ssid, sizeof(ssid_string) - 1);
    }
    ssid_string[sizeof(ssid_string) - 1] = '\0';
    lv_label_set_text(ui_wifissid, ssid_string);
    // binded
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Network, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Network_screen_init);
    lv_group_remove_all_objs(g_main);
    lv_group_add_obj(g_main, ui_wificancel);

    lv_obj_clear_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_move_foreground(ui_wifiicon);

    lv_obj_add_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
}

void setblec_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setblec_cb");

    if (lv_obj_has_state(ui_setblesw, LV_STATE_DISABLED)) {
        ESP_LOGI(TAG, "ui_setblesw is disabled, skipping action");
        return;
    }

    static int btn_state;
    btn_state = (get_ble_switch(UI_CALLER));
    switch (btn_state)
    {
        case 0:
            ESP_LOGI(TAG, "ble_btn_status: on");
            set_ble_switch(UI_CALLER, 1);
            lv_obj_add_state(ui_setblesw, LV_STATE_CHECKED);
            lv_obj_add_state(ui_setblesw, LV_STATE_DISABLED);
            view_ble_switch_timer_start();
            break;
        case 1:
            ESP_LOGI(TAG, "ble_btn_status: off");
            set_ble_switch(UI_CALLER, 0);
            lv_obj_clear_state(ui_setblesw, LV_STATE_CHECKED);
            lv_obj_add_state(ui_setblesw, LV_STATE_DISABLED);
            view_ble_switch_timer_start();
            break;

        default:
            break;
    }
}

void setrgbc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setrgbc_cb");
    static int btn_state;
    btn_state = (get_rgb_switch(UI_CALLER));
    switch (btn_state)
    {
        case 0:
            ESP_LOGI(TAG, "rgb_switch: on");
            set_rgb_switch(UI_CALLER, 1);
            lv_obj_add_state(ui_setrgbsw, LV_STATE_CHECKED);
            break;
        case 1:
            ESP_LOGI(TAG, "rgb_switch: off");
            set_rgb_switch(UI_CALLER, 0);
            lv_obj_clear_state(ui_setrgbsw, LV_STATE_CHECKED);
            break;

        default:
            break;
    }
}

void setwwc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setwwc_cb");
    static lv_state_t btn_state;
    btn_state = lv_obj_get_state(ui_setwwsw);
    switch (btn_state)
    {
        case 0:
            lv_obj_add_state(ui_setwwsw, LV_STATE_CHECKED);

            break;
        case 1:
            lv_obj_clear_state(ui_setwwsw, LV_STATE_CHECKED);

            break;

        default:
            break;
    }
}

void setdownc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setdownc_cb");
    g_swipeid = 0;
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Swipe, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Swipe_screen_init);
    lv_slider_set_value(ui_spsilder, 0, LV_ANIM_ON);
    Page_shutdown();
    lv_group_add_obj(g_main, ui_spback);
}

void setfac_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setfac_cb");
    g_swipeid = 1;
    lv_pm_open_page(g_main, NULL, PM_CLEAR_GROUP, &ui_Page_Swipe, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Swipe_screen_init);
    lv_slider_set_value(ui_spsilder, 0, LV_ANIM_ON);
    Page_facreset();
    lv_group_add_obj(g_main, ui_spback);
}

void setappf_cb(lv_event_t *e)
{
    set_obj_style_focused(ui_setapp, ui_setappt);
}

void setappdf_cb(lv_event_t *e)
{
    set_obj_style_defocused(ui_setapp, ui_setappt);
}

void setappc_cb(lv_event_t *e)
{
    ESP_LOGI(CLICK_TAG, "setappc_cb");
    lv_pm_open_page(g_main, &group_page_connectapp, PM_ADD_OBJS_TO_GROUP, &ui_Page_Connect, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Connect_screen_init);
    lv_group_focus_obj(ui_connp1);
}

void slidervc_cb(lv_event_t *e)
{
    static int32_t slider_value;
    slider_value = lv_slider_get_value(ui_spsilder);
    if (slider_value > 80)
    {
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xFF5656), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    }
    else
    {
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_spsilder, lv_color_hex(0xD47C2A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    }
}

void sliderr_cb(lv_event_t *e)
{
    static int32_t slider_value;
    slider_value = lv_slider_get_value(ui_spsilder);
    if (slider_value > 80)
    {
        switch (g_swipeid)
        {
            case 0:
                if (g_shutdown == 0)
                {
                    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_REBOOT, NULL, 0, pdMS_TO_TICKS(10000));
                }
                if (g_shutdown == 1)
                {
                    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_SHUTDOWN, NULL, 0, pdMS_TO_TICKS(10000));
                }
                break;

            case 1:
                lv_obj_clear_flag(ui_swipep2, LV_OBJ_FLAG_HIDDEN);
                set_reset_factory(false);
                break;

            default:
                break;
        }
    }
    if(slider_value <=80)
    {
        lv_slider_set_value(ui_spsilder, 0, LV_ANIM_OFF);
    }
}

void otaback_cb(lv_event_t * e)
{
    ESP_LOGI(CLICK_TAG, "otaback_cb");
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
}

void sleeptimeset_cb(lv_event_t * e)
{
    static uint16_t sleep_time_roller_id;
    lv_obj_t * obj = lv_event_get_target(e);
    sleep_time_roller_id = lv_roller_get_selected(obj);
    set_screenoff_time(UI_CALLER, sleep_time_roller_id);
    g_screenoff_time = get_screenoff_time(UI_CALLER);
    // ESP_LOGI(TAG, "roller selected obj's id: %d", sleep_time_roller_id);
}

void setsleepsw_cb(lv_event_t * e)
{
    // ESP_LOGI(CLICK_TAG, "setsleepsw_cb");
    lv_event_send(ui_sleepswitch, LV_EVENT_CLICKED, NULL);
}

void sleepswitch_cb(lv_event_t * e)
{
    ESP_LOGI(CLICK_TAG, "sleepswitch_cb");
    static int btn_state;
    btn_state = (get_screenoff_switch(UI_CALLER));
    switch (btn_state)
    {
        case 0:
            ESP_LOGI(TAG, "sleep_switch: on");
            set_screenoff_switch(UI_CALLER, 1);
            lv_obj_add_state(ui_sleepswitch, LV_STATE_CHECKED);
            g_screenoff_switch = get_screenoff_switch(UI_CALLER);
            break;
        case 1:
            ESP_LOGI(TAG, "sleep_switch: off");
            set_screenoff_switch(UI_CALLER, 0);
            lv_obj_clear_state(ui_sleepswitch, LV_STATE_CHECKED);
            g_screenoff_switch = get_screenoff_switch(UI_CALLER);
            break;

        default:
            break;
    }
}

void p2tclick_cb(lv_event_t * e)
{
    if(g_push2talk_status == EMOJI_SPEAKING || g_push2talk_status == EMOJI_ANALYZING){
        app_rgb_set(SR, RGB_BLINK_BLUE);
        lv_arc_set_value(ui_push2talkarc, 0);

        g_push2talk_timer = 1;
        view_push2talk_timer_start();

        lv_obj_clear_flag(ui_push2talkpanel2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_push2talkpanel3, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_p2texit, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(push2talk_textarea, LV_OBJ_FLAG_HIDDEN);

        lv_group_remove_all_objs(g_main);
        lv_group_add_obj(g_main, ui_push2talkarc);

        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_VI_STOP, NULL, NULL, pdMS_TO_TICKS(10000));
        view_push2talk_animation_timer_stop();
    }
}

void push2talkcancel_cb(lv_event_t * e)
{
    ESP_LOGI(CLICK_TAG, "push2talkcancel_cb");
    static int push2talk_direct_exit = 0;
    if(g_taskflow_pause == 1)
    {
        lv_label_set_text(ui_revtext, "Resuming \nTask...");
        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE,  \
                                    VIEW_EVENT_TASK_FLOW_START_CURRENT_TASK, NULL, 0, portMAX_DELAY);
    }else{
        lv_label_set_text(ui_revtext, "Receiving \nTask...");
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
    }
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_VI_EXIT, &push2talk_direct_exit, sizeof(push2talk_direct_exit), pdMS_TO_TICKS(10000));

    g_taskflow_pause = 0;
    g_is_push2talk = 0;
}

void push2talkcheck_cb(lv_event_t * e)
{
    ESP_LOGI(CLICK_TAG, "push2talkcheck_cb");
    static int push2talk_newtask_exit = 1;
    lv_label_set_text(ui_revtext, "Receiving \nTask...");
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_VI_EXIT, &push2talk_newtask_exit, sizeof(push2talk_newtask_exit), pdMS_TO_TICKS(10000));
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE,  \
                                    VIEW_EVENT_TASK_FLOW_START_CURRENT_TASK, NULL, 0, portMAX_DELAY);

    g_taskflow_pause = 0;
    g_is_push2talk = 0;
}

void p2tvaluechange_cb(lv_event_t * e)
{
    ESP_LOGI(TAG, "p2tvaluechange_cb");
    lv_obj_t * arc = lv_event_get_target(e);
    lv_obj_t * knob = lv_event_get_user_data(e);
    uint16_t angle = get_angle(arc);
    lv_coord_t x = lv_obj_get_x(knob);
    lv_coord_t y = lv_obj_get_y(knob);
    // ESP_LOGI(TAG, "Object coordinates: x = %d, y = %d", x, y);
    lv_arc_align_obj_to_angle(arc, knob, 0);
    // ESP_LOGI(TAG, "arc angle: %d", angle);
    lv_img_set_angle(knob, angle * 10 + 900);

    static int push2talk_direct_exit = 0;
    static int16_t push2talk_arc;
    push2talk_arc = lv_arc_get_value(ui_push2talkarc);
    // ESP_LOGI(TAG, "push2talk_arc =  %d", push2talk_arc);
    if(push2talk_arc == 10)
    {
        view_push2talk_timer_stop();
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
        lv_group_set_editing(g_main, false);

        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_VI_EXIT, &push2talk_direct_exit, sizeof(push2talk_direct_exit), pdMS_TO_TICKS(10000));

        if(g_taskflow_pause == 1)
        {
            esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE,  \
                            VIEW_EVENT_TASK_FLOW_START_CURRENT_TASK, NULL, 0, pdMS_TO_TICKS(10000));
            lv_label_set_text(ui_revtext, "Resuming \nTask...");
        }
        else{
            lv_label_set_text(ui_revtext, "Receiving \nTask...");
        }

        g_taskflow_pause = 0;
        g_is_push2talk = 0;
        app_rgb_set(SR, RGB_OFF);
    }
}

void p2tfocus_cb(lv_event_t * e)
{
    lv_group_set_editing(g_main, true);
}

void volvc_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "volvc_cb");
    volbri.vs_value = lv_slider_get_value(ui_vslider);

    static char vs_buffer[10];
    lv_snprintf(vs_buffer, sizeof(vs_buffer), "%" PRId32, volbri.vs_value);
    lv_label_set_text(ui_bvbv, vs_buffer);
}

void volre_cb(lv_event_t *e)
{
    // write volume value into nvs and post event
    set_sound(UI_CALLER, volbri.vs_value);
}

void volfs_cb(lv_event_t * e)
{
    lv_obj_set_style_border_color(ui_vp, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bvback, lv_color_hex(0x8FC31F), LV_PART_MAIN | LV_STATE_FOCUSED);
}

void voldf_cb(lv_event_t * e)
{
    lv_obj_set_style_border_color(ui_vp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
}

void brivc_cb(lv_event_t *e)
{
    // ESP_LOGI(CLICK_TAG, "brivc_cb");
    volbri.bs_value = lv_slider_get_value(ui_bslider);

    static char bs_buffer[10];
    lv_snprintf(bs_buffer, sizeof(bs_buffer), "%" PRId32, volbri.bs_value);
    lv_label_set_text(ui_bvbv, bs_buffer);
}

void brire_cb(lv_event_t *e)
{
    set_brightness(UI_CALLER, volbri.bs_value);
}

void brifs_cb(lv_event_t * e)
{
    lv_obj_set_style_border_color(ui_bp, lv_color_hex(0x1F6DC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bvback, lv_color_hex(0x1F6DC3), LV_PART_MAIN | LV_STATE_FOCUSED);
}

void bridf_cb(lv_event_t * e)
{
    lv_obj_set_style_border_color(ui_bp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
}

void hap_cb(lv_event_t *e)
{
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
}

void pageguideavaf_cb(lv_event_t * e)
{
    if(g_guide_step == 2)
    {
        _ui_screen_change(&ui_Page_Guideavatar, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Guideavatar_screen_init);
    }
}

void pageguideavascrload_cb(lv_event_t * e)
{
    if(g_guide_step == 0){
        lv_obj_add_flag(ui_guide1p1, LV_OBJ_FLAG_CLICKABLE);
        lv_group_remove_all_objs(g_main);
        lv_group_add_obj(g_main, ui_Page_Guideavatar);
        lv_group_add_obj(g_main, ui_Page_Guidelive);
        lv_group_add_obj(g_main, ui_guide1p1);

        lv_group_focus_obj(ui_guide1p1);
        lv_group_focus_freeze(g_main, true);
        lv_group_set_wrap(g_main, false);
    }
}

void guideavaclick_cb(lv_event_t * e)
{
    if(g_guide_step == 0)
    {
        g_guide_step = 1;

        lv_obj_add_flag(ui_guide1t1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_guide1p1, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_clear_flag(ui_guide1p2, LV_OBJ_FLAG_HIDDEN);

        lv_group_focus_freeze(g_main, false);
        lv_group_focus_obj(ui_Page_Guideavatar);
        lv_group_remove_obj(ui_guide1p1);
    }
}

void guide2avaclick_cb(lv_event_t * e)
{
    if(g_guide_step == 2)
    {
        g_guide_step = 3;
        lv_obj_add_flag(ui_guide1p2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_guide1p3, LV_OBJ_FLAG_HIDDEN);
        lv_group_remove_all_objs(g_main);
        lv_group_add_obj(g_main, ui_guide1btn1);
        lv_group_add_obj(g_main, ui_guide1btn2);
        lv_group_add_obj(g_main, ui_guide1btn3);

        set_usage_guide(UI_CALLER, 1);
        g_guide_disable = get_usage_guide(UI_CALLER);
        lv_group_set_wrap(g_main, true);
    }
}

void emoticonback_cb(lv_event_t * e)
{
    g_group_layer_ = 0;
    lv_obj_add_flag(ui_Page_Emoji, LV_OBJ_FLAG_HIDDEN);
    lv_group_remove_obj(ui_emoticonok);
    lv_group_focus_freeze(g_main, false);
    lv_group_focus_obj(pre_foucsed_obj);
}

void flagloaded_cb(lv_event_t * e)
{
    intmax_t tlid = 0;
    tf_engine_tid_get(&tlid);
    // if task is preview, do not send task_flow_pause
    if(tlid != 4)esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_PAUSE, NULL, NULL, pdMS_TO_TICKS(10000));
}

void guidebtn1click_cb(lv_event_t * e)
{
    lv_pm_open_page(g_main, &group_page_guide, PM_ADD_OBJS_TO_GROUP, &ui_Page_Guideavatar, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Guideavatar_screen_init);
}

void guidebtn2click_cb(lv_event_t * e)
{
    set_usage_guide(UI_CALLER, 1);
    g_guide_disable = get_usage_guide(UI_CALLER);

    if(g_tasktype == 0)
    {
        if(local_task_id == 0 || local_task_id == 1 || local_task_id == 2)
        {
            g_taskdown = 0;
            esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), pdMS_TO_TICKS(10000));
            lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
        }
    }

    if(g_tasktype == 1)
    {
        g_taskdown = 0;
        if(lv_scr_act() != ui_Page_ViewAva)lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
    }
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_RESUME, NULL, NULL, pdMS_TO_TICKS(10000));
}

void guide1btn2c_cb(lv_event_t * e)
{
    ESP_LOGI(CLICK_TAG, "guide1btn2c_cb");
    Task_end();
}

void guide1btn3c_cb(lv_event_t * e)
{
    if(g_tasktype == 0)
    {
        if(local_task_id == 0 || local_task_id == 1 || local_task_id == 2)
        {
            g_taskdown = 0;
            esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_START_BY_LOCAL, &local_task_id, sizeof(local_task_id), pdMS_TO_TICKS(10000));
            lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
        }
    }

    if(g_tasktype == 1)
    {
        g_taskdown = 0;
        if(lv_scr_act() != ui_Page_ViewAva)lv_pm_open_page(g_main, &group_page_view, PM_ADD_OBJS_TO_GROUP, &ui_Page_ViewAva, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_ViewAva_screen_init);
        esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_RESUME, NULL, NULL, pdMS_TO_TICKS(10000));
    }
}

void pageguidelivef_cb(lv_event_t * e)
{
    if(g_guide_step == 1)
    {
        _ui_screen_change(&ui_Page_Guidelive, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Guidelive_screen_init);
        lv_obj_add_flag(ui_guide2p1, LV_OBJ_FLAG_CLICKABLE);

        lv_group_add_obj(g_main, ui_guide2p1);
        lv_group_focus_obj(ui_guide2p1);
        lv_group_focus_freeze(g_main, true);
    }
}

void pageguidelivescrload_cb(lv_event_t * e)
{

}

void guideliveclick_cb(lv_event_t * e)
{
    g_guide_step = 2;

    lv_img_set_src(ui_guide1img2, &ui_img_onboardclick_png);
    lv_label_set_text(ui_guide1t2, "Click to manage task");
    lv_obj_add_flag(ui_guide1p2, LV_OBJ_FLAG_CLICKABLE);

    lv_obj_add_flag(ui_guide2t1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_guide2p1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_guide2p2, LV_OBJ_FLAG_HIDDEN);

    lv_group_focus_freeze(g_main, false);
    lv_group_remove_obj(ui_guide2p1);
    lv_group_focus_obj(ui_Page_Guidelive);
}

void guide2liveclick_cb(lv_event_t * e)
{

}

void taskerrc_cb(lv_event_t *e)
{
    lv_obj_add_flag(ui_task_error, LV_OBJ_FLAG_HIDDEN);
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, 0, portMAX_DELAY);
}
/* Page device bundle
 *
 */
void ConnAPP_QR_Init()
{
    static lv_color_t bg_color;
    bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
    static lv_color_t fg_color;
    fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);

    qr = lv_qrcode_create(ui_conn_QR, 150, fg_color, bg_color);
}

static void Page_ConnAPP_Mate()
{
    lv_arc_set_value(ui_conn_arcr, 0);
    lv_obj_clear_flag(ui_conn_panel1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_add_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN);   /// Flags
    lv_obj_clear_flag(ui_arrow1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_arrow2, LV_OBJ_FLAG_HIDDEN);

    static const char *data = "https://sensecraft-app-download.seeed.cc";
    lv_qrcode_update(qr, data, strlen(data));
    lv_obj_center(qr);
}

static void Page_ConnAPP_BLE()
{
    lv_arc_set_value(ui_conn_arcr, 100);
    lv_obj_add_flag(ui_conn_panel1, LV_OBJ_FLAG_HIDDEN);   /// Flags
    lv_obj_clear_flag(ui_conn_panel2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_add_flag(ui_arrow1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_arrow2, LV_OBJ_FLAG_HIDDEN);

    if (qrcode_content && strlen(qrcode_content) > 16) {
        lv_qrcode_update(qr, qrcode_content, strlen(qrcode_content));
    } else {
        lv_qrcode_update(qr, "NULL", 4);  // just in case
    }
    lv_obj_center(qr);
}

static void Task_end()
{
    g_taskdown = 1;
    g_alarm_p = 0;
    local_task_id = 4;
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_ALARM_OFF, &g_taskdown, sizeof(uint8_t), pdMS_TO_TICKS(10000));
    esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_TASK_FLOW_STOP, NULL, NULL, pdMS_TO_TICKS(10000));

    lv_obj_add_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN); /// Flags
}

static void Page_shutdown()
{
    if (g_shutdown == 1)
    {
        lv_label_set_text(ui_sptitle, "Shut down");
        lv_label_set_text(ui_sptext, "Swipe to shut down");
    }
    else if (g_shutdown == 0)
    {
        lv_label_set_text(ui_sptitle, "Reboot");
        lv_label_set_text(ui_sptext, "Swipe to reboot");
    }
}

static void Page_facreset()
{
    lv_label_set_text(ui_sptitle, "Factory reset");
    lv_label_set_text(ui_sptext, "Swipe to reset");
}

// device bind config status
void waitForWifi()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_wifi_3_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Waiting for Wi-Fi Setup...");
}

void waitForBinding()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_wifi_3_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Waiting for binding...");
}

void waitForAddDev()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_wifi_3_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Binding device to your account");
}

void bindFinish()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_wifiok_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Watcher is ready");
}

void wifiConnectFailed()
{
    lv_obj_add_flag(ui_wifip1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_wifitext2, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_wifilogo, &ui_img_error_png);
    lv_obj_clear_flag(ui_wifip3, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_wifitext3, "Wi-Fi Connection Failed");
}

uint8_t* retry_get_data(uint8_t* (*func)(int), int caller, int retries) {
    uint8_t *data = NULL;
    for (int i = 0; i < retries; ++i) {
        data = func(caller);
        if (data != NULL) {
            break;
        }
    }
    return data;
}

void viewInfoInit()
{
    lv_slider_set_range(ui_bslider, 1, 100);
    lv_obj_add_state(ui_setblesw, LV_STATE_CHECKED);
    ConnAPP_QR_Init();
}

static void view_info_obtain_early()
{
    g_guide_disable = retry_get_data((uint8_t* (*)(int))get_usage_guide, UI_CALLER, MAX_RETRIES);
    qrcode_content = (char *)retry_get_data((uint8_t* (*)(int))get_qrcode_content, UI_CALLER, MAX_RETRIES);
}

void view_info_obtain()
{
    ESP_LOGI(TAG, "settingInfoInit");
    retry_get_data((uint8_t* (*)(int))get_brightness, UI_CALLER, MAX_RETRIES);
    retry_get_data((uint8_t* (*)(int))get_sound, UI_CALLER, MAX_RETRIES);
    const uint8_t *rgb_switch = retry_get_data((uint8_t* (*)(int))get_rgb_switch, UI_CALLER, MAX_RETRIES);
    const uint8_t *ble_switch = retry_get_data((uint8_t* (*)(int))get_ble_switch, UI_CALLER, MAX_RETRIES);
    g_screenoff_time = (int *)retry_get_data(get_screenoff_time, UI_CALLER, MAX_RETRIES);
    g_screenoff_switch = (int *)retry_get_data(get_screenoff_switch, UI_CALLER, MAX_RETRIES);

    if(rgb_switch)
    {
        lv_obj_add_state(ui_setrgbsw, LV_STATE_CHECKED);
    }else{
        lv_obj_clear_state(ui_setrgbsw, LV_STATE_CHECKED);
    }

    if(ble_switch)
    {
        lv_obj_add_state(ui_setblesw, LV_STATE_CHECKED);
    }else{
        lv_obj_clear_state(ui_setblesw, LV_STATE_CHECKED);
    }

    if(g_screenoff_switch)
    {
        lv_obj_add_state(ui_sleepswitch, LV_STATE_CHECKED);
    }else{
        lv_obj_clear_state(ui_sleepswitch, LV_STATE_CHECKED);
    }

    // Update SN、EUI、BTMAC、WIFIMAC、ESP_VERSION、AI_VERSION  to about device page
    static char about_sn[20];
    static char about_eui[40];
    static char about_btmac[20];
    static char about_wifimac[20];
    static char about_sw_version[20];
    static char about_himax_version[20];

    const uint8_t *sn_code = retry_get_data(get_sn, UI_CALLER, MAX_RETRIES);
    const uint8_t *eui_code = retry_get_data(get_eui, 0, MAX_RETRIES);
    const uint8_t *bt_mac = retry_get_data(get_bt_mac, 0, MAX_RETRIES);
    const uint8_t *wifi_mac = retry_get_data(get_wifi_mac, 0, MAX_RETRIES);
    const char *sw_version = (char *)retry_get_data((uint8_t* (*)(int))get_software_version, UI_CALLER, MAX_RETRIES);
    const char *himax_version = (char *)retry_get_data((uint8_t* (*)(int))get_himax_software_version, UI_CALLER, MAX_RETRIES);

    if (sn_code != NULL) {
        snprintf(about_sn, sizeof(about_sn), "%02X%02X%02X%02X%02X%02X%02X%02X%02X", sn_code[0], sn_code[1], sn_code[2], sn_code[3], sn_code[4], sn_code[5], sn_code[6], sn_code[7], sn_code[8]);
    } else {
        snprintf(about_sn, sizeof(about_sn), "N/A");
    }

    if (eui_code != NULL) {
        snprintf(about_eui, sizeof(about_eui), "%02X%02X%02X%02X%02X%02X%02X%02X", eui_code[0], eui_code[1], eui_code[2], eui_code[3], eui_code[4], eui_code[5], eui_code[6], eui_code[7]);
    } else {
        snprintf(about_eui, sizeof(about_eui), "N/A");
    }

    if (bt_mac != NULL) {
        snprintf(about_btmac, sizeof(about_btmac), "%02X:%02X:%02X:%02X:%02X:%02X", bt_mac[0], bt_mac[1], bt_mac[2], bt_mac[3], bt_mac[4], bt_mac[5]);
    } else {
        snprintf(about_btmac, sizeof(about_btmac), "N/A");
    }

    if (wifi_mac != NULL) {
        snprintf(about_wifimac, sizeof(about_wifimac), "%02X:%02X:%02X:%02X:%02X:%02X", wifi_mac[0], wifi_mac[1], wifi_mac[2], wifi_mac[3], wifi_mac[4], wifi_mac[5]);
    } else {
        snprintf(about_wifimac, sizeof(about_wifimac), "N/A");
    }

    if (sw_version != NULL) {
        snprintf(about_sw_version, sizeof(about_sw_version), "%s", sw_version);
    } else {
        snprintf(about_sw_version, sizeof(about_sw_version), "N/A");
    }

    if (himax_version != NULL) {
        snprintf(about_himax_version, sizeof(about_himax_version), "%s", himax_version);
    } else {
        snprintf(about_himax_version, sizeof(about_himax_version), "N/A");
    }

    lv_label_set_text(ui_aiversion2, about_himax_version);
    lv_label_set_text(ui_espversiont2, about_sw_version);
    lv_label_set_text(ui_snt2, (char *)about_sn);
    lv_label_set_text(ui_euit2, (char *)about_eui);
    lv_label_set_text(ui_blet2, (char *)about_btmac);
    lv_label_set_text(ui_wifit2, about_wifimac);
}

void viewp1c_cb(lv_event_t *e)
{
    g_alarm_p = 0;
    lv_obj_add_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_alarm_indicator, LV_OBJ_FLAG_HIDDEN);
    lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
    lv_group_set_wrap(g_main, true);
}

void viewp2c_cb(lv_event_t *e)
{
    Task_end();
}

void viewp3c_cb(lv_event_t *e)
{
    lv_obj_add_flag(ui_viewavap, LV_OBJ_FLAG_HIDDEN);
    lv_group_remove_all_objs(g_main);
    lv_group_add_obj(g_main, ui_Page_ViewAva);
    lv_group_add_obj(g_main, ui_Page_ViewLive);
    g_alarm_p = 0;
    if(lv_scr_act() == ui_Page_ViewAva)lv_group_focus_obj(ui_Page_ViewAva);
    if(lv_scr_act() == ui_Page_ViewLive)lv_group_focus_obj(ui_Page_ViewLive);
}

void ui_event_alarm_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        if(target == ui_viewpbtn1)
        {
            viewp1c_cb(e);
        }else if (target == ui_viewpbtn2)
        {
            viewp2c_cb(e);
        }else if (target == ui_viewpbtn3)
        {
            viewp3c_cb(e);
        }
    }
    if(event_code == LV_EVENT_FOCUSED) {
        if(target == ui_viewpbtn1)
        {
            lv_obj_set_style_border_color(ui_viewpbtn1, lv_color_hex(0x1F6DC3), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_viewpbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_viewpbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

            lv_obj_set_style_border_opa(ui_viewpbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(ui_viewpbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(ui_viewpbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        }else if (target == ui_viewpbtn2)
        {
            lv_obj_set_style_border_color(ui_viewpbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_viewpbtn2, lv_color_hex(0x1F6DC3), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_viewpbtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

            lv_obj_set_style_border_opa(ui_viewpbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(ui_viewpbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(ui_viewpbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        }else if (target == ui_viewpbtn3)
        {
            lv_obj_set_style_border_color(ui_viewpbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_viewpbtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_viewpbtn3, lv_color_hex(0x1F6DC3), LV_PART_MAIN | LV_STATE_DEFAULT);

            lv_obj_set_style_border_opa(ui_viewpbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(ui_viewpbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(ui_viewpbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
    }
}

void ui_event_emoticonok(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        emoticonback_cb(e);
    }
}

/*----------------------------------------------extension sensor------------------------------------------------------*/
void view_sensor_data_update(const char *data1, const char *data2, const char *data3, const char *data4) 
{
    strncpy(sensor_data_1, data1, sizeof(sensor_data_1) - 1);
    sensor_data_1[sizeof(sensor_data_1) - 1] = '\0';

    strncpy(sensor_data_2, data2, sizeof(sensor_data_2) - 1);
    sensor_data_2[sizeof(sensor_data_2) - 1] = '\0';

    strncpy(sensor_data_3, data3, sizeof(sensor_data_3) - 1);
    sensor_data_3[sizeof(sensor_data_3) - 1] = '\0';

    strncpy(sensor_data_4, data4, sizeof(sensor_data_4) - 1);
    sensor_data_4[sizeof(sensor_data_4) - 1] = '\0';

    // ESP_LOGI(TAG, "text1: %s, text2: %s, text3: %s, text4: %s", sensor_data_1, sensor_data_2, sensor_data_3, sensor_data_4);
    sensor_date_update();
}


void sensor_date_update()
{
    switch(bubble_position[EXTENSION_TEMP])
    {
        case 0:{
            lv_label_set_text(ui_extensionbubble1Value, sensor_data_1);
            lv_label_set_text(ui_extensionbubble1Unit, "°C");
            lv_img_set_src(ui_extensionbubble1Icon, &ui_img_2057255035);
            lv_obj_add_flag(ui_extensionbubble1Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 1:{
            lv_label_set_text(ui_extensionbubble2Value, sensor_data_1);
            lv_label_set_text(ui_extensionbubble2Unit, "°C");
            lv_img_set_src(ui_extensionbubble2Icon, &ui_img_1761657674);
            lv_obj_add_flag(ui_extensionbubble2Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 2:{
            lv_label_set_text(ui_extensionbubble3Value, sensor_data_1);
            lv_label_set_text(ui_extensionbubble3Unit, "°C");
            lv_img_set_src(ui_extensionbubble3Icon, &ui_img_1761657674);
            lv_obj_add_flag(ui_extensionbubble3Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 3:{
            lv_label_set_text(ui_extensionbubble4Value, sensor_data_1);
            lv_label_set_text(ui_extensionbubble4Unit, "°C");
            lv_img_set_src(ui_extensionbubble4Icon, &ui_img_1761657674);
            lv_obj_add_flag(ui_extensionbubble4Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Unit, LV_OBJ_FLAG_HIDDEN);

            break;
        }
    }

    switch(bubble_position[EXTENSION_HUMI])
    {
        case 0:{
            lv_label_set_text(ui_extensionbubble1Value, sensor_data_2);
            lv_label_set_text(ui_extensionbubble1Unit, "%");
            lv_img_set_src(ui_extensionbubble1Icon, &ui_img_1336611536);
            lv_obj_add_flag(ui_extensionbubble1Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 1:{
            lv_label_set_text(ui_extensionbubble2Value, sensor_data_2);
            lv_label_set_text(ui_extensionbubble2Unit, "%");
            lv_img_set_src(ui_extensionbubble2Icon, &ui_img_1955521171);
            lv_obj_add_flag(ui_extensionbubble2Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 2:{
            lv_label_set_text(ui_extensionbubble3Value, sensor_data_2);
            lv_label_set_text(ui_extensionbubble3Unit, "%");
            lv_img_set_src(ui_extensionbubble3Icon, &ui_img_1955521171);
            lv_obj_add_flag(ui_extensionbubble3Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 3:{
            lv_label_set_text(ui_extensionbubble4Value, sensor_data_2);
            lv_label_set_text(ui_extensionbubble4Unit, "%");
            lv_img_set_src(ui_extensionbubble4Icon, &ui_img_1955521171);
            lv_obj_add_flag(ui_extensionbubble4Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
    }

    switch(bubble_position[EXTENSION_CO2])
    {
        case 0:{
            lv_label_set_text(ui_extensionbubble1Value, sensor_data_3);
            lv_label_set_text(ui_extensionbubble1Unit, "ppm");
            lv_img_set_src(ui_extensionbubble1Icon, &ui_img_226867343);
            lv_obj_add_flag(ui_extensionbubble1Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 1:{
            lv_label_set_text(ui_extensionbubble2Value, sensor_data_3);
            lv_label_set_text(ui_extensionbubble2Unit, "ppm");
            lv_img_set_src(ui_extensionbubble2Icon, &ui_img_529164268);
            lv_obj_add_flag(ui_extensionbubble2Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 2:{
            lv_label_set_text(ui_extensionbubble3Value, sensor_data_3);
            lv_label_set_text(ui_extensionbubble3Unit, "ppm");
            lv_img_set_src(ui_extensionbubble3Icon, &ui_img_529164268);
            lv_obj_add_flag(ui_extensionbubble3Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 3:{
            lv_label_set_text(ui_extensionbubble4Value, sensor_data_3);
            lv_label_set_text(ui_extensionbubble4Unit, "ppm");
            lv_img_set_src(ui_extensionbubble4Icon, &ui_img_529164268);
            lv_obj_add_flag(ui_extensionbubble4Icon2, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Unit, LV_OBJ_FLAG_HIDDEN);
            break;
        }
    }

    switch(bubble_position[EXTENSION_BACK])
    {
        case 0:{
            lv_obj_add_flag(ui_extensionbubble1Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble1Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble1Unit, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble1Icon2, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 1:{
            lv_obj_add_flag(ui_extensionbubble2Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble2Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble2Unit, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble2Icon2, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 2:{
            lv_obj_add_flag(ui_extensionbubble3Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble3Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble3Unit, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble3Icon2, LV_OBJ_FLAG_HIDDEN);
            break;
        }
        case 3:{
            lv_obj_add_flag(ui_extensionbubble4Value, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble4Icon, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_extensionbubble4Unit, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_extensionbubble4Icon2, LV_OBJ_FLAG_HIDDEN);
            
            break;
        }
    }

    // for (int i = 0; i < 4; i++)
    // {
    //     ESP_LOGI(TAG, "bubble%d_position: %d", i, bubble_position[i]);
    // }
}

void rotate_positions(uint8_t positions[], int size, int direction)
{
    uint8_t temp[4];
    for (int i = 0; i < size; i++) {
        if (direction == 1) {
            temp[(i + 1) % size] = positions[i];
        } else {
            temp[(i + size - 1) % size] = positions[i];
        }
    }
    for (int i = 0; i < size; i++) {
        positions[i] = temp[i];
    }
}

void bubble2f_cb(lv_event_t * e)
{
    // ESP_LOGI(TAG, "bubble2f_cb");
    extensionscroll.cur_idx = 1;
    if(extensionscroll.cur_idx - extensionscroll.pre_idx == -2)
    {
        rotate_positions(bubble_position, 4, 1);
    } else {
        rotate_positions(bubble_position, 4, -1);
    }
    sensor_date_update();
    extensionscroll.pre_idx = extensionscroll.cur_idx;
}

void bubble2c_cb(lv_event_t * e)
{
    if(bubble_position[3] == 0)
    {
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
    }
}

void bubble3f_cb(lv_event_t * e)
{
    // ESP_LOGI(TAG, "bubble3f_cb");
    extensionscroll.cur_idx = 2;
    if(extensionscroll.cur_idx - extensionscroll.pre_idx == 1)
    {
        rotate_positions(bubble_position, 4, 1);
    } else {
        rotate_positions(bubble_position, 4, -1);
    }
    sensor_date_update();
    extensionscroll.pre_idx = extensionscroll.cur_idx;
}

void bubble3c_cb(lv_event_t * e)
{
    if(bubble_position[3] == 0)
    {
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
    }
}

void bubble4f_cb(lv_event_t * e)
{
    // ESP_LOGI(TAG, "bubble4f_cb");
    extensionscroll.cur_idx = 3;
    if(extensionscroll.cur_idx - extensionscroll.pre_idx == 1)
    {
        rotate_positions(bubble_position, 4, 1);
    } else {
        rotate_positions(bubble_position, 4, -1);
    }
    sensor_date_update();
    extensionscroll.pre_idx = extensionscroll.cur_idx;
}

void bubble4c_cb(lv_event_t * e)
{
    if(bubble_position[3] == 0)
    {
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
    }
}

void extensionpanel_cb(lv_event_t * e)
{
    if(bubble_position[3] == 0)
    {
        lv_pm_open_page(g_main, &group_page_main, PM_ADD_OBJS_TO_GROUP, &ui_Page_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page_Home_screen_init);
    }
}
/*----------------------------------------------push 2 talk------------------------------------------------------*/
void push2talk_init(void)
{
    push2talk_textarea = lv_textarea_create(ui_Page_Push2talk);
    lv_obj_set_width(push2talk_textarea, 280);
    lv_obj_set_height(push2talk_textarea, 90);
    // lv_obj_set_height(push2talk_textarea, LV_SIZE_CONTENT);
    lv_obj_set_x(push2talk_textarea, 0);
    lv_obj_set_y(push2talk_textarea, 120);
    lv_obj_set_align(push2talk_textarea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(push2talk_textarea, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_text_color(push2talk_textarea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(push2talk_textarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(push2talk_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(push2talk_textarea, &ui_font_fbold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(push2talk_textarea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(push2talk_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(push2talk_textarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(push2talk_textarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(push2talk_textarea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_placeholder_text(push2talk_textarea, "");
    // lv_textarea_set_one_line(push2talk_textarea, true);
    lv_textarea_set_cursor_pos(push2talk_textarea, LV_TEXTAREA_CURSOR_LAST);
    lv_obj_set_scrollbar_mode(push2talk_textarea, LV_SCROLLBAR_MODE_OFF);
}

static void view_push2talk_animation_timer_callback(lv_timer_t *timer)
{
    // static uint32_t last_time = 0;
    // uint32_t current_time = lv_tick_get();

    // if (last_time != 0) {
    //     ESP_LOGI("view_push2talk_animation", "Time since last tick: %u ms\n", current_time - last_time);
    // }
    // last_time = current_time;

    if (push2talk_text && push2talk_text[push2talk_text_index] != '\0' && push2talk_timer_active) {
        char temp[4];
        int i;
        for (i = 0; i < 3 && push2talk_text[push2talk_text_index] != '\0'; i++) {
            temp[i] = push2talk_text[push2talk_text_index];
            push2talk_text_index++;
        }
        temp[i] = '\0';
        lv_textarea_add_text(push2talk_textarea, temp);
    } else {
        push2talk_timer_active = false;
        lv_timer_pause(view_push2talk_animation_timer);

        if (push2talk_text) {
            free(push2talk_text);
            push2talk_text = NULL;
        }
    }
}

void view_push2talk_animation_timer_start(uint32_t interval_ms)
{
    if (view_push2talk_animation_timer == NULL) {
        view_push2talk_animation_timer = lv_timer_create(view_push2talk_animation_timer_callback, interval_ms, NULL);
    } else {
        lv_timer_set_period(view_push2talk_animation_timer, interval_ms);
        lv_timer_resume(view_push2talk_animation_timer);
    }
}

void view_push2talk_animation_timer_stop()
{
    if (view_push2talk_animation_timer != NULL) {
        lv_timer_pause(view_push2talk_animation_timer);
    }
}

void push2talk_start_animation(const char *text, uint32_t duration_ms)
{
    ESP_LOGI(TAG, "Starting animation with text: %s, duration: %d", text, duration_ms);

    char *formatted_text = strdup(text);
    if (!formatted_text) return;
    for (int i = 0; i < strlen(formatted_text); i++) {
        if (formatted_text[i] == '\n') {
            formatted_text[i] = ' ';
        }
    }

    if (text == NULL || text[0] == '\0') {
        ESP_LOGE(TAG, "Invalid parameters for start animation");
        return;
    }
    if(duration_ms == 0) {
        ESP_LOGW(TAG, "Duration is 0, setting to default value");
        duration_ms = 10000;
    }
    if (push2talk_timer_active) {
        view_push2talk_animation_timer_stop();
        push2talk_timer_active = false;

        if (push2talk_text) {
            free(push2talk_text);
            push2talk_text = NULL;
        }
    }

    push2talk_text = formatted_text;
    if (push2talk_text == NULL) {
        ESP_LOGE(TAG, "Failed to allocate memory for push2talk_text");
        return;
    }

    push2talk_timer_active = true;
    push2talk_text_index = 0;
    lv_textarea_set_text(push2talk_textarea, "");

    uint32_t text_length = strlen(text);
    uint32_t push2talk_anim_interval = (duration_ms) / (text_length / 3);
    if (push2talk_anim_interval < 1) {
        push2talk_anim_interval = 10;
    }

    ESP_LOGI(TAG, "interval: %d, text_length: %d, duration: %dms ", push2talk_anim_interval, text_length, duration_ms);
    view_push2talk_animation_timer_start(push2talk_anim_interval - 25);
}
/*--------------------------------------------view timer----------------------------------------------------------------*/
static void view_ble_switch_timer_callback(lv_timer_t *timer)
{
    lv_obj_clear_state(ui_setblesw, LV_STATE_DISABLED);
}

void view_ble_switch_timer_start()
{
    if (view_ble_switch_timer != NULL) {
        lv_timer_del(view_ble_switch_timer);
        view_ble_switch_timer = NULL;
    }
    view_ble_switch_timer = lv_timer_create(view_ble_switch_timer_callback, 1000, NULL); // 1000 ms = 1 second
}

static void view_sleep_timer_callback(lv_timer_t *timer)
{
    inactive_time = lv_disp_get_inactive_time(NULL);
    get_inactive_time = g_screenoff_time;
    if((inactive_time % (30*1000)) < 2000)
    {
        ESP_LOGI("view_inactive", "inactive_time: %d, screenoff_time: %d, screenoff_mode: %d", inactive_time, g_screenoff_time, screenoff_mode);
        ESP_LOGI("view_inactive", "standby_mode: %d, is_taskdown: %d", standby_mode, g_taskdown);
    }

    switch (get_inactive_time) {
        case 0:
            inactive_threshold = 0;
            break;
        case 1:
            inactive_threshold = (1 * 60 * 1000);
            break;
        case 2:
            inactive_threshold = (5 * 60 * 1000);
            break;
        case 3:
            inactive_threshold = (10 * 60 * 1000);
            break;
        case 4:
            inactive_threshold = (15 * 60 * 1000);
            break;
        case 5:
            inactive_threshold = (30 * 60 * 1000);
            break;
        case 6:
            inactive_threshold = (24 * 60 * 60 * 1000);
            break;
        default:
            inactive_threshold = 0;
            break;
    }
    // extension scroll play
    if(inactive_time > (60 * 1000) && lv_scr_act()== ui_Page_Extension && (!extension_scroll_mode))
    {
        view_extension_timer_start();
        extension_scroll_mode = 1;
    }

    // standby mode
    if(inactive_time > (5 * 60 * 1000) && standby_mode == 0 && g_taskdown && lv_scr_act() != ui_Page_Extension)
    {
        ESP_LOGI(TAG, "Standby mode active");

        emoji_switch_scr = SCREEN_STANDBY;
        emoji_timer(EMOJI_STANDBY);
        lv_obj_clear_flag(ui_Page_Standby, LV_OBJ_FLAG_HIDDEN);

        standby_mode = 1;
    }else if(standby_mode == 1 && !g_taskdown)
    {
        ESP_LOGI(TAG, "Standby mode deactive");

        emoji_switch_scr = SCREEN_AVATAR;
        lv_obj_add_flag(ui_Page_Standby, LV_OBJ_FLAG_HIDDEN);
        emoji_timer_stop();

        standby_mode = 0;
    }

    // sleep mode
    if(inactive_time > inactive_threshold)
    {
        if(get_inactive_time > 0 && screenoff_mode == 0 && lv_scr_act() != ui_Page_Avatar)
        {
            ESP_LOGI(TAG, "Sleep mode active");
            bsp_lcd_brightness_set(0);
            screenoff_mode = 1;
        }

        if(get_inactive_time == 0 && screenoff_mode == 1)
        {
            ESP_LOGI(TAG, "Sleep mode deactive");
            int brightness = get_brightness(UI_CALLER);
            bsp_lcd_brightness_set(brightness);
            screenoff_mode = 0;
        }
    }


    // deactivate sleep mode and stanby mode
    if(inactive_time < ACTIVE_THRESHOLD)
    {
        if(screenoff_mode != 0)
        {
            ESP_LOGI(TAG, "Sleep mode deactive");
            int brightness = get_brightness(UI_CALLER);
            bsp_lcd_brightness_set(brightness);
            screenoff_mode = 0;
        }

        if(standby_mode != 0)
        {
            ESP_LOGI(TAG, "Standby mode deactive");

            lv_obj_add_flag(ui_Page_Standby, LV_OBJ_FLAG_HIDDEN);
            emoji_timer_stop();

            standby_mode = 0;
        }

        if(extension_scroll_mode != 0)
        {
            view_extension_timer_stop();
            extension_scroll_mode = 0;
        }
    }
}

void view_sleep_timer_start()
{
    if (view_sleep_timer != NULL) {
        lv_timer_del(view_sleep_timer);
    }
    view_sleep_timer = lv_timer_create(view_sleep_timer_callback, 1000, NULL); // 1000 ms = 1 second
}

void view_sleep_timer_stop()
{
    if (view_sleep_timer != NULL) {
        lv_timer_del(view_sleep_timer);
        view_sleep_timer = NULL;
    }
}

static void view_push2talk_timer_callback(lv_timer_t *timer)
{
    ESP_LOGI(TAG, "view_push2talk_timer_callback");
    static int16_t push2talk_arc;
    static int push2talk_run_taskflow_exit = 1;

    if(g_push2talk_timer == 0)
    {
        push2talk_timer_counter++;
        if(push2talk_timer_counter==10){
            if(g_push2talk_mode == 2)
            {
                view_push2talk_timer_stop();
                esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE, VIEW_EVENT_VI_EXIT, &push2talk_run_taskflow_exit, sizeof(push2talk_run_taskflow_exit), pdMS_TO_TICKS(10000));
                esp_event_post_to(app_event_loop_handle, VIEW_EVENT_BASE,  \
                                    VIEW_EVENT_TASK_FLOW_START_CURRENT_TASK, NULL, 0, pdMS_TO_TICKS(10000));
                push2talk_timer_counter = 0;
                g_is_push2talk = 0;
            }
            if(g_push2talk_mode == 0)
            {
                lv_event_send(ui_Page_Push2talk, LV_EVENT_CLICKED, NULL);
                push2talk_timer_counter = 0;
            }
        }
    }else{
        push2talk_arc = lv_arc_get_value(ui_push2talkarc);
        lv_arc_set_value(ui_push2talkarc, push2talk_arc+1);
        lv_event_send(ui_push2talkarc, LV_EVENT_VALUE_CHANGED, NULL);
    }
    // ESP_LOGI(TAG, "g_push2talk_timer: %d, g_push2talk_mode: %d, push2talk_timer_counter: %d ", g_push2talk_timer, g_push2talk_mode, push2talk_timer_counter);
}

void view_push2talk_timer_start()
{
    if (view_push2talk_timer != NULL) {
        lv_timer_del(view_push2talk_timer);
    }
    push2talk_timer_counter = 0;
    view_push2talk_timer = lv_timer_create(view_push2talk_timer_callback, 1000, NULL); // 1000 ms = 1 second
}

void view_push2talk_timer_stop()
{
    if (view_push2talk_timer != NULL) {
        lv_timer_del(view_push2talk_timer);
        view_push2talk_timer = NULL;
    }
}

static void view_push2talk_msg_timer_callback(lv_timer_t *timer)
{
    lv_obj_t *push2talk_panel_child;
    ESP_LOGI(TAG, "push2talk_panel_idx is %d ", push2talk_panel_idx);

    if(push2talk_item[push2talk_panel_idx]){
        switch (push2talk_panel_idx)
        {
        case 0:
            lv_label_set_text(ui_p2tobj2, push2talk_item[push2talk_panel_idx]);
            lv_obj_clear_flag(ui_p2tobj, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2tobj);
            lv_group_focus_obj(ui_p2tobj);
            break;
        case 1:
            lv_label_set_text(ui_p2tcomparison2, push2talk_item[push2talk_panel_idx]);
            lv_obj_clear_flag(ui_p2tcomparison, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2tcomparison);
            lv_group_focus_obj(ui_p2tcomparison);
            break;
        case 2:
            lv_label_set_text(ui_p2tbehavior2, push2talk_item[push2talk_panel_idx]);
            lv_obj_clear_flag(ui_p2tbehavior, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2tbehavior);
            lv_group_focus_obj(ui_p2tbehavior);
            break;
        case 3:
            lv_label_set_text(ui_p2tfeat2, push2talk_item[push2talk_panel_idx]);
            lv_obj_clear_flag(ui_p2tfeat, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2tfeat);
            lv_group_focus_obj(ui_p2tfeat);
            break;
        case 4:
            lv_label_set_text(ui_p2tnotify2, push2talk_item[push2talk_panel_idx]);
            lv_obj_clear_flag(ui_p2tnotify, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2tnotify);
            lv_group_focus_obj(ui_p2tnotify);
            break;
        case 5:
            lv_label_set_text(ui_p2ttime2, push2talk_item[push2talk_panel_idx]);
            lv_obj_clear_flag(ui_p2ttime, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2ttime);
            lv_group_focus_obj(ui_p2ttime);
            break;
        case 6:
            lv_label_set_text(ui_p2tfreq2, push2talk_item[push2talk_panel_idx]);
            lv_obj_clear_flag(ui_p2tfreq, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2tfreq);
            lv_group_focus_obj(ui_p2tfreq);
            break;
        case 7:
            lv_obj_clear_flag(ui_p2tcancel, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_p2tcheck, LV_OBJ_FLAG_HIDDEN);
            lv_group_add_obj(g_main, ui_p2tcancel);
            lv_group_add_obj(g_main, ui_p2tcheck);
            lv_group_focus_obj(ui_p2tcheck);
            break;
        
        default:
            break;
        }
    }

    push2talk_panel_idx++;
    if (push2talk_panel_idx >= 8)
    {
        view_push2talk_msg_timer_stop();
        push2talk_panel_idx = 0;
    }
}

void view_push2talk_msg_timer_start()
{
    if (view_push2talk_msg_timer != NULL) {
        lv_timer_del(view_push2talk_msg_timer);
    }
    view_push2talk_msg_timer = lv_timer_create(view_push2talk_msg_timer_callback, 500, NULL); // 500 ms
}

void view_push2talk_msg_timer_stop()
{
    if (view_push2talk_msg_timer != NULL) {
        lv_timer_del(view_push2talk_msg_timer);
        view_push2talk_msg_timer = NULL;
    }
}

static void view_extension_timer_callback(lv_timer_t *timer)
{
    ESP_LOGI(TAG, "view_extension_timer_callback");
    rotate_positions(bubble_position, 4, 1);
    if(bubble_position[3]==0)rotate_positions(bubble_position, 4, 1);

    sensor_date_update();
}

void view_extension_timer_start()
{
    if (view_extension_timer != NULL) {
        lv_timer_del(view_extension_timer);
    }
    view_extension_timer = lv_timer_create(view_extension_timer_callback, 1000 * 60, NULL);

}

void view_extension_timer_stop()
{
    if (view_extension_timer != NULL) {
        lv_timer_del(view_extension_timer);
        view_extension_timer = NULL;
    }
}

static void view_push2talk_expired_timer_callback(lv_timer_t * timer)
{
    ESP_LOGI(TAG, "view_push2talk_expired_timer_callback");
    lv_event_send(ui_p2tcancel, LV_EVENT_CLICKED, NULL);
    view_push2talk_expired_timer = NULL;
}

void view_push2talkexpired_timer_stop()
{
    ESP_LOGI(TAG, "view_push2talkexpired_timer_stop");
    if (view_push2talk_expired_timer != NULL) {
        lv_timer_del(view_push2talk_expired_timer);
        view_push2talk_expired_timer = NULL;
    }
}

void view_push2talkexpired_timer_start()
{
    ESP_LOGI(TAG, "view_push2talkexpired_timer_start");
    if (view_push2talk_expired_timer != NULL) {
        lv_timer_del(view_push2talk_expired_timer);
        view_push2talk_expired_timer = NULL;
    }

    view_push2talk_expired_timer = lv_timer_create(view_push2talk_expired_timer_callback, 900 * 600, NULL);
    if (view_push2talk_expired_timer != NULL) {
        lv_timer_set_repeat_count(view_push2talk_expired_timer, 1);
        ESP_LOGI(TAG, "Timer successfully created and started.");
    } else {
        ESP_LOGE(TAG, "Failed to create view_push2talk_expired_timer");
    }
}